# Few-Shot Example Selection

## Overview

Few-shot prompting requires representative examples that demonstrate how flaky and non-flaky tests should be analyzed.

Rather than selecting examples arbitrarily, representative examples were selected from the preprocessed dataset using quantitative criteria. The goal was to choose examples that are representative of typical test cases while avoiding unusually small or extremely large artifacts that could bias the evaluation.

The selected examples will be used only as demonstrations in the few-shot prompts. These examples are removed from the evaluation dataset to prevent data leakage during model evaluation.

In [58]:
from pathlib import Path

import pandas as pd

In [59]:
# ============================================================
# Load Preprocessed Dataset
# ============================================================

PROJECT_ROOT = Path.cwd().parent

DATASET_PATH = (
    PROJECT_ROOT
    / "datasets"
    / "context_augmented_dataset_preprocessed.jsonl"
)

working_df = pd.read_json(
    DATASET_PATH,
    lines=True
)

working_df["isFlaky"] = working_df["isFlaky"].astype(bool)

print("=" * 80)
print("DATASET LOADED")
print("=" * 80)
print(f"Total Records : {len(working_df)}")

================================================================================
DATASET LOADED
================================================================================
Total Records : 2743

## Compute Artifact Statistics

The dataset contains multiple contextual artifacts with varying sizes.

To identify representative examples, descriptive statistics are first computed for each artifact. These statistics are later used to identify examples whose artifact sizes are close to the central tendency of the dataset.

In [61]:
candidate_df = working_df.copy()

candidate_df["test_length"] = candidate_df["test_code"].str.len()

candidate_df["helper_count"] = candidate_df["helper_methods_json"].apply(
    lambda x: len(x) if isinstance(x, dict) else 0
)

candidate_df["failure_length"] = candidate_df["failure_log"].str.len()

candidate_df["production_classes"] = candidate_df["code_under_test_json"].apply(
    lambda x: len(x) if isinstance(x, dict) else 0
)

candidate_df["artifact_completeness"] = (
    (candidate_df["test_length"] > 0).astype(int)
    + (candidate_df["failure_length"] > 0).astype(int)
    + (candidate_df["production_classes"] > 0).astype(int)
    + (candidate_df["helper_count"] > 0).astype(int)
)

In [20]:
summary = candidate_df[
    [
        "test_length",
        "helper_count",
        "failure_length",
        "production_classes",
        "artifact_completeness"
    ]
].describe()

display(summary)

,test_length,helper_count,failure_length,production_classes,artifact_completeness
count,2745.000000,2745.000000,2745.000000,2745.000000,2745.000000
mean,710.868488,0.856466,3226.079781,10.938069,3.491075
std,913.269735,1.310065,6210.939116,23.031142,0.520019
min,55.000000,0.000000,0.000000,0.000000,2.000000
25%,296.000000,0.000000,1625.000000,1.000000,3.000000
50%,458.000000,1.000000,2933.000000,4.000000,4.000000
75%,851.000000,1.000000,3395.000000,9.000000,4.000000
max,21275.000000,20.000000,165904.000000,312.000000,4.000000

## Identify Representative Candidate Examples

Representative candidates are selected using the following objective criteria:

- Complete contextual information (artifact completeness = 4).
- Artifact sizes close to the median of the dataset.
- Moderate production code context.
- Representative of the corresponding class.

These criteria reduce the likelihood of selecting trivial or unusually large examples while ensuring that the demonstrations resemble a typical sample from the dataset.

In [21]:
# ============================================================
# Dataset Medians
# ============================================================

median_test = candidate_df["test_length"].median()
median_failure = candidate_df["failure_length"].median()
median_production = candidate_df["production_classes"].median()

# ============================================================
# Normalized Distance from Dataset Median
# ============================================================

candidate_df["distance_from_median"] = (

    abs(candidate_df["test_length"] - median_test) / median_test

    + abs(candidate_df["failure_length"] - median_failure) / median_failure

    + abs(candidate_df["production_classes"] - median_production) / median_production

)

## Construct Candidate Pools

Candidate pools are created by separating flaky and non-flaky test cases.

The representative ranking is then performed independently within each class to identify suitable demonstration examples.

In [35]:
# ============================================================
# Construct Candidate Pools
# ============================================================

flaky_candidates = candidate_df[
    candidate_df["isFlaky"]
].copy()

non_flaky_candidates = candidate_df[
    ~candidate_df["isFlaky"]
].copy()

print(f"Flaky Candidates     : {len(flaky_candidates)}")
print(f"Non-Flaky Candidates : {len(non_flaky_candidates)}")

Flaky Candidates     : 1107
Non-Flaky Candidates : 1638

In [37]:
flaky_ranked = (
    flaky_candidates
    .sort_values("distance_from_median")
    .copy()
)

non_flaky_ranked = (
    non_flaky_candidates
    .sort_values("distance_from_median")
    .copy()
)

## Top Representative Candidates

The highest ranked flaky and non-flaky candidates are inspected manually before final selection.

Although the ranking identifies statistically representative records, a manual inspection is still required to ensure that the selected examples are understandable, contain meaningful contextual artifacts, and clearly illustrate the intended reasoning process.

In [38]:
columns = [
    "test_id",
    "issue_category",
    "test_length",
    "helper_count",
    "failure_length",
    "production_classes",
    "distance_from_median"
]

display(flaky_ranked[columns].head(15))

,test_id,issue_category,test_length,helper_count,failure_length,production_classes,distance_from_median
180,fastjsonf164d85test_for_issue4,Implementation Dependent,505,0,2896,4,0.115235
758,OpenRefinemaina68ba3btestSelectedEmptyChoice,Implementation Dependent,541,1,2962,4,0.191110
757,OpenRefinemaina68ba3bserializeListFacet,Implementation Dependent,547,1,2957,4,0.202506
789,jolokiasupportspring275165bsystemProperties,Implementation Dependent,535,1,3088,4,0.220969
182,fastjson803fd73test_for_issue8,Implementation Dependent,318,0,2685,4,0.390232
687,snakeyaml626340btestBoolOutAsEmpty32,Implementation Dependent,407,2,2710,3,0.437385
904,wildflynaming3a83b7b10,Order Dependent,363,2,2925,3,0.460151
67,avrolangjavaavro7fd098atestRecord,Implementation Dependent,286,1,3459,4,0.554884
48,bladebladecoreaa32ce9testCreateRouteBuilder,Implementation Dependent,517,0,3525,3,0.580662
670,slingorgapacheslingservletsget1cea3aetestBoole...,Implementation Dependent,516,1,3662,5,0.625189
2,fastjson194b299test_f12,Implementation Dependent,638,0,2913,3,0.649832
254,JSONjava1be6ee3queryByEmptyKeySubObject,Implementation Dependent,214,1,3349,4,0.674585
440,hutoolhutoolcore33121a4getCombinationAnnotatio...,Implementation Dependent,335,0,3417,5,0.683578
918,dubbodubborpcdubborpcdubboaa9f16e,Order Dependent,197,0,2585,4,0.688519
893,wikidatatoolkitwdtkutil10f9711,Order Dependent,395,0,2760,2,0.696539

In [39]:
columns = [
    "test_id",
    "test_length",
    "helper_count",
    "failure_length",
    "production_classes",
    "distance_from_median"
]

display(non_flaky_ranked[columns].head(15))

,test_id,test_length,helper_count,failure_length,production_classes,distance_from_median
1951,JacksonCore-21-2,452,4,2786,4,0.063220
1959,JacksonCore-22-7,490,4,2888,4,0.085212
1956,JacksonCore-22-4,494,4,2889,4,0.093604
1125,Cli-15-1,447,1,2704,4,0.102095
1111,Cli-4-2,446,0,2707,4,0.103255
1361,Closure-64,414,1,2881,4,0.113799
1155,Cli-31,485,0,2729,4,0.128505
2157,Jsoup-25,444,0,3235,4,0.133534
2218,Jsoup-61-2,458,0,3347,4,0.141152
2695,Time-12-2,400,0,2875,4,0.146413
2694,Time-12-1,399,0,2874,4,0.148937
2697,Time-12-4,398,0,2879,4,0.149416
2696,Time-12-3,397,0,2878,4,0.151940
2676,Time-3-4,410,0,2779,4,0.157309
2517,Math-64-1,404,2,3063,4,0.162227

## Candidate Inspection

The ranking procedure identifies representative candidates based on artifact sizes.

However, multiple highly ranked candidates may originate from the same software project and therefore represent nearly identical testing scenarios.

To improve diversity, a small number of highly ranked candidates from different projects are manually inspected before selecting the final demonstrations.

In [40]:
def inspect_candidate(index):

    sample = working_df.loc[index]

    print("=" * 80)
    print(f"Index : {index}")
    print(f"Test ID : {sample['test_id']}")
    print(f"Flaky : {sample['isFlaky']}")
    print(f"Category : {sample['issue_category']}")
    print("=" * 80)

    print("\nArtifact Summary")
    print("-" * 80)
    print(f"Test Length         : {len(sample['test_code'])}")
    print(f"Helper Methods      : {len(sample['helper_methods_json']) if isinstance(sample['helper_methods_json'], dict) else 0}")
    print(f"Failure Log Length  : {len(sample['failure_log'])}")
    print(f"Production Classes  : {len(sample['code_under_test_json']) if isinstance(sample['code_under_test_json'], dict) else 0}")

    print("\n" + "=" * 80)
    print("TEST CODE")
    print("=" * 80)
    print(sample["test_code"])

    print("\n" + "=" * 80)
    print("HELPER METHODS")
    print("=" * 80)
    print(sample["helper_methods_json"])

    print("\n" + "=" * 80)
    print("FAILURE LOG")
    print("=" * 80)
    print(sample["failure_log"])

    print("\n" + "=" * 80)
    print("PRODUCTION CODE")
    print("=" * 80)
    print(sample["code_under_test_json"])

In [ ]:
inspect_candidate(758)
inspect_candidate(789)
inspect_candidate(904)

================================================================================
Index : 758
Test ID : OpenRefinemaina68ba3btestSelectedEmptyChoice
Flaky : True
Category : Implementation Dependent
================================================================================

Artifact Summary
--------------------------------------------------------------------------------
Test Length         : 541
Helper Methods      : 1
Failure Log Length  : 2962
Production Classes  : 4

================================================================================
TEST CODE
================================================================================
@Test
    public void testSelectedEmptyChoice() throws IOException {
        Project project = createCSVProject("Column A\n" +
                "a\n" +
                "c\n" +
                "e");
        Engine engine = new Engine(project);

        ListFacetConfig facetConfig = ParsingUtilities.mapper.readValue(jsonConfig, ListFacetConfig.class);
        Facet facet = facetConfig.apply(project);
        facet.computeChoices(project, engine.getAllFilteredRows());
        TestUtils.isSerializedTo(facet, selectedEmptyChoiceFacet);
    }

================================================================================
HELPER METHODS
================================================================================
{'createCSVProject': 'protected Project createCSVProject(String input) {\n        return createCSVProject("test project", input);\n    }'}

================================================================================
FAILURE LOG
================================================================================
java.lang.AssertionError: Objects above are not equal as JSON strings.
	at org.testng.Assert.fail(Assert.java:110)
	at com.google.refine.util.TestUtils.assertEqualsAsJson(TestUtils.java:88)
	at com.google.refine.util.TestUtils.isSerializedTo(TestUtils.java:121)
	at com.google.refine.util.TestUtils.isSerializedTo(TestUtils.java:132)
	at com.google.refine.browsing.facets.ListFacetTests.testSelectedEmptyChoice(ListFacetTests.java:131)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.testng.TestRunner.privateRun(TestRunner.java:829)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
	at org.testng.SuiteRunner.run(SuiteRunner.java:330)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
	at org.testng.TestNG.runSuites(TestNG.java:1099)
	at org.testng.TestNG.run(TestNG.java:1067)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:155)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:102)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:91)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:137)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)

================================================================================
PRODUCTION CODE
================================================================================
{'com.google.refine.RefineTest': {'createCSVProject': 'protected Project createCSVProject(String input) {\n        return createCSVProject("test project", input);\n    }'}, 'com.google.refine.browsing.Engine': {'<init>': 'public Engine(Project project) {\n        _project = project;\n    }', 'Engine': 'public Engine(Project project) {\n        _project = project;\n    }', 'getAllFilteredRows': '@JsonIgnore\n    public FilteredRows getAllFilteredRows() {\n        return getFilteredRows(null);\n    }'}, 'com.google.refine.model.Project': {'<init>': 'public Project() {\n        this(generateID());\n    }'}, 'com.google.refine.util.TestUtils': {'assertEqualsAsJson': 'public static void assertEqualsAsJson(String actual, String expected) {\n        try {\n            JsonNode jsonA = mapper.readValue(expected, JsonNode.class);\n            JsonNode jsonB = mapper.readValue(actual, JsonNode.class);\n            if (!jsonA.equals(jsonB)) {\n                jsonDiff(expected, actual);\n                fail("Objects above are not equal as JSON strings.");\n            }\n        } catch (Exception e) {\n            fail("\\"" + actual + "\\" and \\"" + expected + "\\" are not equal as JSON strings.");\n        }\n    }', 'isSerializedTo': 'public static void isSerializedTo(Object o, String targetJson, boolean saveMode) {\n\n        try {\n            ObjectWriter writer = null;\n            if (saveMode) {\n                writer = ParsingUtilities.saveWriter;\n            } else {\n                writer = ParsingUtilities.defaultWriter;\n            }\n            String jacksonJson = writer.writeValueAsString(o);\n            assertEqualsAsJson(jacksonJson, targetJson);\n        } catch (JsonProcessingException e) {\n            e.printStackTrace();\n            fail("jackson serialization failed");\n        }\n    }'}}
================================================================================
Index : 789
Test ID : jolokiasupportspring275165bsystemProperties
Flaky : True
Category : Implementation Dependent
================================================================================

Artifact Summary
--------------------------------------------------------------------------------
Test Length         : 535
Helper Methods      : 1
Failure Log Length  : 3088
Production Classes  : 4

================================================================================
TEST CODE
================================================================================
@Test
    public void systemProperties() throws Exception {
        checkSystemPropertyMode("fallback","/jol/","/j4p/","/j4p/");
        checkSystemPropertyMode("fallback","/jol/",null,"/jol/");
        checkSystemPropertyMode("fallback",null,null,"/jolokia/");

        checkSystemPropertyMode("override","/jol/","/j4p/","/jol/");
        checkSystemPropertyMode("override","/jol/",null,"/jol/");
        checkSystemPropertyMode("override",null,null,"/jolokia/");

        checkSystemPropertyMode(null,"/jol/",null,"/jolokia/");
    }

================================================================================
HELPER METHODS
================================================================================
{'checkSystemPropertyMode': 'private void checkSystemPropertyMode(String mode,String propContext,String configContext,String expectContext) throws Exception {\n        if (propContext != null) {\n            System.setProperty("jolokia.agentContext", propContext);\n        }\n        SpringJolokiaAgent server = new SpringJolokiaAgent();\n        server.setConfig(getConfig(true,100,"agentContext", configContext));\n        server.setSystemPropertiesMode(mode);\n        server.afterPropertiesSet();\n        assertEquals(server.getServerConfig().getContextPath(), expectContext);\n        System.getProperties().remove("jolokia.agentContext");\n        checkServerAndStop(server);\n\n        Thread.sleep(500);\n    }'}

================================================================================
FAILURE LOG
================================================================================
java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:111)
	at org.testng.Assert.failNotEquals(Assert.java:1578)
	at org.testng.Assert.assertTrue(Assert.java:57)
	at org.testng.Assert.assertTrue(Assert.java:67)
	at org.jolokia.support.spring.BaseServerTest.checkServerAndStop(BaseServerTest.java:38)
	at org.jolokia.support.spring.SpringJolokiaServerTest.checkSystemPropertyMode(SpringJolokiaServerTest.java:69)
	at org.jolokia.support.spring.SpringJolokiaServerTest.systemProperties(SpringJolokiaServerTest.java:48)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.testng.TestRunner.privateRun(TestRunner.java:739)
	at org.testng.TestRunner.run(TestRunner.java:614)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
	at org.testng.SuiteRunner.run(SuiteRunner.java:312)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
	at org.testng.TestNG.runSuites(TestNG.java:1112)
	at org.testng.TestNG.run(TestNG.java:1079)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:155)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:102)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:91)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:137)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)

================================================================================
PRODUCTION CODE
================================================================================
{'org.jolokia.jvmagent.JolokiaServerConfig': {'getContextPath': 'public String getContextPath() {\n        return context;\n    }'}, 'org.jolokia.support.spring.SpringJolokiaAgent': {'afterPropertiesSet': 'public void afterPropertiesSet() throws IOException {\n        Map<String, String> config = new HashMap<>();\n        if (systemPropertyMode == SystemPropertyMode.FALLBACK) {\n            config.putAll(lookupSystemProperties());\n        }\n        if (configHolder.getConfig() != null) {\n            config.putAll(configHolder.getConfig());\n        }\n\n        if (lookupConfig && context != null) {\n            config.putAll(lookupConfigurationFromContext());\n        }\n\n        if (systemPropertyMode == SystemPropertyMode.OVERRIDE) {\n            config.putAll(lookupSystemProperties());\n        }\n\n        boolean autoStart = Boolean.parseBoolean(config.remove("autoStart"));\n\n        LogHandler logHandler = logHandlerHolder != null ? logHandlerHolder.getLogHandler() : null;\n        init(new JolokiaServerConfig(config), logHandler);\n\n        if (exposeApplicationContext && context != null) {\n            addService(new SpringRequestHandler(context, 100));\n        }\n\n        if (lookupServices) {\n            lookupServices();\n        }\n\n        if (autoStart) {\n            start();\n        }\n    }', 'destroy': 'public void destroy() {\n        stop();\n    }', 'getServerConfig': '@SuppressWarnings("unused")\n    public JolokiaServerConfig getServerConfig() {\n        return config;\n    }', 'lookupSystemProperties': 'private Map<String, String> lookupSystemProperties() {\n        Map<String,String> ret = new HashMap<>();\n        Enumeration<?> propEnum = System.getProperties().propertyNames();\n        while (propEnum.hasMoreElements()) {\n            String prop = (String) propEnum.nextElement();\n            if (prop.startsWith("jolokia.")) {\n                String key = prop.substring("jolokia.".length());\n                ret.put(key,System.getProperty(prop));\n            }\n        }\n        return ret;\n    }', 'setConfig': 'public void setConfig(SpringJolokiaConfigHolder pConfig) {\n        configHolder = pConfig;\n    }', 'setSystemPropertiesMode': 'public void setSystemPropertiesMode(String pMode) {\n        systemPropertyMode = SystemPropertyMode.fromMode(pMode);\n        if (systemPropertyMode == null) {\n            systemPropertyMode = SystemPropertyMode.NEVER;\n        }\n    }'}, 'org.jolokia.support.spring.SpringJolokiaConfigHolder': {'getConfig': 'public Map<String, String> getConfig() {\n        return config;\n    }', 'setConfig': 'public void setConfig(Map<String, String> pConfig) {\n        config = pConfig;\n    }', 'setOrder': 'public void setOrder(int pOrder) {\n        order = pOrder;\n    }'}, 'org.jolokia.support.spring.SystemPropertyMode': {'fromMode': 'public static SystemPropertyMode fromMode(String pMode) {\n        if (pMode != null) {\n            for (SystemPropertyMode m : SystemPropertyMode.values()) {\n                if (m.mode.equals(pMode.toLowerCase())) {\n                    return m;\n                }\n            }\n        }\n        return null;\n    }'}}
================================================================================
Index : 904
Test ID : wildflynaming3a83b7b10
Flaky : True
Category : Order Dependent
================================================================================

Artifact Summary
--------------------------------------------------------------------------------
Test Length         : 363
Helper Methods      : 2
Failure Log Length  : 2925
Production Classes  : 3

================================================================================
TEST CODE
================================================================================
@Test
    public void testLookupBinding() throws Exception {
        final ServiceName bindingName = ServiceName.JBOSS.append("foo", "bar");
        final Object value = new Object();
        bindObject(bindingName, value);

        final Object obj = store.lookup(new CompositeName("foo/bar"));
        assertNotNull(obj);
        assertEquals(value, obj);
    }

================================================================================
HELPER METHODS
================================================================================
{'bindObject': 'private void bindObject(final ServiceName serviceName, final Object value) throws Exception {\n        final CountDownLatch latch = new CountDownLatch(1);\n        container.addService(serviceName, new Service<ManagedReferenceFactory>() {\n            public void start(StartContext context) throws StartException {\n                store.add(serviceName);\n                latch.countDown();\n            }\n\n            public void stop(StopContext context) {\n            }\n\n            public ManagedReferenceFactory getValue() throws IllegalStateException, IllegalArgumentException {\n                return new ValueManagedReferenceFactory(Values.immediateValue(value));\n            }\n        }).install();\n        latch.await();\n    }', 'lookup': '@Override\n            public Object lookup(Name name) throws NamingException {\n                if ("blah/blah2".equals(name.toString())) {\n                    return new Integer(5);\n                }\n\n                return null;\n            }'}

================================================================================
FAILURE LOG
================================================================================
javax.naming.NamingException: WFLYNAM0062: Failed to lookup foo/bar [Root exception is java.lang.NoClassDefFoundError: Could not initialize class org.wildfly.security.manager.WildFlySecurityManager]
	at org.jboss.as.naming.ServiceBasedNamingStore.lookup(ServiceBasedNamingStore.java:159)
	at org.jboss.as.naming.ServiceBasedNamingStore.lookup(ServiceBasedNamingStore.java:83)
	at org.jboss.as.naming.ServiceBasedNamingStore.lookup(ServiceBasedNamingStore.java:75)
	at org.jboss.as.naming.ServiceBasedNamingStoreTestCase.testLookupBinding(ServiceBasedNamingStoreTestCase.java:96)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:385)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:285)

In [ ]:
inspect_candidate(1951)
inspect_candidate(1125)
inspect_candidate(1361)

================================================================================
Index : 1951
Test ID : JacksonCore-21-2
Flaky : False
Category : Non-Flaky
================================================================================

Artifact Summary
--------------------------------------------------------------------------------
Test Length         : 452
Helper Methods      : 4
Failure Log Length  : 2786
Production Classes  : 4

================================================================================
TEST CODE
================================================================================
@SuppressWarnings("resource")
    public void testBasicSingleMatchFilteringWithPath() throws Exception
    {
        JsonParser p0 = JSON_F.createParser(SIMPLE);
        JsonParser p = new FilteringParserDelegate(p0,
               new NameMatchFilter("value"),
                   true,
                   false
                );

        String result = readAndWrite(JSON_F, p);
        assertEquals(aposToQuotes("{'ob':{'value':3}}"), result);
    }

================================================================================
HELPER METHODS
================================================================================
{'NameMatchFilter': 'public NameMatchFilter(String... names) {\n            _names = new HashSet<String>(Arrays.asList(names));\n        }', 'aposToQuotes': 'protected String aposToQuotes(String json) {\n        return json.replace("\'", "\\"");\n    }', 'createParser': 'protected JsonParser createParser(int mode, String doc) throws IOException {\n        return createParser(JSON_FACTORY, mode, doc);\n    }', 'readAndWrite': 'protected String readAndWrite(JsonFactory f, JsonParser p) throws IOException\n    {\n        StringWriter sw = new StringWriter(100);\n        JsonGenerator g = f.createGenerator(sw);\n        g.disable(JsonGenerator.Feature.AUTO_CLOSE_JSON_CONTENT);\n        try {\n            while (p.nextToken() != null) {\n                g.copyCurrentEvent(p);\n            }\n        } catch (IOException e) {\n            g.flush();\n            fail("Unexpected problem during `readAndWrite`. Output so far: \'"+sw+"\'; problem: "+e);\n        }\n        p.close();\n        g.close();\n        return sw.toString();\n    }'}

================================================================================
FAILURE LOG
================================================================================
junit.framework.ComparisonFailure: expected:<{"ob":{"value":3}[}]> but was:<{"ob":{"value":3}[]>
	at junit.framework.Assert.assertEquals(Assert.java:100)
	at junit.framework.Assert.assertEquals(Assert.java:107)
	at junit.framework.TestCase.assertEquals(TestCase.java:269)
	at com.fasterxml.jackson.core.filter.TokenVerifyingParserFiltering330Test.testBasicSingleMatchFilteringWithPath(TokenVerifyingParserFiltering330Test.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:255)
	at junit.framework.TestSuite.run(TestSuite.java:250)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.run(JUnitTestRunner.java:520)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTask.executeInVM(JUnitTask.java:1484)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTask.execute(JUnitTask.java:872)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTask.executeOrQueue(JUnitTask.java:1972)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTask.execute1(JUnitTask.java:824)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTask.execute(JUnitTask.java:2277)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:392)
	at org.apache.tools.ant.Target.performTasks(Target.java:413)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1368)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
	at org.apache.tools.ant.Main.runBuild(Main.java:811)
	at org.apache.tools.ant.Main.startAnt(Main.java:217)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)

================================================================================
PRODUCTION CODE
================================================================================
{'FilteringParserDelegate': {'<init>': 'public FilteringParserDelegate(JsonParser p, TokenFilter f,\n            boolean includePath, boolean allowMultipleMatches)\n    {\n        super(p);\n        rootFilter = f;\n\n        _itemFilter = f;\n        _headContext = TokenFilterContext.createRootContext(f);\n        _includePath = includePath;\n        _allowMultipleMatches = allowMultipleMatches;\n    }'}, 'JsonFactory': {'<init>': 'public JsonFactory() { this(null); }'}, 'JsonGenerator': {'<init>': 'protected JsonGenerator() { }'}, 'JsonParser': {'<init>': 'protected JsonParser() { }'}}
================================================================================
Index : 1125
Test ID : Cli-15-1
Flaky : False
Category : Non-Flaky
================================================================================

Artifact Summary
--------------------------------------------------------------------------------
Test Length         : 447
Helper Methods      : 1
Failure Log Length  : 2704
Production Classes  : 4

================================================================================
TEST CODE
================================================================================
public void testSingleOptionSingleArgument() throws Exception {
        Parser parser = createDefaultValueParser(new String[]{"100", "1000"});
        String enteredValue1 = "1";
        String[] args = new String[]{"-b", enteredValue1};
        CommandLine cl = parser.parse(args);
        CommandLine cmd = cl;
        assertNotNull(cmd);
        List b = cmd.getValues("-b");
        assertEquals("[" + enteredValue1 + ", 1000]", b + "");
    }

================================================================================
HELPER METHODS
================================================================================
{'createDefaultValueParser': 'private Parser createDefaultValueParser(String[] defaults) {\n        final DefaultOptionBuilder obuilder = new DefaultOptionBuilder();\n        final ArgumentBuilder abuilder = new ArgumentBuilder();\n        final GroupBuilder gbuilder = new GroupBuilder();\n\n        DefaultOption bOption = obuilder.withShortName("b")\n                .withLongName("b")\n                .withArgument(abuilder.withName("b")\n                        .withMinimum(0)\n                        .withMaximum(defaults.length)\n                        .withDefaults(Arrays.asList(defaults))\n                        .create())\n                .create();\n\n        Group options = gbuilder\n                .withName("options")\n                .withOption(bOption)\n                .create();\n\n        Parser parser = new Parser();\n        parser.setHelpTrigger("--help");\n        parser.setGroup(options);\n        return parser;\n    }'}

================================================================================
FAILURE LOG
================================================================================
junit.framework.ComparisonFailure: expected:<[1[, 1000]]> but was:<[1[]]>
	at junit.framework.Assert.assertEquals(Assert.java:100)
	at junit.framework.Assert.assertEquals(Assert.java:107)
	at junit.framework.TestCase.assertEquals(TestCase.java:269)
	at org.apache.commons.cli2.bug.BugCLI158Test.testSingleOptionSingleArgument(BugCLI158Test.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:255)
	at junit.framework.TestSuite.run(TestSuite.java:250)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.run(JUnitTestRunner.java:520)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTask.executeInVM(JUnitTask.java:1484)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTask.execute(JUnitTask.java:872)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTask.executeOrQueue(JUnitTask.java:1972)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTask.execute1(JUnitTask.java:824)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTask.execute(JUnitTask.java:2277)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:392)
	at org.apache.tools.ant.Target.performTasks(Target.java:413)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1368)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
	at org.apache.tools.ant.Main.runBuild(Main.java:811)
	at org.apache.tools.ant.Main.startAnt(Main.java:217)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)

================================================================================
PRODUCTION CODE
================================================================================
{'ArgumentBuilder': {'<init>': 'public ArgumentBuilder() {\n        reset();\n    }'}, 'DefaultOption': {'<init>': 'public DefaultOption(final String shortPrefix,\n                         final String longPrefix,\n                         final boolean burstEnabled,\n                         final String preferredName,\n                         final String description,\n                         final Set aliases,\n                         final Set burstAliases,\n                         final boolean required,\n                         final Argument argument,\n                         final Group children,\n                         final int id) {\n        super(argument, children, description, id, required);\n\n        this.shortPrefix = shortPrefix;\n        this.burstEnabled = burstEnabled;\n\n        this.burstLength = shortPrefix.length() + 1;\n\n        this.preferredName = preferredName;\n        this.aliases =\n            (aliases == null) ? Collections.EMPTY_SET\n                              : Collections.unmodifiableSet(new HashSet(aliases));\n\n        this.burstAliases =\n            (burstAliases == null) ? Collections.EMPTY_SET\n                                   : Collections.unmodifiableSet(new HashSet(burstAliases));\n\n        final Set newTriggers = new HashSet();\n        newTriggers.add(preferredName);\n        newTriggers.addAll(this.aliases);\n        newTriggers.addAll(this.burstAliases);\n        this.triggers = Collections.unmodifiableSet(newTriggers);\n\n        final Set newPrefixes = new HashSet(super.getPrefixes());\n        newPrefixes.add(shortPrefix);\n        newPrefixes.add(longPrefix);\n        this.prefixes = Collections.unmodifiableSet(newPrefixes);\n\n        checkPrefixes(newPrefixes);\n    }'}, 'DefaultOptionBuilder': {'<init>': 'public DefaultOptionBuilder() {\n        this(DefaultOption.DEFAULT_SHORT_PREFIX, DefaultOption.DEFAULT_LONG_PREFIX,\n             DefaultOption.DEFAULT_BURST_ENABLED);\n    }'}, 'GroupBuilder': {'<init>': 'public GroupBuilder() {\n        reset();\n    }'}}
================================================================================
Index : 1361
Test ID : Closure-64
Flaky : False
Category : Non-Flaky
================================================================================

Artifact Summary
--------------------------------------------------------------------------------
Test Length         : 414
Helper Methods      : 1
Failure Log Length  : 2881
Production Classes  : 4

================================================================================
TEST CODE
================================================================================
public void testES5StrictUseStrictMultipleInputs() {
    args.add("--language_in=ECMASCRIPT5_STRICT");
    Compiler compiler = compile(new String[] {"var x = f.function",
        "var y = f.function", "var z = f.function"});
    String outputSource = compiler.toSource();
    assertEquals("'use strict'", outputSource.substring(0, 12));
    assertEquals(outputSource.substring(13).indexOf("'use strict'"), -1);
  }

================================================================================
HELPER METHODS
================================================================================
{'compile': 'private Compiler compile(String[] original) {\n    CommandLineRunner runner = createCommandLineRunner(original);\n    assertTrue(runner.shouldRunCompiler());\n    Supplier<List<JSSourceFile>> inputsSupplier = null;\n    Supplier<List<JSModule>> modulesSupplier = null;\n\n    if (useModules == ModulePattern.NONE) {\n      List<JSSourceFile> inputs = Lists.newArrayList();\n      for (int i = 0; i < original.length; i++) {\n        inputs.add(JSSourceFile.fromCode("input" + i, original[i]));\n      }\n      inputsSupplier = Suppliers.ofInstance(inputs);\n    } else if (useModules == ModulePattern.STAR) {\n      modulesSupplier = Suppliers.<List<JSModule>>ofInstance(\n          Lists.<JSModule>newArrayList(\n              CompilerTestCase.createModuleStar(original)));\n    } else if (useModules == ModulePattern.CHAIN) {\n      modulesSupplier = Suppliers.<List<JSModule>>ofInstance(\n          Lists.<JSModule>newArrayList(\n              CompilerTestCase.createModuleChain(original)));\n    } else {\n      throw new IllegalArgumentException("Unknown module type: " + useModules);\n    }\n\n    runner.enableTestMode(\n        Suppliers.<List<JSSourceFile>>ofInstance(externs),\n        inputsSupplier,\n        modulesSupplier,\n        new Function<Integer, Boolean>() {\n          @Override\n          public Boolean apply(Integer code) {\n            return exitCodes.add(code);\n          }\n        });\n    runner.run();\n    lastCompiler = runner.getCompiler();\n    lastCommandLineRunner = runner;\n    return lastCompiler;\n  }'}

================================================================================
FAILURE LOG
================================================================================
junit.framework.AssertionFailedError: expected:<17> but was:<-1>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at junit.framework.Assert.assertEquals(Assert.java:241)
	at junit.framework.TestCase.assertEquals(TestCase.java:409)
	at com.google.javascript.jscomp.CommandLineRunnerTest.testES5StrictUseStrictMultipleInputs(CommandLineRunnerTest.java:803)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:255)
	at junit.framework.TestSuite.run(TestSuite.java:250)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.run(JUnitTestRunner.java:520)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTask.executeInVM(JUnitTask.java:1484)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTask.execute(JUnitTask.java:872)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTask.executeOrQueue(JUnitTask.java:1972)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTask.execute1(JUnitTask.java:824)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTask.execute(JUnitTask.java:2277)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:392)
	at org.apache.tools.ant.Target.performTasks(Target.java:413)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1368)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
	at org.apache.tools.ant.Main.runBuild(Main.java:811)
	at org.apache.tools.ant.Main.startAnt(Main.java:217)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)

================================================================================
PRODUCTION CODE
================================================================================

## Final Example Selection

The highest ranked candidates were manually inspected to identify representative demonstrations for few-shot prompting.

The final examples were selected based on the following considerations:

- close to the median artifact sizes of the dataset,
- complete contextual information (test code, helper methods, failure log, and production code),
- concise and readable source code,
- informative failure logs,
- manageable production code size,
- deterministic behaviour that clearly distinguishes flaky and non-flaky tests,
- suitability as teaching examples for Large Language Models.

Following this inspection, one flaky example and one non-flaky example were selected and fixed for all subsequent few-shot experiments.

Using the same demonstrations across all prompt configurations ensures that any performance differences observed during evaluation are attributable to the prompting strategy and contextual information rather than differences in the demonstration examples themselves.

In [41]:
FLAKY_EXAMPLE_INDEX = 758
NON_FLAKY_EXAMPLE_INDEX = 1951

selected_examples = working_df.loc[
    [FLAKY_EXAMPLE_INDEX, NON_FLAKY_EXAMPLE_INDEX]
]

selected_examples[
    [
        "test_id",
        "isFlaky",
        "issue_category"
    ]
]

,test_id,isFlaky,issue_category
758,OpenRefinemaina68ba3btestSelectedEmptyChoice,True,Implementation Dependent
1951,JacksonCore-21-2,False,Non-Flaky

## Create Evaluation Dataset

The selected demonstration examples are removed from the evaluation dataset to eliminate data leakage.

The resulting evaluation dataset is subsequently used throughout all LLM experiments, while the selected examples are used exclusively as fixed demonstrations for few-shot prompting.

In [42]:
evaluation_df = working_df.drop(
    index=[
        FLAKY_EXAMPLE_INDEX,
        NON_FLAKY_EXAMPLE_INDEX
    ]
)

print(f"Original Dataset   : {len(working_df)}")
print(f"Evaluation Dataset : {len(evaluation_df)}")

Original Dataset   : 2745
Evaluation Dataset : 2743

In [43]:
OUTPUT_PATH = (
    PROJECT_ROOT
    / "datasets"
    / "context_augmented_dataset_evaluation.jsonl"
)

evaluation_df.to_json(
    OUTPUT_PATH,
    orient="records",
    lines=True
)

print(f"Saved evaluation dataset to:\n{OUTPUT_PATH}")

Saved evaluation dataset to:
d:\university works\Final-Year_Firts_sem\FYP\INFO\REPO\CA-Classification-Framework\datasets\context_augmented_dataset_evaluation.jsonl

# Second Selection Round

## Motivation

The initially selected representative examples were validated using an expert language model in the subsequent notebook.

During validation, the initial non-flaky example was successfully verified. However, the initial flaky example was incorrectly classified by the expert model when only the test code was provided.

Since few-shot demonstrations must accurately represent the dataset labels, the initial flaky example was rejected.

A second representative flaky example is therefore selected using the same ranking procedure while keeping the validated non-flaky example unchanged.

In [44]:
SECOND_FLAKY_INDEX = 789

inspect_candidate(SECOND_FLAKY_INDEX)

================================================================================
Index : 789
Test ID : jolokiasupportspring275165bsystemProperties
Flaky : True
Category : Implementation Dependent
================================================================================

Artifact Summary
--------------------------------------------------------------------------------
Test Length         : 535
Helper Methods      : 1
Failure Log Length  : 3088
Production Classes  : 4

================================================================================
TEST CODE
================================================================================
@Test
    public void systemProperties() throws Exception {
        checkSystemPropertyMode("fallback","/jol/","/j4p/","/j4p/");
        checkSystemPropertyMode("fallback","/jol/",null,"/jol/");
        checkSystemPropertyMode("fallback",null,null,"/jolokia/");

        checkSystemPropertyMode("override","/jol/","/j4p/","/jol/");
        checkSystemPropertyMode("override","/jol/",null,"/jol/");
        checkSystemPropertyMode("override",null,null,"/jolokia/");

        checkSystemPropertyMode(null,"/jol/",null,"/jolokia/");
    }

================================================================================
HELPER METHODS
================================================================================
{'checkSystemPropertyMode': 'private void checkSystemPropertyMode(String mode,String propContext,String configContext,String expectContext) throws Exception {\n        if (propContext != null) {\n            System.setProperty("jolokia.agentContext", propContext);\n        }\n        SpringJolokiaAgent server = new SpringJolokiaAgent();\n        server.setConfig(getConfig(true,100,"agentContext", configContext));\n        server.setSystemPropertiesMode(mode);\n        server.afterPropertiesSet();\n        assertEquals(server.getServerConfig().getContextPath(), expectContext);\n        System.getProperties().remove("jolokia.agentContext");\n        checkServerAndStop(server);\n\n        Thread.sleep(500);\n    }'}

================================================================================
FAILURE LOG
================================================================================
java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:111)
	at org.testng.Assert.failNotEquals(Assert.java:1578)
	at org.testng.Assert.assertTrue(Assert.java:57)
	at org.testng.Assert.assertTrue(Assert.java:67)
	at org.jolokia.support.spring.BaseServerTest.checkServerAndStop(BaseServerTest.java:38)
	at org.jolokia.support.spring.SpringJolokiaServerTest.checkSystemPropertyMode(SpringJolokiaServerTest.java:69)
	at org.jolokia.support.spring.SpringJolokiaServerTest.systemProperties(SpringJolokiaServerTest.java:48)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.testng.TestRunner.privateRun(TestRunner.java:739)
	at org.testng.TestRunner.run(TestRunner.java:614)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
	at org.testng.SuiteRunner.run(SuiteRunner.java:312)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
	at org.testng.TestNG.runSuites(TestNG.java:1112)
	at org.testng.TestNG.run(TestNG.java:1079)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:155)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:102)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:91)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:137)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)

================================================================================
PRODUCTION CODE
================================================================================
{'org.jolokia.jvmagent.JolokiaServerConfig': {'getContextPath': 'public String getContextPath() {\n        return context;\n    }'}, 'org.jolokia.support.spring.SpringJolokiaAgent': {'afterPropertiesSet': 'public void afterPropertiesSet() throws IOException {\n        Map<String, String> config = new HashMap<>();\n        if (systemPropertyMode == SystemPropertyMode.FALLBACK) {\n            config.putAll(lookupSystemProperties());\n        }\n        if (configHolder.getConfig() != null) {\n            config.putAll(configHolder.getConfig());\n        }\n\n        if (lookupConfig && context != null) {\n            config.putAll(lookupConfigurationFromContext());\n        }\n\n        if (systemPropertyMode == SystemPropertyMode.OVERRIDE) {\n            config.putAll(lookupSystemProperties());\n        }\n\n        boolean autoStart = Boolean.parseBoolean(config.remove("autoStart"));\n\n        LogHandler logHandler = logHandlerHolder != null ? logHandlerHolder.getLogHandler() : null;\n        init(new JolokiaServerConfig(config), logHandler);\n\n        if (exposeApplicationContext && context != null) {\n            addService(new SpringRequestHandler(context, 100));\n        }\n\n        if (lookupServices) {\n            lookupServices();\n        }\n\n        if (autoStart) {\n            start();\n        }\n    }', 'destroy': 'public void destroy() {\n        stop();\n    }', 'getServerConfig': '@SuppressWarnings("unused")\n    public JolokiaServerConfig getServerConfig() {\n        return config;\n    }', 'lookupSystemProperties': 'private Map<String, String> lookupSystemProperties() {\n        Map<String,String> ret = new HashMap<>();\n        Enumeration<?> propEnum = System.getProperties().propertyNames();\n        while (propEnum.hasMoreElements()) {\n            String prop = (String) propEnum.nextElement();\n            if (prop.startsWith("jolokia.")) {\n                String key = prop.substring("jolokia.".length());\n                ret.put(key,System.getProperty(prop));\n            }\n        }\n        return ret;\n    }', 'setConfig': 'public void setConfig(SpringJolokiaConfigHolder pConfig) {\n        configHolder = pConfig;\n    }', 'setSystemPropertiesMode': 'public void setSystemPropertiesMode(String pMode) {\n        systemPropertyMode = SystemPropertyMode.fromMode(pMode);\n        if (systemPropertyMode == null) {\n            systemPropertyMode = SystemPropertyMode.NEVER;\n        }\n    }'}, 'org.jolokia.support.spring.SpringJolokiaConfigHolder': {'getConfig': 'public Map<String, String> getConfig() {\n        return config;\n    }', 'setConfig': 'public void setConfig(Map<String, String> pConfig) {\n        config = pConfig;\n    }', 'setOrder': 'public void setOrder(int pOrder) {\n        order = pOrder;\n    }'}, 'org.jolokia.support.spring.SystemPropertyMode': {'fromMode': 'public static SystemPropertyMode fromMode(String pMode) {\n        if (pMode != null) {\n            for (SystemPropertyMode m : SystemPropertyMode.values()) {\n                if (m.mode.equals(pMode.toLowerCase())) {\n                    return m;\n                }\n            }\n        }\n        return null;\n    }'}}

In [45]:
selected_examples = working_df.loc[
    [
        FLAKY_EXAMPLE_INDEX,
        NON_FLAKY_EXAMPLE_INDEX
    ]
]

selected_examples[
    [
        "test_id",
        "isFlaky"
    ]
]

                                           test_id  isFlaky
758   OpenRefinemaina68ba3btestSelectedEmptyChoice     True
1951                              JacksonCore-21-2    False

## Create Updated Evaluation Dataset

To prevent information leakage during model evaluation, the final selected demonstration examples are removed from the evaluation dataset.

The resulting dataset will be used during the feasibility analysis and subsequent LLM evaluation.

In [46]:
evaluation_df = working_df.drop(
    index=[
        FLAKY_EXAMPLE_INDEX,
        NON_FLAKY_EXAMPLE_INDEX
    ]
)

print(f"Evaluation Records : {len(evaluation_df)}")

Evaluation Records : 2743

In [48]:
OUTPUT_PATH = (
    PROJECT_ROOT
    / "datasets"
    / "context_augmented_dataset_evaluation.jsonl"
)

evaluation_df.to_json(
    OUTPUT_PATH,
    orient="records",
    lines=True
)

print("✓ Final evaluation dataset saved.")
print(OUTPUT_PATH)

✓ Final evaluation dataset saved.
d:\university works\Final-Year_Firts_sem\FYP\INFO\REPO\CA-Classification-Framework\datasets\context_augmented_dataset_evaluation.jsonl

## Revision of Demonstration Selection Strategy

The first two representative flaky candidates were rejected during expert validation because the expert model could not reliably infer flaky behaviour from the test code alone.

Although these examples were representative in terms of dataset statistics, they did not provide sufficiently observable flaky characteristics for code-only prompting.

Therefore, the demonstration selection strategy was refined.

For the code-only prompt configuration, replacement candidates are selected based on the presence of explicit flaky indicators within the test code (e.g., concurrency or timing constructs), while maintaining the previously validated non-flaky demonstration.

## Select Code-Oriented Replacement Candidate

Following the refinement of the demonstration selection strategy, a new flaky example is selected specifically for the code-only prompt configuration.

Unlike the previous representative examples, the replacement candidate is chosen because the flaky behaviour is explicitly observable within the test code (e.g., concurrency or timing constructs). Such characteristics enable the expert model to infer the correct classification without requiring additional contextual artifacts.

The previously validated non-flaky demonstration remains unchanged.

In [52]:
FINAL_FLAKY_TEST_ID = "CURATOR-671"

FINAL_NON_FLAKY_TEST_ID = "JacksonCore-21-2"

In [50]:
replacement_example = working_df[
    working_df["test_id"] == REPLACEMENT_TEST_ID
].iloc[0]

display(
    replacement_example[
        [
            "test_id",
            "issue_category",
            "isFlaky"
        ]
    ]
)

test_id              CURATOR-671
issue_category    Time Dependent
isFlaky                     True
Name: 1082, dtype: object

In [53]:
final_examples = working_df[

    working_df["test_id"].isin(

        [
            FINAL_FLAKY_TEST_ID,
            FINAL_NON_FLAKY_TEST_ID
        ]

    )

]

display(

    final_examples[
        [
            "test_id",
            "issue_category",
            "isFlaky"
        ]
    ]

)

               test_id  issue_category  isFlaky
1082       CURATOR-671  Time Dependent     True
1951  JacksonCore-21-2       Non-Flaky    False

## Create Final Evaluation Dataset

The final selected demonstration examples are removed from the evaluation dataset to prevent data leakage during LLM evaluation.

This dataset will be used throughout the subsequent experiments.

In [54]:
final_dataset = working_df[

    ~working_df["test_id"].isin(

        [
            FINAL_FLAKY_TEST_ID,
            FINAL_NON_FLAKY_TEST_ID
        ]

    )

].copy()

print(len(final_dataset))

2743

In [63]:
OUTPUT_PATH = (
    PROJECT_ROOT
    / "datasets"
    / "context_augmented_dataset_preprocessed.jsonl"
)

final_dataset.to_json(

    OUTPUT_PATH,
    orient="records",
    lines=True

)

print("✓ Final evaluation dataset saved.")

✓ Final evaluation dataset saved.