# Context Window Feasibility Analysis

## Overview

Following dataset preprocessing and prompt construction, the next stage of the proposed framework is to determine whether the generated prompts can be accommodated within the context windows of the selected Large Language Models (LLMs).

The proposed framework evaluates six prompt configurations formed by combining three prompting strategies (Zero-shot, Zero-shot Chain-of-Thought, and Few-shot Chain-of-Thought) with two input representations (Code Only and Code + Context).

This notebook generates the actual prompts using the developed prompt builder and measures their token usage using the tokenizer of each selected LLM. The analysis determines whether the generated prompts can be directly used for evaluation or whether additional context reduction is required.

---

## Objectives

This notebook aims to:

- Validate the preprocessed dataset.
- Generate prompts for all planned experimental configurations.
- Measure prompt lengths using the tokenizer of each selected LLM.
- Compare prompt sizes against the context windows of the selected models.
- Determine whether additional context reduction is required before evaluation.

---

## Experimental Configurations

| Prompt Strategy | Code Only | Code + Context |
|-----------------|-----------|----------------|
| Zero-shot | ✓ | ✓ |
| Zero-shot CoT | ✓ | ✓ |
| Few-shot CoT | ✓ | ✓ |

This results in six experimental configurations that will be evaluated throughout the remainder of this study.

In [1]:
# ============================================================
# Step 1 - Import Libraries
# ============================================================

import sys
from pathlib import Path

import pandas as pd
import numpy as np

from IPython.display import display

In [2]:
# ============================================================
# Step 2 - Load Preprocessed Dataset
# ============================================================

PROJECT_ROOT = Path.cwd().parent.parent

DATASET_PATH = (
    PROJECT_ROOT
    / "datasets"
    / "evaluation_dataset.jsonl"
)

working_df = pd.read_json(
    DATASET_PATH,
    lines=True
)

print("=" * 80)
print("DATASET LOADED")
print("=" * 80)

print(f"Dataset Shape : {working_df.shape}")

================================================================================
DATASET LOADED
================================================================================
Dataset Shape : (2741, 15)

## Step 3 - Experimental Configurations

The feasibility analysis is performed using the same prompt configurations that will be used during the final LLM evaluation.

Three prompting strategies are considered:

- Zero-shot
- Zero-shot Chain-of-Thought (CoT)
- Few-shot Chain-of-Thought (CoT)

Each strategy is evaluated under two input representations:

- Code Only
- Code + Context

This results in six experimental configurations.

In [3]:
# ============================================================
# Step 3 - Experimental Configurations
# ============================================================

PROMPT_CONFIGS = [

    {
        "name": "Zero-shot + Code Only",
        "strategy": "zero_shot",
        "include_context": False
    },

    {
        "name": "Zero-shot + Code + Context",
        "strategy": "zero_shot",
        "include_context": True
    },

    {
        "name": "Zero-shot CoT + Code Only",
        "strategy": "zero_shot_cot",
        "include_context": False
    },

    {
        "name": "Zero-shot CoT + Code + Context",
        "strategy": "zero_shot_cot",
        "include_context": True
    },

    {
        "name": "Few-shot CoT + Code Only",
        "strategy": "few_shot_cot",
        "include_context": False
    },

    {
        "name": "Few-shot CoT + Code + Context",
        "strategy": "few_shot_cot",
        "include_context": True
    }

]

print("=" * 80)
print("EXPERIMENTAL CONFIGURATIONS")
print("=" * 80)

display(pd.DataFrame(PROMPT_CONFIGS))

================================================================================
EXPERIMENTAL CONFIGURATIONS
================================================================================

                             name       strategy  include_context
0           Zero-shot + Code Only      zero_shot            False
1      Zero-shot + Code + Context      zero_shot             True
2       Zero-shot CoT + Code Only  zero_shot_cot            False
3  Zero-shot CoT + Code + Context  zero_shot_cot             True
4        Few-shot CoT + Code Only   few_shot_cot            False
5   Few-shot CoT + Code + Context   few_shot_cot             True

## Step 4 - Load Prompt Builder

The prompts are generated using the prompt builder developed during the previous stage. Using the same prompt builder for both feasibility analysis and the final evaluation ensures methodological consistency throughout the study.

In [4]:
# ============================================================
# Step 4 - Load Prompt Builder
# ============================================================

if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))

from utils.prompt_builder import build_prompt

print("=" * 80)
print("PROMPT BUILDER")
print("=" * 80)

print("✓ Prompt Builder Loaded Successfully")

================================================================================
PROMPT BUILDER
================================================================================
✓ Prompt Builder Loaded Successfully

## Step 5 - Verify Prompt Generation

Before analyzing all test cases, a representative sample is used to verify that prompts are generated correctly for each experimental configuration.

This step confirms that:

- The correct prompting strategy is applied.
- Contextual artifacts are included only when required.
- The generated prompts match the format intended for the final evaluation.

In [5]:
# ============================================================
# Step 5 - Verify Prompt Generation
# ============================================================

sample = working_df.iloc[0].to_dict()

for config in PROMPT_CONFIGS:

    print("=" * 80)
    print(config["name"])
    print("=" * 80)

    prompt = build_prompt(

        sample=sample,

        strategy=config["strategy"],

        include_context=config["include_context"]

    )

    print(prompt[:10500])
    print("\n")

================================================================================
Zero-shot + Code Only
================================================================================
You are an expert software testing assistant specializing in flaky test identification and classification.

Base every decision solely on the provided artifacts.

Do not rely on external knowledge or assumptions.

If the available evidence is insufficient to confidently identify a flaky test, classify it as Non-Flaky.

Your task is to analyze the provided software testing artifacts.

Determine whether the test is Flaky or Non-Flaky.

If the test is Flaky, select exactly one issue category from the provided category list.

Justify the classification using only the provided evidence.

Identify the artifacts that support your conclusion.

## Flaky Test Categories

If the test is classified as Flaky, select exactly one issue category from the following list.

1. Implementation Dependent
   - The test outcome depends on implementation-specific behavior rather than the intended specification.

2. Order Dependent
   - The test outcome depends on the execution order of tests because of shared state or side effects.

3. Non-Idempotent
   - Repeated execution changes the outcome because the test or system under test modifies state that is not reset.

4. Time Dependent
   - The test outcome depends on timing, scheduling, delays, clocks, or asynchronous execution.

If the test is classified as Non-Flaky, return:

Non-Flaky

Analyze the following test artifacts.

Produce the final classification based only on the provided artifacts.

## Input

### 1. Test Code

@Test
  public void testFindItemsByNamespace() throws Exception {
    final int page = 0;
    final int size = 50;
    final ArgumentCaptor<HttpGet> request = ArgumentCaptor.forClass(HttpGet.class);

    itemOpenApiService.findItemsByNamespace(someAppId, someEnv, someCluster, someNamespace, page, size);

    verify(httpClient, times(1)).execute(request.capture());

    HttpGet get = request.getValue();

    assertEquals(String.format("%s/envs/%s/apps/%s/clusters/%s/namespaces/%s/items?size=%s&page=%s",
            someBaseUrl, someEnv, someAppId, someCluster, someNamespace, size, page), get.getURI().toString());
  }

Return only the following JSON object without any additional explanation or markdown.

{
    "classification": "<Flaky | Non-Flaky>",
    "category": "<One category from the provided category list or Non-Flaky>",
    "reasoning": "...",
    "evidence": [
        < List of artifacts helps to conclusion. Example: "Test Code", "Helper Methods", "Failure Log", "Production Code" >
    ]
}


================================================================================
Zero-shot + Code + Context
================================================================================
You are an expert software testing assistant specializing in flaky test identification and classification.

Base every decision solely on the provided artifacts.

Do not rely on external knowledge or assumptions.

If the available evidence is insufficient to confidently identify a flaky test, classify it as Non-Flaky.

Your task is to analyze the provided software testing artifacts.

Determine whether the test is Flaky or Non-Flaky.

If the test is Flaky, select exactly one issue category from the provided category list.

Justify the classification using only the provided evidence.

Identify the artifacts that support your conclusion.

## Flaky Test Categories

If the test is classified as Flaky, select exactly one issue category from the following list.

1. Implementation Dependent
   - The test outcome depends on implementation-specific behavior rather than the intended specification.

2. Order Dependent
   - The test outcome depends on the execution order of tests because of shared state or side effects.

3. Non-Idempotent
   - Repeated execution changes the outcome because the test or system under test modifies state that is not reset.

4. Time Dependent
   - The test outcome depends on timing, scheduling, delays, clocks, or asynchronous execution.

If the test is classified as Non-Flaky, return:

Non-Flaky

Analyze the following test artifacts.

Produce the final classification based only on the provided artifacts.

## Input

### 1. Test Code

@Test
  public void testFindItemsByNamespace() throws Exception {
    final int page = 0;
    final int size = 50;
    final ArgumentCaptor<HttpGet> request = ArgumentCaptor.forClass(HttpGet.class);

    itemOpenApiService.findItemsByNamespace(someAppId, someEnv, someCluster, someNamespace, page, size);

    verify(httpClient, times(1)).execute(request.capture());

    HttpGet get = request.getValue();

    assertEquals(String.format("%s/envs/%s/apps/%s/clusters/%s/namespaces/%s/items?size=%s&page=%s",
            someBaseUrl, someEnv, someAppId, someCluster, someNamespace, size, page), get.getURI().toString());
  }

### 3. Failure Log

org.junit.ComparisonFailure: expected:<...someNamespace/items?[size=50&page=]0> but was:<...someNamespace/items?[page=0&size=5]0>
	at org.junit.Assert.assertEquals(Assert.java:117)
	at org.junit.Assert.assertEquals(Assert.java:146)
	at com.ctrip.framework.apollo.openapi.client.service.ItemOpenApiServiceTest.testFindItemsByNamespace(ItemOpenApiServiceTest.java:321)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.mockito.internal.runners.DefaultInternalRunner$1$1.evaluate(DefaultInternalRunner.java:55)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.mockito.internal.runners.DefaultInternalRunner$1.run(DefaultInternalRunner.java:100)
	at org.mockito.internal.runners.DefaultInternalRunner.run(DefaultInternalRunner.java:107)
	at org.mockito.internal.runners.StrictRunner.run(StrictRunner.java:41)
	at org.mockito.junit.MockitoJUnitRunner.run(MockitoJUnitRunner.java:163)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:43)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:82)
	at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:73)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:150)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)

### 4. Production Code

Class: com.ctrip.framework.apollo.openapi.client.service.AbstractOpenApiService

Method: checkHttpResponseStatus

private void checkHttpResponseStatus(HttpResponse response) {
    if (response.getStatusLine().getStatusCode() == 200) {
      return;
    }

    StatusLine status = response.getStatusLine();
    String message = "";
    try {
      message = EntityUtils.toString(response.getEntity());
    } catch (IOException e) {

    }

    throw new ApolloOpenApiException(status.getStatusCode(), status.getReasonPhrase(), message);
  }

----------------------------------------

Method: checkNotEmpty

protected void checkNotEmpty(String value, String name) {
    Preconditions.checkArgument(!Strings.isNullOrEmpty(value), name + " should not be null or empty");
  }

----------------------------------------

Method: checkPage

protected void checkPage(int page) {
    Preconditions.checkArgument(page >= 0, "page should be positive or 0");
  }

----------------------------------------

Method: checkSize

protected void checkSize(int size) {
    Preconditions.checkArgument(size > 0, "size should be positive number");
  }

----------------------------------------

Method: get

protected CloseableHttpResponse get(OpenApiPathBuilder path) throws IOException {
    HttpGet get = new HttpGet(path.buildPath(baseUrl));

    return execute(get);
  }

----------------------------------------

Class: com.ctrip.framework.apollo.openapi.client.service.ItemOpenApiService

Method: findItemsByNamespace

@Override
  public OpenPageDTO<OpenItemDTO> findItemsByNamespace(String appId, String env, String clusterName,
                                                       String namespaceName, int page, int size) {
    if (Strings.isNullOrEmpty(clusterName)) {
      clusterName = ConfigConsts.CLUSTER_NAME_DEFAULT;
    }
    if (Strings.isNullOrEmpty(namespaceName)) {
      namespaceName = ConfigConsts.NAMESPACE_APPLICATION;
    }

    checkNotEmpty(appId, "App id");
    checkNotEmpty(env, "Env");
    checkPage(page);
    checkSize(size);

    OpenApiPathBuilder pathBuilder = OpenApiPathBuilder.newBuilder()
            .envsPathVal(env)
            .appsPathVal(appId)
            .clustersPathVal(clusterName)
            .namespacesPathVal(namespaceName)
            .itemsPathVal("")
            .addParam("page", page)
            .addParam("size", size);

    try (CloseableHttpResponse response = get(pathBuilder)) {
      return gson.fromJson(EntityUtils.toString(response.getEntity()), OPEN_PAGE_DTO_OPEN_ITEM_DTO_TYPE_REFERENCE);
    } catch (Throwable ex) {
      throw new RuntimeException(String.format("Paging get items: appId: %s, cluster: %s, namespace: %s in env: %s failed",
              appId, clusterName, namespaceName, env), ex);
    }
  }

----------------------------------------

Class: com.ctrip.framework.apollo.openapi.client.url.OpenApiPathBuilder

Method: addParam

public OpenApiPathBuilder addParam(String key, Object value) {
    if (Strings.isNullOrEmpty(key)) {
      throw new IllegalArgumentException("Param key should not be null or empty");
    }
    this.params.put(key, escapeParam(String.valueOf(value)));
    return this;
  }

----------------------------------------

Method: appsPathVal

public OpenApiPathBuilder appsPathVal(String apps) {
    pathVariable.put(APPS_PATH, escapePath(apps));
    return this;
  }

----------------------------------------

Method: buildPath

public String buildPath(String baseUrl) {
    if (Strings.isNullOrEmpty(baseUrl)) {
      throw new IllegalArgumentException("Base url should not be null or empty");
    }
    List<String> parts = new


================================================================================
Zero-shot CoT + Code Only
================================================================================
You are an expert software testing assistant specializing in flaky test identification and classification.

Base every decision solely on the provided artifacts.

Do not rely on external knowledge or assumptions.

If the available evidence is insufficient to confidently identify a flaky test, classify it as Non-Flaky.

Your task is to analyze the provided software testing artifacts.

Determine whether the test is Flaky or Non-Flaky.

If the test is Flaky, select exactly one issue category from the provided category list.

Justify the classification using only the provided evidence.

Identify the artifacts that support your conclusion.

## Flaky Test Categories

If the test is classified as Flaky, select exactly one issue category from the following list.

1. Implementation Dependent
   - The test outcome depends on implementation-specific behavior rather than the intended specification.

2. Order Dependent
   - The test outcome depends on the execution order of tests because of shared state or side effects.

3. Non-Idempotent
   - Repeated execution changes the outcome because the test or system under test modifies state that is not reset.

4. Time Dependent
   - The test outcome depends on timing, scheduling, delays, clocks, or asynchronous execution.

If the test is classified as Non-Flaky, return:

Non-Flaky

Study the worked examples below.

Each example illustrates how to:
- identify the relevant evidence,
- evaluate possible sources of flakiness,
- eliminate unsupported explanations,
- determine the final classification.

Apply the same reasoning process demonstrated in the examples to the new test case.

## Input

### 1. Test Code

@Test
  public void testFindItemsByNamespace() throws Exception {
    final int page = 0;
    final int size = 50;
    final ArgumentCaptor<HttpGet> request = ArgumentCaptor.forClass(HttpGet.class);

    itemOpenApiService.findItemsByNamespace(someAppId, someEnv, someCluster, someNamespace, page, size);

    verify(httpClient, times(1)).execute(request.capture());

    HttpGet get = request.getValue();

    assertEquals(String.format("%s/envs/%s/apps/%s/clusters/%s/namespaces/%s/items?size=%s&page=%s",
            someBaseUrl, someEnv, someAppId, someCluster, someNamespace, size, page), get.getURI().toString());
  }

Return only the following JSON object without any additional explanation or markdown.

{
    "classification": "<Flaky | Non-Flaky>",
    "category": "<One category from the provided category list or Non-Flaky>",
    "reasoning": "...",
    "evidence": [
        < List of artifacts helps to conclusion. Example: "Test Code", "Helper Methods", "Failure Log", "Production Code" >
    ]
}


================================================================================
Zero-shot CoT + Code + Context
================================================================================
You are an expert software testing assistant specializing in flaky test identification and classification.

Base every decision solely on the provided artifacts.

Do not rely on external knowledge or assumptions.

If the available evidence is insufficient to confidently identify a flaky test, classify it as Non-Flaky.

Your task is to analyze the provided software testing artifacts.

Determine whether the test is Flaky or Non-Flaky.

If the test is Flaky, select exactly one issue category from the provided category list.

Justify the classification using only the provided evidence.

Identify the artifacts that support your conclusion.

## Flaky Test Categories

If the test is classified as Flaky, select exactly one issue category from the following list.

1. Implementation Dependent
   - The test outcome depends on implementation-specific behavior rather than the intended specification.

2. Order Dependent
   - The test outcome depends on the execution order of tests because of shared state or side effects.

3. Non-Idempotent
   - Repeated execution changes the outcome because the test or system under test modifies state that is not reset.

4. Time Dependent
   - The test outcome depends on timing, scheduling, delays, clocks, or asynchronous execution.

If the test is classified as Non-Flaky, return:

Non-Flaky

Study the worked examples below.

Each example illustrates how to:
- identify the relevant evidence,
- evaluate possible sources of flakiness,
- eliminate unsupported explanations,
- determine the final classification.

Apply the same reasoning process demonstrated in the examples to the new test case.

## Input

### 1. Test Code

@Test
  public void testFindItemsByNamespace() throws Exception {
    final int page = 0;
    final int size = 50;
    final ArgumentCaptor<HttpGet> request = ArgumentCaptor.forClass(HttpGet.class);

    itemOpenApiService.findItemsByNamespace(someAppId, someEnv, someCluster, someNamespace, page, size);

    verify(httpClient, times(1)).execute(request.capture());

    HttpGet get = request.getValue();

    assertEquals(String.format("%s/envs/%s/apps/%s/clusters/%s/namespaces/%s/items?size=%s&page=%s",
            someBaseUrl, someEnv, someAppId, someCluster, someNamespace, size, page), get.getURI().toString());
  }

### 3. Failure Log

org.junit.ComparisonFailure: expected:<...someNamespace/items?[size=50&page=]0> but was:<...someNamespace/items?[page=0&size=5]0>
	at org.junit.Assert.assertEquals(Assert.java:117)
	at org.junit.Assert.assertEquals(Assert.java:146)
	at com.ctrip.framework.apollo.openapi.client.service.ItemOpenApiServiceTest.testFindItemsByNamespace(ItemOpenApiServiceTest.java:321)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.mockito.internal.runners.DefaultInternalRunner$1$1.evaluate(DefaultInternalRunner.java:55)

## Step 6 - Load Prompt Tokenizer

To estimate the size of each generated prompt, a single representative tokenizer (Qwen3-Coder) is used to calculate the number of tokens in each prompt.

The estimated token counts are then compared against the published context window sizes of the selected LLMs (Qwen3-Coder, DeepSeek-R1, and Llama-4 Maverick) to verify that all prompt configurations fit within the supported context limits.

## Step 7 - Load the Prompt Tokenizer

The Qwen3-Coder tokenizer is loaded to estimate the number of tokens in each generated prompt. The tokenizer is used only for prompt size estimation and not for model inference.

In [6]:
# ============================================================
# Step 7 - Load Prompt Tokenizer
# ============================================================

from transformers import AutoTokenizer

TOKENIZER_NAME = "Qwen/Qwen3-Coder-30B-A3B-Instruct"

print(f"Loading tokenizer: {TOKENIZER_NAME}")

tokenizer = AutoTokenizer.from_pretrained(
    TOKENIZER_NAME,
    trust_remote_code=True
)

print("✓ Tokenizer loaded successfully!")

C:\Users\ASUS\AppData\Roaming\Python\Python314\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
[transformers] PyTorch was not found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.

Loading tokenizer: Qwen/Qwen3-Coder-30B-A3B-Instruct

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

✓ Tokenizer loaded successfully!

## Step 8 - Define Context Window Sizes

The published context window sizes of the selected LLMs are defined. These values are later used to determine whether each generated prompt fits within the supported input length of each model.

In [7]:
# ============================================================
# Step 8 - Selected LLM Context Windows
# ============================================================

MODELS = [
    {
        "name": "Qwen3-Coder",
        "context_window": 32768
    },
    {
        "name": "DeepSeek-R1",
        "context_window": 32768
    },
    {
        "name": "Llama-4-Maverick",
        "context_window": 131072
    }
]

MODELS

[{'name': 'Qwen3-Coder', 'context_window': 32768},
 {'name': 'DeepSeek-R1', 'context_window': 32768},
 {'name': 'Llama-4-Maverick', 'context_window': 131072}]

## Step 9 - Generate Prompt Token Statistics

Each dataset instance is processed using every prompt configuration. The generated prompts are tokenized using the Qwen3-Coder tokenizer to estimate their input size.

For each generated prompt, the following information is recorded:

- Prompt configuration
- Character count
- Token count
- Context window utilization
- Whether the prompt fits within each selected LLM's context window

The analysis is performed across the entire dataset to determine the maximum prompt size and verify compatibility with the selected LLMs.

In [8]:
# ============================================================
# Step 9 - Generate Prompt Token Statistics
# ============================================================

import pandas as pd
from tqdm.auto import tqdm

results = []

total_prompts = len(working_df) * len(PROMPT_CONFIGS)

print(f"Dataset samples : {len(working_df):,}")
print(f"Prompt strategies : {len(PROMPT_CONFIGS)}")
print(f"Total prompts : {total_prompts:,}")
print()

for sample_index, (_, row) in enumerate(tqdm(working_df.iterrows(),
                                              total=len(working_df),
                                              desc="Generating Prompts")):

    for config in PROMPT_CONFIGS:

        # Build prompt
        prompt = build_prompt(
            sample=row,
            strategy=config["strategy"],
            include_context=config["include_context"]
        )

        # Prompt statistics
        char_count = len(prompt)
        token_count = len(tokenizer.encode(prompt))

        # Compare against every selected LLM
        for model in MODELS:

            utilization = (token_count / model["context_window"]) * 100

            results.append({
                "sample_index": sample_index,
                "prompt_configuration": config["name"],
                "strategy": config["strategy"],
                "include_context": config["include_context"],

                "character_count": char_count,
                "token_count": token_count,

                "model": model["name"],
                "context_window": model["context_window"],

                "utilization_percent": round(utilization, 2),
                "fits_context": token_count <= model["context_window"]
            })

results_df = pd.DataFrame(results)

print()
print("Analysis completed successfully.")
print(f"Generated records : {len(results_df):,}")

Dataset samples : 2,741
Prompt strategies : 6
Total prompts : 16,446

Generating Prompts: 100%|██████████| 2741/2741 [02:50<00:00, 16.05it/s]

Analysis completed successfully.
Generated records : 49,338

## Step 10 - Summarize Prompt Statistics

Descriptive statistics are calculated for each prompt configuration to analyze the distribution of prompt sizes across the dataset.

The statistics include:

- Minimum token count
- Average token count
- Median token count
- 95th percentile
- 99th percentile
- Maximum token count

These values are used to identify the largest generated prompts and verify that they remain within the supported context windows of the selected LLMs.

In [9]:
# ============================================================
# Step 10 - Prompt Token Statistics
# ============================================================

summary_df = (
    results_df
    .drop_duplicates(
        subset=["sample_index", "prompt_configuration"]
    )
    .groupby("prompt_configuration")["token_count"]
    .agg(
        Minimum="min",
        Mean="mean",
        Median="median",
        Percentile95=lambda x: x.quantile(0.95),
        Percentile99=lambda x: x.quantile(0.99),
        Maximum="max"
    )
    .round(2)
    .reset_index()
)

summary_df

,prompt_configuration,Minimum,Mean,Median,Percentile95,Percentile99,Maximum
0,Few-shot CoT + Code + Context,3561,9364.43,5259.0,24281.0,62882.8,237416
1,Few-shot CoT + Code Only,1192,1349.83,1288.0,1648.0,2182.4,9527
2,Zero-shot + Code + Context,503,6306.43,2201.0,21223.0,59824.8,234358
3,Zero-shot + Code Only,399,556.83,495.0,855.0,1389.4,8734
4,Zero-shot CoT + Code + Context,537,6340.43,2235.0,21257.0,59858.8,234392
5,Zero-shot CoT + Code Only,433,590.83,529.0,889.0,1423.4,8768

## Step 11 - Count Prompts Exceeding Context Windows

The number of generated prompts that exceed the maximum context window of each selected LLM is calculated. This analysis identifies whether any prompt configurations require preprocessing or context reduction before being submitted to the models.

In [10]:
# ============================================================
# Step 11 - Count Prompts Exceeding Context Windows
# ============================================================

context_window_summary = (
    results_df
    .groupby(["model", "prompt_configuration"])
    .agg(
        Total_Prompts=("fits_context", "count"),
        Exceeds_Context=("fits_context", lambda x: (~x).sum()),
        Fits_Context=("fits_context", "sum")
    )
    .reset_index()
)

context_window_summary["Exceeds (%)"] = (
    context_window_summary["Exceeds_Context"]
    / context_window_summary["Total_Prompts"] * 100
).round(2)

context_window_summary["Fits (%)"] = (
    context_window_summary["Fits_Context"]
    / context_window_summary["Total_Prompts"] * 100
).round(2)

context_window_summary

,model,prompt_configuration,Total_Prompts,Exceeds_Context,Fits_Context,Exceeds (%),Fits (%)
0,DeepSeek-R1,Few-shot CoT + Code + Context,2741,63,2678,2.30,97.70
1,DeepSeek-R1,Few-shot CoT + Code Only,2741,0,2741,0.00,100.00
2,DeepSeek-R1,Zero-shot + Code + Context,2741,60,2681,2.19,97.81
3,DeepSeek-R1,Zero-shot + Code Only,2741,0,2741,0.00,100.00
4,DeepSeek-R1,Zero-shot CoT + Code + Context,2741,60,2681,2.19,97.81
5,DeepSeek-R1,Zero-shot CoT + Code Only,2741,0,2741,0.00,100.00
6,Llama-4-Maverick,Few-shot CoT + Code + Context,2741,2,2739,0.07,99.93
7,Llama-4-Maverick,Few-shot CoT + Code Only,2741,0,2741,0.00,100.00
8,Llama-4-Maverick,Zero-shot + Code + Context,2741,2,2739,0.07,99.93
9,Llama-4-Maverick,Zero-shot + Code Only,2741,0,2741,0.00,100.00
10,Llama-4-Maverick,Zero-shot CoT + Code + Context,2741,2,2739,0.07,99.93
11,Llama-4-Maverick,Zero-shot CoT + Code Only,2741,0,2741,0.00,100.00
12,Qwen3-Coder,Few-shot CoT + Code + Context,2741,63,2678,2.30,97.70
13,Qwen3-Coder,Few-shot CoT + Code Only,2741,0,2741,0.00,100.00
14,Qwen3-Coder,Zero-shot + Code + Context,2741,60,2681,2.19,97.81
15,Qwen3-Coder,Zero-shot + Code Only,2741,0,2741,0.00,100.00
16,Qwen3-Coder,Zero-shot CoT + Code + Context,2741,60,2681,2.19,97.81
17,Qwen3-Coder,Zero-shot CoT + Code Only,2741,0,2741,0.00,100.00

## Step 12 - Verify Generated Prompt Templates

One representative prompt is generated for each prompt configuration to verify that the prompt builder correctly constructs the expected input before performing the context window analysis.

In [11]:
# ============================================================
# Step 12 - Verify Generated Prompt Templates
# ============================================================

# Use the first sample for verification
sample = working_df.iloc[0]

for config in PROMPT_CONFIGS:

    print("=" * 120)
    print(f"Prompt Configuration : {config['name']}")
    print(f"Strategy             : {config['strategy']}")
    print(f"Include Context      : {config['include_context']}")
    print("=" * 120)

    prompt = build_prompt(
        sample=sample,
        strategy=config["strategy"],
        include_context=config["include_context"]
    )

    token_count = len(tokenizer.encode(prompt))

    print(f"Character Count : {len(prompt):,}")
    print(f"Token Count     : {token_count:,}")
    print()
    print(prompt)
    print("\n\n")

========================================================================================================================
Prompt Configuration : Zero-shot + Code Only
Strategy             : zero_shot
Include Context      : False
========================================================================================================================
Character Count : 2,485
Token Count     : 541

You are an expert software testing assistant specializing in flaky test identification and classification.

Base every decision solely on the provided artifacts.

Do not rely on external knowledge or assumptions.

If the available evidence is insufficient to confidently identify a flaky test, classify it as Non-Flaky.

Your task is to analyze the provided software testing artifacts.

Determine whether the test is Flaky or Non-Flaky.

If the test is Flaky, select exactly one issue category from the provided category list.

Justify the classification using only the provided evidence.

Identify the artifacts that support your conclusion.

## Flaky Test Categories

If the test is classified as Flaky, select exactly one issue category from the following list.

1. Implementation Dependent
   - The test outcome depends on implementation-specific behavior rather than the intended specification.

2. Order Dependent
   - The test outcome depends on the execution order of tests because of shared state or side effects.

3. Non-Idempotent
   - Repeated execution changes the outcome because the test or system under test modifies state that is not reset.

4. Time Dependent
   - The test outcome depends on timing, scheduling, delays, clocks, or asynchronous execution.

If the test is classified as Non-Flaky, return:

Non-Flaky

Analyze the following test artifacts.

Produce the final classification based only on the provided artifacts.

## Input

### 1. Test Code

@Test
  public void testFindItemsByNamespace() throws Exception {
    final int page = 0;
    final int size = 50;
    final ArgumentCaptor<HttpGet> request = ArgumentCaptor.forClass(HttpGet.class);

    itemOpenApiService.findItemsByNamespace(someAppId, someEnv, someCluster, someNamespace, page, size);

    verify(httpClient, times(1)).execute(request.capture());

    HttpGet get = request.getValue();

    assertEquals(String.format("%s/envs/%s/apps/%s/clusters/%s/namespaces/%s/items?size=%s&page=%s",
            someBaseUrl, someEnv, someAppId, someCluster, someNamespace, size, page), get.getURI().toString());
  }

Return only the following JSON object without any additional explanation or markdown.

{
    "classification": "<Flaky | Non-Flaky>",
    "category": "<One category from the provided category list or Non-Flaky>",
    "reasoning": "...",
    "evidence": [
        < List of artifacts helps to conclusion. Example: "Test Code", "Helper Methods", "Failure Log", "Production Code" >
    ]
}



========================================================================================================================
Prompt Configuration : Zero-shot + Code + Context
Strategy             : zero_shot
Include Context      : True
========================================================================================================================
Character Count : 13,685
Token Count     : 2,991

You are an expert software testing assistant specializing in flaky test identification and classification.

Base every decision solely on the provided artifacts.

Do not rely on external knowledge or assumptions.

If the available evidence is insufficient to confidently identify a flaky test, classify it as Non-Flaky.

Your task is to analyze the provided software testing artifacts.

Determine whether the test is Flaky or Non-Flaky.

If the test is Flaky, select exactly one issue category from the provided category list.

Justify the classification using only the provided evidence.

Identify the artifacts that support your conclusion.

## Flaky Test Categories

If the test is classified as Flaky, select exactly one issue category from the following list.

1. Implementation Dependent
   - The test outcome depends on implementation-specific behavior rather than the intended specification.

2. Order Dependent
   - The test outcome depends on the execution order of tests because of shared state or side effects.

3. Non-Idempotent
   - Repeated execution changes the outcome because the test or system under test modifies state that is not reset.

4. Time Dependent
   - The test outcome depends on timing, scheduling, delays, clocks, or asynchronous execution.

If the test is classified as Non-Flaky, return:

Non-Flaky

Analyze the following test artifacts.

Produce the final classification based only on the provided artifacts.

## Input

### 1. Test Code

@Test
  public void testFindItemsByNamespace() throws Exception {
    final int page = 0;
    final int size = 50;
    final ArgumentCaptor<HttpGet> request = ArgumentCaptor.forClass(HttpGet.class);

    itemOpenApiService.findItemsByNamespace(someAppId, someEnv, someCluster, someNamespace, page, size);

    verify(httpClient, times(1)).execute(request.capture());

    HttpGet get = request.getValue();

    assertEquals(String.format("%s/envs/%s/apps/%s/clusters/%s/namespaces/%s/items?size=%s&page=%s",
            someBaseUrl, someEnv, someAppId, someCluster, someNamespace, size, page), get.getURI().toString());
  }

### 3. Failure Log

org.junit.ComparisonFailure: expected:<...someNamespace/items?[size=50&page=]0> but was:<...someNamespace/items?[page=0&size=5]0>
	at org.junit.Assert.assertEquals(Assert.java:117)
	at org.junit.Assert.assertEquals(Assert.java:146)
	at com.ctrip.framework.apollo.openapi.client.service.ItemOpenApiServiceTest.testFindItemsByNamespace(ItemOpenApiServiceTest.java:321)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.mockito.internal.runners.DefaultInternalRunner$1$1.evaluate(DefaultInternalRunner.java:55)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.mockito.internal.runners.DefaultInternalRunner$1.run(DefaultInternalRunner.java:100)
	at org.mockito.internal.runners.DefaultInternalRunner.run(DefaultInternalRunner.java:107)
	at org.mockito.internal.runners.StrictRunner.run(StrictRunner.java:41)
	at org.mockito.junit.MockitoJUnitRunner.run(MockitoJUnitRunner.java:163)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:43)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:82)
	at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:73)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:150)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)

### 4. Production Code

Class: com.ctrip.framework.apollo.openapi.client.service.AbstractOpenApiService

Method: checkHttpResponseStatus

private void checkHttpResponseStatus(HttpResponse response) {
    if (response.getStatusLine().getStatusCode() == 200) {
      return;
    }

    StatusLine status = response.getStatusLine();
    String message = "";
    try {
      message = EntityUtils.toString(response.getEntity());
    } catch (IOException e) {

    }

    throw new ApolloOpenApiException(status.getStatusCode(), status.getReasonPhrase(), message);
  }

----------------------------------------

Method: checkNotEmpty

protected void checkNotEmpty(String value, String name) {
    Preconditions.checkArgument(!Strings.isNullOrEmpty(value), name + " should not be null or empty");
  }

----------------------------------------

Method: checkPage

protected void checkPage(int page) {
    Preconditions.checkArgument(page >= 0, "page should be positive or 0");
  }

----------------------------------------

Method: checkSize

protected void checkSize(int size) {
    Preconditions.checkArgument(size > 0, "size should be positive number");
  }

----------------------------------------

Method: get

protected CloseableHttpResponse get(OpenApiPathBuilder path) throws IOException {
    HttpGet get = new HttpGet(path.buildPath(baseUrl));

    return execute(get);
  }

----------------------------------------

Class: com.ctrip.framework.apollo.openapi.client.service.ItemOpenApiService

Method: findItemsByNamespace

@Override
  public OpenPageDTO<OpenItemDTO> findItemsByNamespace(String appId, String env, String clusterName,
                                                       String namespaceName, int page, int size) {
    if (Strings.isNullOrEmpty(clusterName)) {
      clusterName = ConfigConsts.CLUSTER_NAME_DEFAULT;
    }
    if (Strings.isNullOrEmpty(namespaceName)) {
      namespaceName = ConfigConsts.NAMESPACE_APPLICATION;
    }

    checkNotEmpty(appId, "App id");
    checkNotEmpty(env, "Env");
    checkPage(page);
    checkSize(size);

    OpenApiPathBuilder pathBuilder = OpenApiPathBuilder.newBuilder()
            .envsPathVal(env)
            .appsPathVal(appId)
            .clustersPathVal(clusterName)
            .namespacesPathVal(namespaceName)
            .itemsPathVal("")
            .addParam("page", page)
            .addParam("size", size);

    try (CloseableHttpResponse response = get(pathBuilder)) {
      return gson.fromJson(EntityUtils.toString(response.getEntity()), OPEN_PAGE_DTO_OPEN_ITEM_DTO_TYPE_REFERENCE);
    } catch (Throwable ex) {
      throw new RuntimeException(String.format("Paging get items: appId: %s, cluster: %s, namespace: %s in env: %s failed",
              appId, clusterName, namespaceName, env), ex);
    }
  }

----------------------------------------

Class: com.ctrip.framework.apollo.openapi.client.url.OpenApiPathBuilder

Method: addParam

public OpenApiPathBuilder addParam(String key, Object value) {
    if (Strings.isNullOrEmpty(key)) {
      throw new IllegalArgumentException("Param key should not be null or empty");
    }
    this.params.put(key, escapeParam(String.valueOf(value)));
    return this;
  }

----------------------------------------

Method: appsPathVal

public OpenApiPathBuilder appsPathVal(String apps) {
    pathVariable.put(APPS_PATH, escapePath(apps));
    return this;
  }

----------------------------------------

Method: buildPath

public String buildPath(String baseUrl) {
    if (Strings.isNullOrEmpty(baseUrl)) {
      throw new IllegalArgumentException("Base url should not be null or empty");
    }
    List<String> parts = new ArrayList<>();
    parts.add(baseUrl);

    for (String k : SORTED_PATH_KEYS) {
      if (pathVariable.containsKey(k)) {
        parts.add(k);
        String v = pathVariable.get(k);
        if (!Strings.isNullOrEmpty(v)) {
          parts.add(v);
        }
      }
    }

    if (!Strings.isNullOrEmpty(this.customResource)) {
      parts.add(this.customResource);
    }

    String path = PATH_JOIN.join(parts);

    if (!params.isEmpty()) {
      StringBuilder sb = new StringBuilder();
      for (Map.Entry<String, String> kv : params.entrySet()) {
        if (sb.length() > 0) {
          sb.append("&");
        }
        sb.append(kv.getKey()).append("=").append(kv.getValue());
      }
      path += "?" + sb;
    }
    return path;
  }

----------------------------------------

Method: clustersPathVal

public OpenApiPathBuilder clustersPathVal(String clusters) {
    pathVariable.put(CLUSTERS_PATH, escapePath(clusters));
    return this;
  }

----------------------------------------

Method: envsPathVal

public OpenApiPathBuilder envsPathVal(String envs) {
    pathVariable.put(ENVS_PATH, escapePath(envs));
    return this;
  }

----------------------------------------

Method: escapeParam

protected String escapeParam(String param) {
    return QUERY_PARAM_ESCAPER.escape(param);
  }

----------------------------------------

Method: escapePath

protected String escapePath(String path) {
    return PATH_ESCAPER.escape(path);
  }

----------------------------------------

Method: itemsPathVal

public OpenApiPathBuilder itemsPathVal(String items) {
    if (UrlUtils.hasIllegalChar(items)) {
      items = new String(Base64.getEncoder().encode(items.getBytes(StandardCharsets.UTF_8)));
      pathVariable.put(ENCODED_ITEMS_PATH, escapePath(items));
    } else {
      pathVariable.put(ITEMS_PATH, escapePath(items));
    }
    return this;
  }

----------------------------------------

Method: namespacesPathVal

public OpenApiPathBuilder namespacesPathVal(String namespaces) {
    pathVariable.put(NAMESPACES_PATH, escapePath(namespaces));
    return this;
  }

----------------------------------------

Method: newBuilder

public static OpenApiPathBuilder newBuilder() {
    return new OpenApiPathBuilder();
  }

----------------------------------------

Class: com.ctrip.framework.apollo.openapi.dto.OpenItemDTO

Method: getValue

public String getValue() {
    return value;
  }

----------------------------------------

Class: com.ctrip.framework.apollo.openapi.utils.UrlUtils

Method: hasIllegalChar

public static boolean hasIllegalChar(String key) {
        if (Strings.isNullOrEmpty(key)) {
            return false;
        }
        Matcher matcher = ILLEGAL_KEY_PATTERN.matcher(key);
        return matcher.find();
    }

----------------------------------------

Return only the following JSON object without any additional explanation or markdown.

{
    "classification": "<Flaky | Non-Flaky>",
    "category": "<One category from the provided category list or Non-Flaky>",
    "reasoning": "...",
    "evidence": [
        < List of artifacts helps to conclusion. Example: "Test Code", "Helper Methods", "Failure Log", "Production Code" >
    ]
}



========================================================================================================================
Prompt Configuration : Zero-shot CoT + Code Only
Strategy             : zero_shot_cot
Include Context      : False
========================================================================================================================
Character Count : 2,679
Token Count     : 575

You are an expert software testing assistant specializing in flaky test identification and classification.

Base every decision solely on the provided artifacts.

Do not rely on external knowledge or assumptions.

If the available evidence is insufficient to confidently identify a flaky test, classify it as Non-Flaky.

Your task is to analyze the provided software testing artifacts.

Determine whether the test is Flaky or Non-Flaky.

If the test is Flaky, select exactly one issue category from the provided category list.

Justify the classification using only the provided evidence.

Identify the artifacts that support your conclusion.

## Flaky Test Categories

If the test is classified as Flaky, select exactly one issue category from the following list.

1. Implementation Dependent
   - The test outcome depends on implementation-specific behavior rather than the intended specification.

2. Order Dependent
   - The test outcome depends on the execution order of tests because of shared state or side effects.

3. Non-Idempotent
   - Repeated execution changes the outcome because the test or system under test modifies state that is not reset.

4. Time Dependent
   - The test outcome depends on timing, scheduling, delays, clocks, or asynchronous execution.

If the test is classified as Non-Flaky, return:

Non-Flaky

Study the worked examples below.

Each example illustrates how to:
- identify the relevant evidence,
- evaluate possible sources of flakiness,
- eliminate unsupported explanations,
- determine the final classification.

Apply the same reasoning process demonstrated in the examples to the new test case.

## Input

### 1. Test Code

@Test
  public void testFindItemsByNamespace() throws Exception {
    final int page = 0;
    final int size = 50;
    final ArgumentCaptor<HttpGet> request = ArgumentCaptor.forClass(HttpGet.class);

    itemOpenApiService.findItemsByNamespace(someAppId, someEnv, someCluster, someNamespace, page, size);

    verify(httpClient, times(1)).execute(request.capture());

    HttpGet get = request.getValue();

    assertEquals(String.format("%s/envs/%s/apps/%s/clusters/%s/namespaces/%s/items?size=%s&page=%s",
            someBaseUrl, someEnv, someAppId, someCluster, someNamespace, size, page), get.getURI().toString());
  }

Return only the following JSON object without any additional explanation or markdown.

{
    "classification": "<Flaky | Non-Flaky>",
    "category": "<One category from the provided category list or Non-Flaky>",
    "reasoning": "...",
    "evidence": [