# 03 - Batch Experiments (OpenAI)

This notebook executes flaky test classification experiments using the OpenAI Batch API.

## Workflow
1. Define experiments
2. Validate request files
3. Upload batch request files
4. Create OpenAI Batch jobs
5. Monitor batch execution
6. Download batch results
7. Parse predictions
8. Save predictions for evaluation

This notebook follows the same workflow as `02_batch_experiments.ipynb`, replacing the Gemini Batch API with the OpenAI Batch API.

In [1]:
%pip install openai tqdm

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: openai in C:\Users\ASUS\AppData\Roaming\Python\Python314\site-packages (2.49.0)
Requirement already satisfied: tqdm in C:\Users\ASUS\AppData\Roaming\Python\Python314\site-packages (4.70.0)
Requirement already satisfied: anyio<5,>=3.5.0 in C:\Users\ASUS\AppData\Roaming\Python\Python314\site-packages (from openai) (4.12.1)
Requirement already satisfied: distro<2,>=1.7.0 in C:\Users\ASUS\AppData\Roaming\Python\Python314\site-packages (from openai) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in C:\Users\ASUS\AppData\Roaming\Python\Python314\site-packages (from openai) (0.28.1)
Requirement already satisfied: jiter<1,>=0.10.0 in C:\Users\ASUS\AppData\Roaming\Python\Python314\site-packages (from openai) (0.16.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in C:\Users\ASUS\AppData\Roaming\Python\Python314\site-packages (from openai) (2.12.5)
Requirement already satisfied: sniffio in C:\Users\ASUS\AppData\Roaming\Python\Python314\site-packages (from openai) (1.3.1)
Requirement already satisfied: typing-extensions<5,>=4.14 in C:\Users\ASUS\AppData\Roaming\Python\Python314\site-packages (from openai) (4.15.0)
Requirement already satisfied: idna>=2.8 in C:\Users\ASUS\AppData\Roaming\Python\Python314\site-packages (from anyio<5,>=3.5.0->openai) (3.11)
Requirement already satisfied: certifi in C:\Users\ASUS\AppData\Roaming\Python\Python314\site-packages (from httpx<1,>=0.23.0->openai) (2026.4.22)
Requirement already satisfied: httpcore==1.* in C:\Users\ASUS\AppData\Roaming\Python\Python314\site-packages (from httpx<1,>=0.23.0->openai) (1.0.9)
Requirement already satisfied: h11>=0.16 in C:\Users\ASUS\AppData\Roaming\Python\Python314\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in C:\Users\ASUS\AppData\Roaming\Python\Python314\site-packages (from pydantic<3,>=1.9.0->openai) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in C:\Users\ASUS\AppData\Roaming\Python\Python314\site-packages (from pydantic<3,>=1.9.0->openai) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in C:\Users\ASUS\AppData\Roaming\Python\Python314\site-packages (from pydantic<3,>=1.9.0->openai) (0.4.2)
Requirement already satisfied: colorama in C:\Users\ASUS\AppData\Roaming\Python\Python314\site-packages (from tqdm) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
# ==========================================================
# OpenAI Configuration
# ==========================================================

from pathlib import Path

from openai import OpenAI

from dotenv import load_dotenv
import os

load_dotenv()

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")

# Initialize client
client = OpenAI( api_key=OPENAI_API_KEY )

# Model Configuration
MODEL_NAME = "gpt-5-mini"
BATCH_ENDPOINT_URL = "/v1/responses"
MAX_OUTPUT_TOKENS = 2048


# ============================================================
# Project Directories
# ============================================================

PROJECT_ROOT = Path.cwd().parent

DATA_DIR = PROJECT_ROOT / "datasets"

REQUEST_DIR = PROJECT_ROOT / "generated_prompts" / "openai_batch_requests"

RESULTS_DIR = PROJECT_ROOT / "results"

REQUEST_DIR.mkdir(parents=True, exist_ok=True)
RESULTS_DIR.mkdir(parents=True, exist_ok=True)

print(f"Model      : {MODEL_NAME}")
print(f"Requests   : {REQUEST_DIR}")
print(f"Results    : {RESULTS_DIR}")

Model      : gpt-5-mini
Requests   : d:\university works\Final-Year_Firts_sem\FYP\INFO\REPO\CA-Classification-Framework\generated_prompts\openai_batch_requests
Results    : d:\university works\Final-Year_Firts_sem\FYP\INFO\REPO\CA-Classification-Framework\results

In [3]:
# ============================================================
# Experiment Definitions
# ============================================================

EXPERIMENTS = [
    {
        "name": "zero_shot_without_context",
        "prompt_type": "zero_shot",
        "context_enabled": False,
    },
    {
        "name": "zero_shot_with_context",
        "prompt_type": "zero_shot",
        "context_enabled": True,
    },
    {
        "name": "zero_shot_cot_without_context",
        "prompt_type": "zero_shot_cot",
        "context_enabled": False,
    },
    {
        "name": "zero_shot_cot_with_context",
        "prompt_type": "zero_shot_cot",
        "context_enabled": True,
    },
    {
        "name": "few_shot_cot_without_context",
        "prompt_type": "few_shot_cot",
        "context_enabled": False,
    },
    {
        "name": "few_shot_cot_with_context",
        "prompt_type": "few_shot_cot",
        "context_enabled": True,
    },
]

print(f"Total Experiments: {len(EXPERIMENTS)}")

for exp in EXPERIMENTS:
    print(f"• {exp['name']}")

Total Experiments: 6
• zero_shot_without_context
• zero_shot_with_context
• zero_shot_cot_without_context
• zero_shot_cot_with_context
• few_shot_cot_without_context
• few_shot_cot_with_context

## 3. Load Evaluation Dataset

Load the evaluation dataset that will be used to generate prompts for every
experiment. A lookup table is also created to enable efficient retrieval of
samples using their unique identifier when predictions are merged with
ground truth later.

In [4]:
# ============================================================
# Imports
# ============================================================

import json
import time

import pandas as pd
from tqdm.auto import tqdm

# ============================================================
# Load Evaluation Dataset
# ============================================================

EVALUATION_DATASET = DATA_DIR / "evaluation_dataset.jsonl"

if not EVALUATION_DATASET.exists():
    raise FileNotFoundError(
        f"Evaluation dataset not found:\n{EVALUATION_DATASET}"
    )

df = pd.read_json(EVALUATION_DATASET, lines=True)

df_lookup = df.set_index("id")

print(f"✓ Loaded {len(df)} evaluation samples.")

df.head()

C:\Users\ASUS\AppData\Roaming\Python\Python314\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

✓ Loaded 2210 evaluation samples.

,id,test_id,isFlaky,issue_category,repo_url,issue_commit,fixed_commit,test_code,helper_methods_json,failure_log,code_under_test_json,test_code_original,helper_methods_json_original,failure_log_original,code_under_test_original,has_helper_methods,has_code_under_test,has_failure_log,context_score
0,857,ormlitecore59309e55,True,Order Dependent,https://github.com/j256/ormlite-core,59309e51c61e8a63cb5fd24a5a7607b668a5f095,c80bde196ca152ecc8a3c4f38f77dbe5a4ea3232,@Test\n\tpublic void testSetObjectCacheThrow()...,{},org.opentest4j.AssertionFailedError: Unexpecte...,{'com.j256.ormlite.dao.BaseDaoImpl': {'setObje...,@Test\n\tpublic void testSetObjectCacheThrow()...,{},Failed Rounds: 10/10\norg.opentest4j.Assertion...,{'com.j256.ormlite.dao.BaseDaoImpl': {'setObje...,False,True,True,3
1,1574,Closure-144-21,False,Non-Flaky,https://github.com/google/closure-compiler,c9e89727dc8063d087d28e42629606f4fd74a6e5,465282f1ca28a208b06c47b55fd292d4631c55da,public void testExportMultiple3() throws Excep...,{'compileAndCheck': 'private void compileAndCh...,junit.framework.ComparisonFailure: expected:<....,{'com.google.javascript.jscomp.Result': {'<ini...,public void testExportMultiple3() throws Excep...,{'compileAndCheck': 'private void compileAndCh...,Failed Rounds: 1/1\njunit.framework.Comparison...,{'com.google.javascript.jscomp.Result': {'<ini...,True,True,True,5
2,1483,Closure-115-5,False,Non-Flaky,https://github.com/google/closure-compiler,2d6e1c78f41248fbbb1eec43b23e7430e2bc7885,4597738e8898f738c1f969fe90479728be81cc80,public void testInlineFunctions6() {\n\n te...,"{'test': 'public void test(String js, String e...",junit.framework.AssertionFailedError:\nExpecte...,{'com.google.javascript.jscomp.DiagnosticType'...,public void testInlineFunctions6() {\n // m...,{'test': '/** * Verifies that the compiler ...,Failed Rounds: 1/1\njunit.framework.AssertionF...,{'com.google.javascript.jscomp.DiagnosticType'...,True,True,True,5
3,431,ignite3modulesstoragerocksdb19c8a82testAbortWrite,True,Implementation Dependent,https://github.com/apache/ignite-3,19c8a824bd9d31f0d0dbd3fbbdd2a32ee360cab2,de6ee0702398f9ce3022a8e265c633857f3a3d88,.\n */\n @Test\n public void testAbo...,{'read': 'protected BinaryRow read(RowId rowId...,org.junit.jupiter.api.extension.ParameterResol...,{'org.apache.ignite.internal.hlc.HybridTimesta...,.\n */\n @Test\n public void testAbo...,{'read': '/** * Reads a row. */ ...,Failed Rounds: 84/101\norg.junit.jupiter.api.e...,{'org.apache.ignite.internal.hlc.HybridTimesta...,True,True,True,5
4,1563,Closure-144-10,False,Non-Flaky,https://github.com/google/closure-compiler,c9e89727dc8063d087d28e42629606f4fd74a6e5,465282f1ca28a208b06c47b55fd292d4631c55da,public void testVariableArgumentsTypesAnnotati...,{'assertTypeAnnotations': 'private void assert...,junit.framework.ComparisonFailure: expected:<....,{'com.google.javascript.rhino.Node': {'getDoub...,public void testVariableArgumentsTypesAnnotati...,{'assertTypeAnnotations': 'private void assert...,Failed Rounds: 1/1\njunit.framework.Comparison...,{'com.google.javascript.rhino.Node': {'getDoub...,True,True,True,5

### Import Prompt Builder

Prompt engineering logic is **reused unchanged** from `utils/prompt_builder.py`,
the same utility used by `classification-phase-01-gemini.ipynb`.

In [5]:
import sys

sys.path.insert(0, str(PROJECT_ROOT))

from utils.prompt_builder import build_prompt

## 4. Generate OpenAI Batch Request Files

For every experiment, this section iterates through the evaluation dataset,
builds the prompt using the existing `build_prompt` utility (prompt
engineering logic is **not** modified here), and writes one OpenAI Batch API
request per sample.

Each line follows the OpenAI Batch API format:

```json
{
  "custom_id": "sample_<id>",
  "method": "POST",
  "url": "/v1/responses",
  "body": {
    "model": "gpt-5-mini",
    "input": "...generated prompt...",
    "max_output_tokens": 2048
  }
}
```

Request files are written to `generated_prompts/openai_batch_requests/`.
If a request file already exists, generation is skipped for that experiment
so the notebook can be re-run without unnecessary rework. Pass
`overwrite=True` to force regeneration.

In [6]:
# ============================================================
# Build OpenAI Batch Request Files
# ============================================================

def build_batch_request_line(sample: dict, prompt_type: str, context_enabled: bool) -> dict:
    """
    Build a single OpenAI Batch API request record for one dataset sample.

    Reuses the existing `build_prompt` utility for prompt engineering.
    """

    prompt = build_prompt(
        sample=sample,
        strategy=prompt_type,
        include_context=context_enabled,
    )

    return {
        "custom_id": f"sample_{sample['id']}",
        "method": "POST",
        "url": BATCH_ENDPOINT_URL,
        "body": {
            "model": MODEL_NAME,
            "input": prompt,
            "max_output_tokens": MAX_OUTPUT_TOKENS,
        },
    }


def generate_request_file(experiment: dict, overwrite: bool = False):
    """
    Generate a JSONL OpenAI Batch request file for one experiment.

    Skips generation if the file already exists, unless overwrite=True.
    """

    request_file = REQUEST_DIR / f"{experiment['name']}.jsonl"

    if request_file.exists() and not overwrite:
        print(f"↻ Skipping generation (exists): {request_file.name}")
        return request_file

    print(f"Generating prompts for: {experiment['name']}")

    with open(request_file, "w", encoding="utf-8") as f:

        for _, row in tqdm(
            df.iterrows(),
            total=len(df),
            desc=experiment["name"],
        ):
            sample = row.to_dict()

            record = build_batch_request_line(
                sample=sample,
                prompt_type=experiment["prompt_type"],
                context_enabled=experiment["context_enabled"],
            )

            f.write(json.dumps(record, ensure_ascii=False) + "\n")

    print(f"✓ Wrote request file: {request_file}")

    return request_file

In [7]:
# ============================================================
# Generate Request Files for All Experiments
# ============================================================

for experiment in EXPERIMENTS:
    experiment["request_file"] = generate_request_file(experiment, overwrite=False)

Generating prompts for: zero_shot_without_context

zero_shot_without_context: 100%|██████████| 2210/2210 [00:02<00:00, 1026.28it/s]

✓ Wrote request file: d:\university works\Final-Year_Firts_sem\FYP\INFO\REPO\CA-Classification-Framework\generated_prompts\openai_batch_requests\zero_shot_without_context.jsonl
Generating prompts for: zero_shot_with_context

zero_shot_with_context: 100%|██████████| 2210/2210 [00:02<00:00, 844.16it/s]

✓ Wrote request file: d:\university works\Final-Year_Firts_sem\FYP\INFO\REPO\CA-Classification-Framework\generated_prompts\openai_batch_requests\zero_shot_with_context.jsonl
Generating prompts for: zero_shot_cot_without_context

zero_shot_cot_without_context: 100%|██████████| 2210/2210 [00:01<00:00, 1145.09it/s]

✓ Wrote request file: d:\university works\Final-Year_Firts_sem\FYP\INFO\REPO\CA-Classification-Framework\generated_prompts\openai_batch_requests\zero_shot_cot_without_context.jsonl
Generating prompts for: zero_shot_cot_with_context

zero_shot_cot_with_context: 100%|██████████| 2210/2210 [00:02<00:00, 899.47it/s]

✓ Wrote request file: d:\university works\Final-Year_Firts_sem\FYP\INFO\REPO\CA-Classification-Framework\generated_prompts\openai_batch_requests\zero_shot_cot_with_context.jsonl
Generating prompts for: few_shot_cot_without_context

few_shot_cot_without_context: 100%|██████████| 2210/2210 [00:02<00:00, 928.41it/s]

✓ Wrote request file: d:\university works\Final-Year_Firts_sem\FYP\INFO\REPO\CA-Classification-Framework\generated_prompts\openai_batch_requests\few_shot_cot_without_context.jsonl
Generating prompts for: few_shot_cot_with_context

few_shot_cot_with_context: 100%|██████████| 2210/2210 [00:03<00:00, 711.25it/s]

✓ Wrote request file: d:\university works\Final-Year_Firts_sem\FYP\INFO\REPO\CA-Classification-Framework\generated_prompts\openai_batch_requests\few_shot_cot_with_context.jsonl

## 5. Validate Request Files

Before uploading, verify that every request file exists and is not empty.

In [8]:
# ============================================================
# Validate Request Files
# ============================================================

print("Validating experiment request files...\n")

for experiment in EXPERIMENTS:
    request_file = experiment.get("request_file") or (
        REQUEST_DIR / f"{experiment['name']}.jsonl"
    )

    if not request_file.exists():
        raise FileNotFoundError(
            f"Missing request file:\n{request_file}"
        )

    if request_file.stat().st_size == 0:
        raise ValueError(
            f"Request file is empty:\n{request_file}"
        )

    experiment["request_file"] = request_file

    print(f"✓ {experiment['name']}")

print(f"\nAll {len(EXPERIMENTS)} request files are available.")

Validating experiment request files...

✓ zero_shot_without_context
✓ zero_shot_with_context
✓ zero_shot_cot_without_context
✓ zero_shot_cot_with_context
✓ few_shot_cot_without_context
✓ few_shot_cot_with_context

All 6 request files are available.

## 6. Batch Execution Functions

This section implements the reusable functions required to execute each
batch experiment using the OpenAI Batch API:

1. Upload the request JSONL file.
2. Create an OpenAI Batch job.
3. Monitor the job until completion.
4. Download the generated response.
5. Convert the response into the standardized prediction format.
6. Save the prediction results.

These functions are reused for all six experiments to ensure a consistent
execution process.

### 6.1 Upload Request File

The first step in the execution workflow is uploading the generated JSONL
request file to the OpenAI Files API with `purpose="batch"`.

The uploaded file is later referenced when creating the batch job.

In [9]:
# ============================================================
# Upload Request File
# ============================================================

def upload_request_file(request_file: Path):
    """
    Upload a JSONL request file to the OpenAI Files API.

    Args:
        request_file (Path): Path to the JSONL request file.

    Returns:
        Uploaded OpenAI file object.
    """

    print(f"Uploading: {request_file.name}")

    with open(request_file, "rb") as f:
        uploaded_file = client.files.create(
            file=f,
            purpose="batch",
        )

    print(f"✓ Upload completed")
    print(f"File Id : {uploaded_file.id}")

    return uploaded_file

In [10]:
experiment = EXPERIMENTS[0]

uploaded_file = upload_request_file(experiment["request_file"])

Uploading: zero_shot_without_context.jsonl
✓ Upload completed
File Id : file-8BdCPLfn3sQ6W7Wu9d5MQj

### 6.2 Create Batch Job

After uploading the request file, an OpenAI Batch job is created.

The batch job references the uploaded JSONL file and specifies the
`/v1/responses` endpoint that should process every request contained in the
file.

The returned batch object is used to monitor execution and later download
the generated predictions.

In [11]:
# ============================================================
# Create Batch Job
# ============================================================

def create_batch_job(uploaded_file):
    """
    Create an OpenAI Batch job.

    Args:
        uploaded_file: Uploaded OpenAI file object.

    Returns:
        Batch job object.
    """

    print("Creating batch job...")

    batch_job = client.batches.create(
        input_file_id=uploaded_file.id,
        endpoint=BATCH_ENDPOINT_URL,
        completion_window="24h",
    )

    print("✓ Batch job created")
    print(f"Batch Job : {batch_job.id}")
    print(f"State     : {batch_job.status}")

    return batch_job

In [12]:
batch_job = create_batch_job(uploaded_file)

Creating batch job...
✓ Batch job created
Batch Job : batch_6a687aec18a4819084ac7c03dc597357
State     : validating

### 6.3 Monitor Batch Job

After a batch job is created, it executes asynchronously.

This function periodically checks the job status until it reaches a
terminal state.

Possible states include:

- validating
- in_progress
- finalizing
- completed
- failed
- expired
- cancelled

Only completed jobs are downloaded in the next step.

In [44]:
# ============================================================
# Wait for Batch Completion
# ============================================================

TERMINAL_SUCCESS_STATES = {"completed"}
TERMINAL_FAILURE_STATES = {"failed", "expired", "cancelled"}


def _format_batch_errors(batch_job):
    """
    Extract readable validation/runtime errors from a failed OpenAI batch.
    Handles object-like and dict-like SDK shapes.
    """

    errors = getattr(batch_job, "errors", None)
    if errors is None and isinstance(batch_job, dict):
        errors = batch_job.get("errors")

    if not errors:
        return "No error details returned by API."

    # Object shape: errors.data
    data = getattr(errors, "data", None)

    # Dict shape: {"data": [...]}
    if data is None and isinstance(errors, dict):
        data = errors.get("data")

    # Some SDK responses return list directly
    if data is None and isinstance(errors, list):
        data = errors

    if not data:
        return str(errors)

    lines = []
    for item in data:
        if isinstance(item, dict):
            code = item.get("code", "unknown_code")
            message = item.get("message", "")
            param = item.get("param")
        else:
            code = getattr(item, "code", "unknown_code")
            message = getattr(item, "message", "")
            param = getattr(item, "param", None)

        if param:
            lines.append(f"- {code}: {message} (param={param})")
        else:
            lines.append(f"- {code}: {message}")

    return "\n".join(lines) if lines else "No structured error entries returned."


def wait_for_batch_completion(batch_job, poll_interval=30):
    """
    Wait until an OpenAI Batch job completes.

    Args:
        batch_job: OpenAI batch job object.
        poll_interval (int): Seconds between status checks.

    Returns:
        Completed batch job object.
    """

    print("\nWaiting for batch job to complete...\n")

    while True:

        batch_job = client.batches.retrieve(batch_job.id)

        completed = batch_job.request_counts.completed if batch_job.request_counts else "?"
        total = batch_job.request_counts.total if batch_job.request_counts else "?"

        print(f"{time.strftime('%H:%M:%S')} | {batch_job.status} | {completed}/{total}")

        if batch_job.status in TERMINAL_SUCCESS_STATES:
            print("\n✓ Batch job completed successfully.")
            return batch_job

        if batch_job.status in TERMINAL_FAILURE_STATES:
            error_details = _format_batch_errors(batch_job)
            raise RuntimeError(
                f"Batch job ended with status: {batch_job.status}\n"
                f"Batch ID: {batch_job.id}\n"
                f"Details:\n{error_details}"
            )

        time.sleep(poll_interval)

In [45]:
completed_batch = wait_for_batch_completion(batch_job)

Waiting for batch job to complete...

18:15:08 | completed | 2210/2210

✓ Batch job completed successfully.

### 6.4 Download Batch Results

Download the raw output file generated by the completed OpenAI Batch job.

The downloaded file contains one JSON response per request submitted to the
Batch API. These responses are stored without modification so they can be
parsed in the next step. If the batch also produced an error file, it is
downloaded alongside the output file.

In [46]:
# ============================================================
# Download Batch Results
# ============================================================

def get_experiment_directory(experiment):
    """
    Create the output directory for an experiment.
    """

    context_folder = (
        "with_context"
        if experiment["context_enabled"]
        else "without_context"
    )

    experiment_dir = (
        RESULTS_DIR
        / MODEL_NAME
        / experiment["prompt_type"]
        / context_folder
    )

    experiment_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    return experiment_dir


def download_batch_results(batch_job, experiment):
    """
    Download the raw OpenAI Batch response.

    Args:
        batch_job: Completed OpenAI batch job.
        experiment (dict): Experiment configuration.

    Returns:
        Path: Downloaded raw response file.
    """

    if batch_job.output_file_id is None:
        raise RuntimeError("Batch job has no output file.")

    experiment_dir = get_experiment_directory(experiment)

    raw_response_file = experiment_dir / "raw_response.jsonl"

    print("Downloading batch results...")

    content = client.files.content(batch_job.output_file_id)

    with open(raw_response_file, "wb") as f:
        f.write(content.read())

    print("✓ Download completed")
    print(f"Saved to: {raw_response_file}")

    if batch_job.error_file_id:
        error_file = experiment_dir / "raw_errors.jsonl"
        error_content = client.files.content(batch_job.error_file_id)
        with open(error_file, "wb") as f:
            f.write(error_content.read())
        print(f"⚠ Batch reported per-request errors → {error_file}")

    return raw_response_file

In [47]:
batch_job = wait_for_batch_completion(batch_job)

Waiting for batch job to complete...

18:15:34 | completed | 2210/2210

✓ Batch job completed successfully.

In [48]:
raw_response_file = download_batch_results(
    batch_job,
    experiment
)

raw_response_file

Downloading batch results...
✓ Download completed
Saved to: d:\university works\Final-Year_Firts_sem\FYP\INFO\REPO\CA-Classification-Framework\results\gpt-5-mini\few_shot_cot\with_context\raw_response.jsonl

WindowsPath('d:/university works/Final-Year_Firts_sem/FYP/INFO/REPO/CA-Classification-Framework/results/gpt-5-mini/few_shot_cot/with_context/raw_response.jsonl')

### 6.5 Inspect Raw Batch Response

Before parsing the complete batch output, inspect a single response record
to verify the response structure returned by the OpenAI Batch API.

This validation step helps ensure the parsing logic matches the actual
response format.

In [18]:
# ============================================================
# Inspect Raw Batch Response
# ============================================================

from pprint import pprint

with open(raw_response_file, "r", encoding="utf-8") as f:
    first_record = json.loads(f.readline())

pprint(first_record)

{'custom_id': 'sample_857',
 'error': None,
 'id': 'batch_req_6a687edf34fc81908adb0009c40c8d1d',
 'response': {'body': {'background': False,
                       'billing': {'payer': 'developer'},
                       'completed_at': 1785232543,
                       'created_at': 1785232540,
                       'error': None,
                       'frequency_penalty': 0.0,
                       'id': 'resp_0d4b596545dde303006a687c9ce860819ea34e2e56dd544b92',
                       'incomplete_details': None,
                       'instructions': None,
                       'max_output_tokens': 2048,
                       'max_tool_calls': None,
                       'metadata': {},
                       'model': 'gpt-5-mini-2025-08-07',
                       'moderation': None,
                       'object': 'response',
                       'output': [{'content': [],
                                   'encrypted_content': 'gAAAAABqaHygvjxopr10IawS7IBMIYXY64wI2ckUwyozMcUDJVi_UsdkwkJil2z3TSZQd2zEvi6nmmlEXfqXmOKqXcU5lUAKL09gaXPEaz2wIUnN2qY2t-9zOGQRMpENWUMHq_gjXwuXwqrZMEnalG-aI3NnY5QySAsbTgaPsGrPWmkFU99ZS9guLLchFjQk0zH_VZGKYKITedeV1bQeGw2bLmVZ1IlJHi4GF-Bsy0rnEBm0BXrSBdUk9S4FXAzLAhncLjKkjFxPJEsrEPqWiaTdy9L4B1kZjDRDdZt7atugFV4Z_BPZZoMjaAOhvPW1wLpWoyBxsaVr2VeoahhUSryD140vVz3XiqV8e7dh7syicVqEv3mix1r9XjU1MYfBOVmgp10J2pYlTS5rU0xiQBjZEob0z6fAcI8T7FjrrUZFFoAWL5z5cE6FgnNwNFcE0imjUURIttZKArHUuLoPjmkEUUPNGTG0TzHt6iuSxTYzEwZY21xUbDEIMa0CBpnRUvFuhmJReSGxboFmyfjnIZhcbOqo2BgDC5Abdx9EyjxhosMPAzA8DCCNBmsMdAXd5P4rFcHQ7IBxdo-tRGhfbqGTQTXdEakdzPI8Uv6CH-1WV6DJm9PgpPFYldLtNsJeFU6HBpQ_jLpZpc1f5S0NNDtGU0KJmspfdsQwNWV0LCc3KdrHeduroGvqlXoPzHlxEFSs4I7T6DEQM5lItYEgjBygFQgMOorpU_jJ-FBYGYFNfKIlst3WgOtFqstM4oynDBPCmlYsntuNlpkTgc-H-eR4YRfztKMo9kgq4O67iff_4q-8Qo13ElrYR18aDB7tazd6_gkW9OgMv983yVZtmz_1M9yQ7Jc-Hwwo4XG62ru7xOd0I2huM-gdyLETDBT3csops8TbNE9EsPMNE0UnTei_b3lfh3iKeA-MNsryVY0OH42_P9mAyYC8odMHWnuzT-hA6qf-pJkQIEJf_GFWfjx_7w-KGMiC49Wdw_nM1SMVcpDSUWSIGA78tqJBvEi2lKgUu4I6IoJBEBxkGybl_i2rWK9C0qTyzdumAI1dHFihSOge4OQuEEGELPXcxDqtMWZX0y4aGUe55F8D7uSn4181L9NfKyX4EKIK2eEzjAwY82iElwm5bj1bVlrAAFIbX0nAwfVZo4aKJ796JuGgXj74tD2_C4fAALDczsrNQU8z1nksE_DxWQMYCSMP_xliy_dzyX7nhj92rLhGWp-ZJ4EbxZz5DQDKMnLvrgf1lGs7iah25qvByIJWR024bo47YNafhHe6ePB-m-NXGkFxsmcqNtn3lCu1uHQvGPLUP-_IaouSe37N1C1ca1_ClFHB6GsxwQ6vZy1w4xfAHFm7av-4uZWGrOR5nHuIm6aAPfOjq2xgSDnoBsZMMtZmHZpNfFBgR2WmHEKXDnzsgqTz8uDyIDwqcHbsPFO_eMLwNEl-BZEAB1SKVejywfX5Lc2-s9Ji8eaUvhMHZdCUMTQiHlyHp9pxLFlnrQNNn2kehufJyRoz2y-emJAR_PVJ-zA8bNLXNl1R3X85MstIGRRZ866nVmLJ83OxRObR-a_lzTUz9sYnEXTlk4bpRDrcUw0F1GyNIef5K8FFe5tFuiqXFlc3RXVU0GOwnm5UyVVL92ORSVeI5IKrHbWIJbndhEIfS5faPPF8WYMxqtiqU39QGO4s2bpwKc2fuAIq2SFy1jHRA1zOCk__eGYRawxGNp1fWFq1SLEB5RmSlUfzYH31gwTVVoxJLeuVFWRMWWfWjlGHGQq8SW1SYvDsJstb8qOlp4qrQxusKMOwTXXYPxYJJhxjfc_Pf6VtfIRbGZ6mipRVOU4JRyFyRfyTfnhVemUifPLIp-7ybgcUiaGut7NqAUXToHjoZq-D7MTV1m05GBRNc8yp1nm6AgoHdZNHoEKumw3kEVYqn1dZ06oUv3grK8Y7vle9z-DBYnNrpiXKVT3fBHgUMEFcYCqFTANmJd7sibHaWEH92ExCmYOMb6B1CVVceNfSILXUkH5Aedj6HElFEULj8BoAGhx0bdaeds0ucf7_Fq4xUoBEAPbJcSGOqHWYa3Vi0HHngRSkKIx2CLVSEkCtcsqhGSryQPv2Sm4286W-DIgj9IelF3L5AJ2yfHuuewS2OqTnJLeNiTMinGH0diYKMkB5wrYRjFdGHS5xMu25Yi-d-8_uO-a3gZ_UREgISkpStSc7pKnK8SlUptDu1BcwfhllKJW5WrMwkIJLKL0_UTBitCJtPNhcpw-5GycXguG9d2BfmqFKkSY8NTfrQa-rQv4MM60Tx7-VhMZf3RlSrtE5Tz3hmLA9JhUChGvph7H0rLlXvtRN7KXLjKL-PFuj8yDZEa9Kf2hoTaiOyjquU4GDvl3ZbvLZ6pZDPUAzd7wkfFlu6stEw6UBLYWF3iTsXR-wZlJCMX7fBaN5ZSQthaxqZJiU5bcEldMu4zKxkUoPXqb2jTDwBBo9zyhV1nr_x7MEqkJK7CrWvgP0edidz9HQ-izXTiwxvzjVz7-vr-xD3It5HnDZQvI5fplvNfUUqDEqbljonuk4z5aM8lKQJ-6s57Y7i8uZi5eyUPtYSxeDe3u85foTwzs94yLsFZR4lnvoIfzzVkoVxaCymhFLIY8izmp0YRXl4gP-6RKK7w4fLgjRAA==',
                                   'id': 'rs_0d4b596545dde303006a687c9d2ca8819e9d430a3abe8c5a66',
                                   'summary': [],
                                   'type': 'reasoning'},
                                  {'content': [{'annotations': [],
                                                'logprobs': [],
                                                'text': '{\n'
                                                        '    "classification": '
                                                        '"Non-Flaky",\n'
                                                        '    "category": '
                                                        '"Non-Flaky",\n'
                                                        '    "reasoning": "The '
                                                        'test uses a mock Dao '
                                                        'and sets an explicit '
                                                        'expectation that '
                                                        'dao.setObjectCache(false) '
                                                        'will throw a '
                                                        'SQLException, then '
                                                        'verifies that '
                                                        'RuntimeExceptionDao '
                                                        'translates that into '
                                                        'a RuntimeException. '
                                                        'All behavior is '
                                                        'driven by the mock '
                                                        'interactions defined '
                                                        'in the test code, '
                                                        'with no timing, '
                                                        'ordering, external '
                                                        'state, or '
                                                        'non-idempotent '
                                                        'operations visible in '
                                                        'the provided '
                                                        'artifact. Therefore '
                                                        'there is no evidence '
                                                        'of flakiness.",\n'
                                                        '    "evidence": [\n'
                                                        '        "Test Code"\n'
                                                        '    ]\n'
                                                        '}',
                                                'type': 'output_text'}],
                                   'id': 'msg_0d4b596545dde303006a687c9ecf88819e8af000ce01ae207a',
                                   'role': 'assistant',
                                   'status': 'completed',
                                   'type': 'message'}],
                       'parallel_tool_calls': True,
                       'presence_penalty': 0.0,
                       'previous_response_id': None,
                       'prompt_cache_key': None,
                       'prompt_cache_retention': 'in_memory',
                       'reasoning': {'context': 'current_turn',
                                     'effort': 'medium',
                                     'mode': 'standard',
                                     'summary': None},
                       'safety_identifier': None,
                       'service_tier': 'default',
                       'status': 'completed',
                       'store': True,
                       'temperature': 1.0,
                       'text': {'format': {'type': 'text'},
                                'verbosity': 'medium'},
                       'tool_choice': 'auto',
                       'tool_usage': {'image_gen': {'input_tokens': 0,
                                                    'input_tokens_details': {'image_tokens': 0,
                                                                             'text_tokens': 0},
                                                    'output_tokens': 0,
                                                    'output_tokens_details': {'image_tokens': 0,
                                                                              'text_tokens': 0},
                                                    'total_tokens': 0},
                                      'web_search': {'num_requests': 0}},
                       'tools': [],
                       'top_logprobs': 0,
                       'top_p': 1.0,
                       'truncation': 'disabled',
                       'usage': {'input_tokens': 498,
                                 'input_tokens_details': {'cache_write_tokens': 0,
                                                          'cached_tokens': 0},
                                 'output_tokens': 380,
                                 'output_tokens_details': {'reasoning_tokens': 192},
                                 'total_tokens': 878},
                       'user': None},
              'request_id': '49464b5f-6aee-4e38-9a29-80df16395794',
              'status_code': 200}}

### 6.6 Parse Batch Responses

Parse the raw OpenAI Batch responses into a standardized intermediate
format.

Each response contains the unique sample identifier (`custom_id`) together
with the model's JSON prediction. This step extracts those predictions while
preserving the sample identifier, enabling them to be merged with the
evaluation dataset in the next step.

Malformed responses (invalid JSON, missing fields, or per-request API
errors) do not stop execution — they are collected and written to a
`malformed_responses.json` file inside the experiment's results folder.

In [19]:
# ============================================================
# Parse Batch Responses
# ============================================================

def extract_response_text(record):
    """
    Extract the model's text output from a single OpenAI Batch response
    record (Responses API shape).
    """

    body = record["response"]["body"]

    text_parts = []

    for item in body.get("output", []):
        if item.get("type") == "message":
            for content_piece in item.get("content", []):
                if content_piece.get("type") in ("output_text", "text"):
                    text_parts.append(content_piece.get("text", ""))

    return "".join(text_parts).strip()


def parse_batch_results(raw_response_file, experiment):
    """
    Parse OpenAI Batch responses into an intermediate format.

    Args:
        raw_response_file (Path): Downloaded OpenAI Batch response file.
        experiment (dict): Experiment configuration.

    Returns:
        list: Parsed predictions.
    """

    parsed_predictions = []
    failed_predictions = []

    with open(raw_response_file, "r", encoding="utf-8") as f:

        for line_no, line in enumerate(f, start=1):

            record = json.loads(line)

            custom_id = record.get("custom_id")

            try:

                sample_id = int(str(custom_id).replace("sample_", ""))

                if record.get("error"):
                    raise ValueError(f"Batch reported error: {record['error']}")

                response_text = extract_response_text(record)

                # Remove markdown fences if present
                if response_text.startswith("```"):
                    response_text = (
                        response_text.replace("```json", "")
                                      .replace("```", "")
                                      .strip()
                    )

                prediction = json.loads(response_text)

                parsed_predictions.append({
                    "id": sample_id,
                    "prediction": prediction
                })

            except (json.JSONDecodeError, ValueError, KeyError, IndexError, TypeError) as e:

                print("=" * 80)
                print(f"JSON parsing failed")
                print(f"Record : {line_no}")
                print(f"Sample : {custom_id}")
                print(f"Error  : {e}")
                print("=" * 80)

                failed_predictions.append({
                    "line": line_no,
                    "sample_id": custom_id,
                    "error": str(e),
                    "raw_response": line,
                })

                # Skip this record and continue
                continue

    print(f"\n✓ Parsed {len(parsed_predictions)} predictions.")

    if failed_predictions:
        print(f"⚠ Skipped {len(failed_predictions)} malformed responses.")

        experiment_dir = get_experiment_directory(experiment)
        failed_file = experiment_dir / "malformed_responses.json"

        with open(failed_file, "w", encoding="utf-8") as fp:
            json.dump(failed_predictions, fp, indent=2)

        print(f"Failed responses saved to {failed_file}")

    return parsed_predictions

In [20]:
parsed_predictions = parse_batch_results(
    raw_response_file,
    experiment
)

parsed_predictions[:2]

✓ Parsed 2210 predictions.

[{'id': 857,
  'prediction': {'classification': 'Non-Flaky',
   'category': 'Non-Flaky',
   'reasoning': 'The test uses a mock Dao and sets an explicit expectation that dao.setObjectCache(false) will throw a SQLException, then verifies that RuntimeExceptionDao translates that into a RuntimeException. All behavior is driven by the mock interactions defined in the test code, with no timing, ordering, external state, or non-idempotent operations visible in the provided artifact. Therefore there is no evidence of flakiness.',
   'evidence': ['Test Code']}},
 {'id': 1574,
  'prediction': {'classification': 'Non-Flaky',
   'category': 'Non-Flaky',
   'reasoning': 'The test provides fixed input and expected output strings to compileAndCheck and contains no sources of nondeterminism: no randomness, timing, asynchronous operations, external resources, or shared mutable state. The single provided artifact (the Test Code) shows a deterministic unit test, so there is insufficient evidence of flakiness.',
   'evidence': ['Test Code']}}]

### 6.7 Merge Predictions with Evaluation Dataset

Merge the parsed model predictions with the evaluation dataset.

This step combines the prediction generated by the model with the
corresponding ground truth labels and metadata using the sample identifier
(`id`).

In [21]:
# ============================================================
# Merge Predictions with Evaluation Dataset
# ============================================================

def merge_predictions(parsed_predictions, df_lookup, experiment):
    """
    Merge parsed OpenAI predictions with the evaluation dataset.
    """

    merged_predictions = []
    skipped = []

    for item in parsed_predictions:

        sample_id = item["id"]
        prediction = item["prediction"]

        # Verify sample exists
        if sample_id not in df_lookup.index:
            print(f"⚠ Sample {sample_id} not found in evaluation dataset.")
            skipped.append(sample_id)
            continue

        sample = df_lookup.loc[sample_id]

        merged_predictions.append({

            "id": sample_id,

            "test_id": sample["test_id"],

            "ground_truth_classification": (
                "Flaky"
                if sample["isFlaky"]
                else "Non-Flaky"
            ),

            "ground_truth_category": sample["issue_category"],

            "predicted_classification": prediction.get("classification"),

            "predicted_category": prediction.get("category"),

            "reasoning": prediction.get("reasoning"),

            "evidence": prediction.get("evidence", []),

            "model": MODEL_NAME,

            "prompt_type": experiment["prompt_type"],

            "context_enabled": experiment["context_enabled"],

            "latency_ms": None

        })

    print(f"✓ Merged {len(merged_predictions)} predictions.")

    if skipped:
        print(f"⚠ Skipped {len(skipped)} predictions (missing sample IDs).")

    return merged_predictions

In [22]:
merged_predictions = merge_predictions(
    parsed_predictions,
    df_lookup,
    experiment
)

merged_predictions[:2]

✓ Merged 2210 predictions.

[{'id': 857,
  'test_id': 'ormlitecore59309e55',
  'ground_truth_classification': 'Flaky',
  'ground_truth_category': 'Order Dependent',
  'predicted_classification': 'Non-Flaky',
  'predicted_category': 'Non-Flaky',
  'reasoning': 'The test uses a mock Dao and sets an explicit expectation that dao.setObjectCache(false) will throw a SQLException, then verifies that RuntimeExceptionDao translates that into a RuntimeException. All behavior is driven by the mock interactions defined in the test code, with no timing, ordering, external state, or non-idempotent operations visible in the provided artifact. Therefore there is no evidence of flakiness.',
  'evidence': ['Test Code'],
  'model': 'gpt-5-mini',
  'prompt_type': 'zero_shot',
  'context_enabled': False,
  'latency_ms': None},
 {'id': 1574,
  'test_id': 'Closure-144-21',
  'ground_truth_classification': 'Non-Flaky',
  'ground_truth_category': 'Non-Flaky',
  'predicted_classification': 'Non-Flaky',
  'predicted_category': 'Non-Flaky',
  'reasoning': 'The test provides fixed input and expected output strings to compileAndCheck and contains no sources of nondeterminism: no randomness, timing, asynchronous operations, external resources, or shared mutable state. The single provided artifact (the Test Code) shows a deterministic unit test, so there is insufficient evidence of flakiness.',
  'evidence': ['Test Code'],
  'model': 'gpt-5-mini',
  'prompt_type': 'zero_shot',
  'context_enabled': False,
  'latency_ms': None}]

### 6.8 Save Predictions

Save the merged prediction records as a JSON Lines (`.jsonl`) file.

The resulting file serves as the standardized input for the evaluation
notebook, where prediction performance is measured using classification
metrics.

In [23]:
# ============================================================
# Save Predictions
# ============================================================

def save_predictions(merged_predictions, experiment):
    """
    Save merged predictions as a JSONL file.

    Args:
        merged_predictions (list): Final prediction records.
        experiment (dict): Experiment configuration.

    Returns:
        Path: Saved prediction file.
    """

    experiment_dir = get_experiment_directory(experiment)

    prediction_file = experiment_dir / "predictions.jsonl"

    with open(prediction_file, "w", encoding="utf-8") as f:

        for prediction in merged_predictions:

            f.write(
                json.dumps(
                    prediction,
                    ensure_ascii=False
                )
            )

            f.write("\n")

    print(f"✓ Saved {len(merged_predictions)} predictions.")
    print(f"Location: {prediction_file}")

    return prediction_file

In [24]:
prediction_file = save_predictions(
    merged_predictions,
    experiment
)

prediction_file

✓ Saved 2210 predictions.
Location: d:\university works\Final-Year_Firts_sem\FYP\INFO\REPO\CA-Classification-Framework\results\gpt-5-mini\zero_shot\without_context\predictions.jsonl

WindowsPath('d:/university works/Final-Year_Firts_sem/FYP/INFO/REPO/CA-Classification-Framework/results/gpt-5-mini/zero_shot/without_context/predictions.jsonl')

### 6.9 Run Experiment (End-to-End)

Combine every step above into a single reusable function so each experiment
can be executed with one call.

In [25]:
# ============================================================
# Run Experiment
# ============================================================

def run_experiment(experiment):

    print("=" * 80)
    print(f"Running: {experiment['name']}")
    print("=" * 80)

    uploaded_file = upload_request_file(
        experiment["request_file"]
    )

    batch_job = create_batch_job(
        uploaded_file
    )

    batch_job = wait_for_batch_completion(
        batch_job
    )

    raw_response_file = download_batch_results(
        batch_job,
        experiment
    )

    parsed_predictions = parse_batch_results(
        raw_response_file,
        experiment
    )

    merged_predictions = merge_predictions(
        parsed_predictions,
        df_lookup,
        experiment
    )

    prediction_file = save_predictions(
        merged_predictions,
        experiment
    )

    print("\n✓ Experiment completed successfully.")

    return prediction_file

### 6.10 Run the Without-Context Experiments

The `without_context` experiments generate smaller request files, so they
are executed directly with `run_experiment`. The larger `with_context`
experiments are executed later using the chunked runner in Section 7.

In [26]:
WITHOUT_CONTEXT_EXPERIMENTS = [
    exp for exp in EXPERIMENTS if not exp["context_enabled"]
]

print(f"Without-context experiments to run: {len(WITHOUT_CONTEXT_EXPERIMENTS)}")
for exp in WITHOUT_CONTEXT_EXPERIMENTS:
    print(f"  • {exp['name']}")

Without-context experiments to run: 3
  • zero_shot_without_context
  • zero_shot_cot_without_context
  • few_shot_cot_without_context

In [27]:
for experiment in WITHOUT_CONTEXT_EXPERIMENTS:
    prediction_file = run_experiment(experiment)

================================================================================
Running: zero_shot_without_context
================================================================================
Uploading: zero_shot_without_context.jsonl
✓ Upload completed
File Id : file-T51KJgu41Gc5PqeSmiRxah
Creating batch job...
✓ Batch job created
Batch Job : batch_6a688b98f1248190b4f331a9bd6a63d4
State     : validating

Waiting for batch job to complete...

16:29:35 | validating | 0/0
16:30:06 | validating | 0/0
16:30:37 | in_progress | 0/2210
16:31:07 | in_progress | 0/2210
16:31:38 | in_progress | 0/2210
16:32:09 | in_progress | 0/2210
16:32:39 | in_progress | 0/2210
16:33:10 | in_progress | 0/2210
16:33:40 | in_progress | 0/2210
16:34:11 | in_progress | 0/2210
16:34:41 | in_progress | 551/2210
16:35:12 | in_progress | 1068/2210
16:35:43 | in_progress | 1931/2210
16:36:13 | finalizing | 2210/2210
16:36:44 | finalizing | 2210/2210
16:37:14 | finalizing | 2210/2210
16:37:45 | finalizing | 2210/2210
16:38:15 | finalizing | 2210/2210
16:38:46 | finalizing | 2210/2210
16:39:16 | completed | 2210/2210

✓ Batch job completed successfully.
Downloading batch results...
✓ Download completed
Saved to: d:\university works\Final-Year_Firts_sem\FYP\INFO\REPO\CA-Classification-Framework\results\gpt-5-mini\zero_shot\without_context\raw_response.jsonl

✓ Parsed 2210 predictions.
✓ Merged 2210 predictions.
✓ Saved 2210 predictions.
Location: d:\university works\Final-Year_Firts_sem\FYP\INFO\REPO\CA-Classification-Framework\results\gpt-5-mini\zero_shot\without_context\predictions.jsonl

✓ Experiment completed successfully.
================================================================================
Running: zero_shot_cot_without_context
================================================================================
Uploading: zero_shot_cot_without_context.jsonl
✓ Upload completed
File Id : file-8pSss45Ps5m8FW4ppzg479
Creating batch job...
✓ Batch job created
Batch Job : batch_6a688de91ac481908e8796efcda8a5a1
State     : validating

Waiting for batch job to complete...

16:39:27 | validating | 0/0
16:39:58 | in_progress | 0/2210
16:40:29 | in_progress | 0/2210
16:40:59 | in_progress | 60/2210
16:41:30 | in_progress | 235/2210
16:42:00 | in_progress | 877/2210
16:42:31 | in_progress | 1682/2210
16:43:01 | in_progress | 2003/2210
16:43:32 | in_progress | 2088/2210
16:44:02 | in_progress | 2135/2210
16:44:33 | in_progress | 2135/2210
16:45:04 | in_progress | 2149/2210
16:45:34 | in_progress | 2196/2210
16:46:05 | in_progress | 2196/2210
16:46:35 | finalizing | 2210/2210
16:47:06 | finalizing | 2210/2210
16:47:36 | finalizing | 2210/2210
16:48:07 | completed | 2210/2210

✓ Batch job completed successfully.
Downloading batch results...
✓ Download completed
Saved to: d:\university works\Final-Year_Firts_sem\FYP\INFO\REPO\CA-Classification-Framework\results\gpt-5-mini\zero_shot_cot\without_context\raw_response.jsonl

✓ Parsed 2210 predictions.
✓ Merged 2210 predictions.
✓ Saved 2210 predictions.
Location: d:\university works\Final-Year_Firts_sem\FYP\INFO\REPO\CA-Classification-Framework\results\gpt-5-mini\zero_shot_cot\without_context\predictions.jsonl

✓ Experiment completed successfully.
================================================================================
Running: few_shot_cot_without_context
================================================================================
Uploading: few_shot_cot_without_context.jsonl
✓ Upload completed
File Id : file-9wFHuCjfFVbKVUcg38UBP6
Creating batch job...
✓ Batch job created
Batch Job : batch_6a688ffd82948190855707a685d931a3
State     : validating

Waiting for batch job to complete...

16:48:20 | validating | 0/0
16:48:50 | in_progress | 0/2210
16:49:21 | in_progress | 73/2210
16:49:51 | in_progress | 905/2210
16:50:22 | in_progress | 1622/2210
16:50:52 | in_progress | 2123/2210
16:51:23 | finalizing | 2210/2210
16:51:53 | finalizing | 2210/2210
16:52:24 | finalizing | 2210/2210
16:52:55 | completed | 2210/2210

✓ Batch job completed successfully.
Downloading batch results...
✓ Download completed
Saved to: d:\university works\Final-Year_Firts_sem\FYP\INFO\REPO\CA-Classification-Framework\results\gpt-5-mini\few_shot_cot\without_context\raw_response.jsonl
================================================================================
JSON parsing failed
Record : 1036
Sample : sample_2035
Error  : Expecting value: line 1 column 1 (char 0)
================================================================================

✓ Parsed 2209 predictions.
⚠ Skipped 1 malformed responses.
Failed responses saved to d:\university works\Final-Year_Firts_sem\FYP\INFO\REPO\CA-Classification-Framework\results\gpt-5-mini\few_shot_cot\without_context\malformed_responses.json
✓ Merged 2209 predictions.
✓ Saved 2209 predictions.
Location: d:\university works\Final-Year_Firts_sem\FYP\INFO\REPO\CA-Classification-Framework\results\gpt-5-mini\few_shot_cot\without_context\predictions.jsonl

✓ Experiment completed successfully.

In [28]:
# List your current batch jobs
for batch in client.batches.list(limit=20):
    print(f"ID: {batch.id}, Status: {batch.status}")

ID: batch_6a688ffd82948190855707a685d931a3, Status: completed
ID: batch_6a688de91ac481908e8796efcda8a5a1, Status: completed
ID: batch_6a688b98f1248190b4f331a9bd6a63d4, Status: completed
ID: batch_6a687aec18a4819084ac7c03dc597357, Status: completed

## 7. Run With-Context Experiments (Chunked)

`with_context` request files are considerably larger than `without_context`
ones because they include helper methods, failure logs, and production code
alongside the test code. Large files risk exceeding OpenAI Batch API limits
(request-count and file-size limits) and take longer to process as a single
job.

This section adds a **chunked runner** used for the three `with_context`
experiments:

1. Split each large request file into smaller JSONL chunks.
2. Run each chunk through the existing upload → create → wait → download →
   parse pipeline, **one chunk at a time**.
3. Combine the parsed predictions from all chunks for an experiment.
4. Reuse the existing `merge_predictions` and `save_predictions` functions
   unchanged, so the final `predictions.jsonl` file is written in the same
   format and location as the `without_context` experiments.

In [49]:
# ============================================================
# Split a Large Request File into Chunks
# ============================================================

def split_request_file(
    request_file: Path,
    max_requests_per_chunk: int = 500,
    max_chunk_bytes: int = 45_000_000,
):
    """
    Split a JSONL batch request file into smaller chunk files.

    Splits by both request count and approximate file bytes to avoid
    OpenAI Batch validation failures on very large with-context prompts.

    Args:
        request_file (Path): Path to the original JSONL request file.
        max_requests_per_chunk (int): Maximum number of requests per chunk.
        max_chunk_bytes (int): Approximate max UTF-8 bytes per chunk file.

    Returns:
        list[Path]: Paths to the generated chunk files.
    """

    lines = request_file.read_text(encoding="utf-8").splitlines()

    chunks = []
    current_chunk = []
    current_bytes = 0

    for line in lines:
        line_bytes = len((line + "\n").encode("utf-8"))

        would_exceed_count = len(current_chunk) >= max_requests_per_chunk
        would_exceed_bytes = current_bytes + line_bytes > max_chunk_bytes

        if current_chunk and (would_exceed_count or would_exceed_bytes):
            chunks.append(current_chunk)
            current_chunk = []
            current_bytes = 0

        current_chunk.append(line)
        current_bytes += line_bytes

    if current_chunk:
        chunks.append(current_chunk)

    chunk_paths = []

    for idx, chunk_lines in enumerate(chunks, start=1):
        chunk_path = request_file.with_name(
            f"{request_file.stem}_chunk{idx}.jsonl"
        )
        chunk_content = "\n".join(chunk_lines) + "\n"
        chunk_path.write_text(chunk_content, encoding="utf-8")
        chunk_paths.append(chunk_path)

    print(f"Split {request_file.name} into {len(chunk_paths)} chunk(s):")
    for p in chunk_paths:
        size_mb = p.stat().st_size / (1024 * 1024)
        print(f"  • {p.name} ({size_mb:.2f} MB)")

    return chunk_paths

### 7.1 Download Helper for Chunked Jobs

The existing `download_batch_results` function always writes to a fixed
`raw_response.jsonl` filename inside the experiment's results folder.
Running several chunks for the same experiment would overwrite that file
each time, so this helper writes each chunk's raw response to its own
numbered file instead.

In [50]:
# ============================================================
# Download Batch Results for a Chunk
# ============================================================

def download_batch_results_chunk(batch_job, experiment, chunk_index):
    """
    Download a completed batch job's results to a chunk-specific file,
    so multiple chunks for the same experiment don't overwrite each other.
    """

    experiment_dir = get_experiment_directory(experiment)

    raw_response_file = experiment_dir / f"raw_response_chunk{chunk_index}.jsonl"

    print(f"Downloading batch results (chunk {chunk_index})...")

    content = client.files.content(batch_job.output_file_id)

    with open(raw_response_file, "wb") as f:
        f.write(content.read())

    print(f"✓ Download completed")
    print(f"Saved to: {raw_response_file}")

    return raw_response_file

### 7.2 Combine Chunk Raw Responses into a Single File

After all chunks for an experiment finish, this concatenates their
individual `raw_response_chunkN.jsonl` files into one `raw_response.jsonl`,
matching the single-file output the `without_context` experiments already
produce.

In [51]:
# ============================================================
# Combine Chunk Raw Responses
# ============================================================

def combine_chunk_raw_responses(experiment, num_chunks=None, raw_files=None):
    """
    Concatenate raw response files into a single raw_response.jsonl.

    Supports two modes:
    1) num_chunks: reads raw_response_chunk{n}.jsonl files (legacy behavior)
    2) raw_files: explicit list of raw response file paths (recommended)
    """

    experiment_dir = get_experiment_directory(experiment)
    combined_file = experiment_dir / "raw_response.jsonl"

    if raw_files is None:
        if num_chunks is None:
            raise ValueError("Provide either num_chunks or raw_files.")
        raw_files = [
            experiment_dir / f"raw_response_chunk{chunk_index}.jsonl"
            for chunk_index in range(1, num_chunks + 1)
        ]

    with open(combined_file, "w", encoding="utf-8") as out_f:
        for raw_file in raw_files:
            with open(raw_file, "r", encoding="utf-8") as in_f:
                out_f.write(in_f.read())

    print(f"✓ Combined {len(raw_files)} chunk file(s) into: {combined_file}")

    return combined_file

### 7.3 Run a With-Context Experiment in Chunks

This function mirrors `run_experiment`, but processes the request file as a
series of smaller batch jobs instead of one large job, combines their raw
responses into a single file, then merges and saves, so the final output
(`raw_response.jsonl` and `predictions.jsonl`) is identical in structure and
naming to the `without_context` experiments.

In [52]:
# ============================================================
# Run a With-Context Experiment (Chunked)
# ============================================================

def run_experiment_with_context(
    experiment,
    max_requests_per_chunk: int = 500,
    max_chunk_bytes: int = 45_000_000,
    min_requests_per_chunk: int = 1,
):

    print("=" * 80)
    print(f"Running (chunked): {experiment['name']}")
    print("=" * 80)

    chunk_files = split_request_file(
        experiment["request_file"],
        max_requests_per_chunk=max_requests_per_chunk,
        max_chunk_bytes=max_chunk_bytes,
    )

    experiment_dir = get_experiment_directory(experiment)
    recovery_log = experiment_dir / "chunk_recovery_log.jsonl"
    successful_raw_files = []

    def _log_recovery_event(payload):
        with open(recovery_log, "a", encoding="utf-8") as fp:
            fp.write(json.dumps(payload, ensure_ascii=False) + "\n")

    def _run_chunk_with_fallback(chunk_path: Path, label: str):
        """
        Run one chunk. If it fails, recursively split into smaller chunks
        until success or single-request failure.
        """

        print("\n" + "-" * 80)
        print(f"Chunk {label}: {chunk_path.name}")
        print("-" * 80)

        try:
            uploaded_file = upload_request_file(chunk_path)
            batch_job = create_batch_job(uploaded_file)
            batch_job = wait_for_batch_completion(batch_job)

            raw_file = experiment_dir / f"raw_response_{label}.jsonl"
            print(f"Downloading batch results ({label})...")
            content = client.files.content(batch_job.output_file_id)
            with open(raw_file, "wb") as f:
                f.write(content.read())

            print(f"✓ Download completed: {raw_file}")
            successful_raw_files.append(raw_file)
            return

        except RuntimeError as error:
            lines = chunk_path.read_text(encoding="utf-8").splitlines()
            n = len(lines)

            _log_recovery_event({
                "experiment": experiment["name"],
                "chunk_label": label,
                "chunk_file": str(chunk_path),
                "requests": n,
                "error": str(error),
            })

            print("\n✗ Chunk failed.")
            print(f"Experiment : {experiment['name']}")
            print(f"Chunk file : {chunk_path}")
            print(f"Requests   : {n}")
            print(error)

            if n <= min_requests_per_chunk:
                # Isolate and skip only this single problematic request.
                skipped_file = experiment_dir / "skipped_requests.jsonl"
                with open(skipped_file, "a", encoding="utf-8") as sf:
                    sf.write(lines[0] + "\n")

                print("⚠ Skipped one irrecoverable request after recursive split.")
                print(f"Logged in: {skipped_file}")
                return

            mid = n // 2
            left_lines = lines[:mid]
            right_lines = lines[mid:]

            left_path = chunk_path.with_name(f"{chunk_path.stem}_{label}a.jsonl")
            right_path = chunk_path.with_name(f"{chunk_path.stem}_{label}b.jsonl")

            left_path.write_text("\n".join(left_lines) + "\n", encoding="utf-8")
            right_path.write_text("\n".join(right_lines) + "\n", encoding="utf-8")

            print(
                f"↻ Retrying by splitting {label} into {label}a ({len(left_lines)} req) "
                f"and {label}b ({len(right_lines)} req)."
            )

            _run_chunk_with_fallback(left_path, f"{label}a")
            _run_chunk_with_fallback(right_path, f"{label}b")

    for chunk_index, chunk_file in enumerate(chunk_files, start=1):
        _run_chunk_with_fallback(chunk_file, f"chunk{chunk_index}")

    if not successful_raw_files:
        raise RuntimeError(
            "All chunks failed; no successful raw responses were produced. "
            "Check chunk_recovery_log.jsonl for details."
        )

    print(f"\n✓ Completed with {len(successful_raw_files)} successful chunk output file(s).")

    combined_raw_file = combine_chunk_raw_responses(
        experiment,
        raw_files=successful_raw_files,
    )

    all_parsed_predictions = parse_batch_results(combined_raw_file, experiment)

    print(f"Total parsed predictions: {len(all_parsed_predictions)}")

    merged_predictions = merge_predictions(
        all_parsed_predictions,
        df_lookup,
        experiment
    )

    prediction_file = save_predictions(
        merged_predictions,
        experiment
    )

    print("\n✓ With-context experiment completed successfully.")

    return prediction_file

### 7.4 Run the Three With-Context Experiments

Only the `context_enabled = True` experiments are run here, since the
`without_context` experiments already completed in Section 6. Each
experiment is run one at a time, with a short buffer pause between them.

In [53]:
WITH_CONTEXT_EXPERIMENTS = [
    exp for exp in EXPERIMENTS if exp["context_enabled"]
]

print(f"With-context experiments to run: {len(WITH_CONTEXT_EXPERIMENTS)}")
for exp in WITH_CONTEXT_EXPERIMENTS:
    print(f"  • {exp['name']}")

With-context experiments to run: 3
  • zero_shot_with_context
  • zero_shot_cot_with_context
  • few_shot_cot_with_context

In [54]:
for experiment in WITH_CONTEXT_EXPERIMENTS:

    try:
        prediction_file = run_experiment_with_context(
            experiment,
            max_requests_per_chunk=500,
            max_chunk_bytes=45_000_000,
            min_requests_per_chunk=1,
        )
        print(f"✓ Completed: {experiment['name']} -> {prediction_file}")
    except RuntimeError as error:
        print("\n" + "=" * 80)
        print(f"✗ Failed experiment: {experiment['name']}")
        print(error)
        print("=" * 80)

    # Buffer pause before the next experiment.
    print("Waiting 60s before starting the next experiment...")
    time.sleep(60)

================================================================================
Running (chunked): zero_shot_with_context
================================================================================
Split zero_shot_with_context.jsonl into 5 chunk(s):
  • zero_shot_with_context_chunk1.jsonl (19.21 MB)
  • zero_shot_with_context_chunk2.jsonl (18.17 MB)
  • zero_shot_with_context_chunk3.jsonl (17.32 MB)
  • zero_shot_with_context_chunk4.jsonl (19.89 MB)
  • zero_shot_with_context_chunk5.jsonl (6.72 MB)

--------------------------------------------------------------------------------
Chunk chunk1: zero_shot_with_context_chunk1.jsonl
--------------------------------------------------------------------------------
Uploading: zero_shot_with_context_chunk1.jsonl
✓ Upload completed
File Id : file-2JF2v2vd1kbaHdGcuYApmE
Creating batch job...
✓ Batch job created
Batch Job : batch_6a68a4c4b3a48190a6c8def84a6ee02f
State     : validating

Waiting for batch job to complete...

18:17:01 | validating | 0/0
18:17:31 | in_progress | 0/500
18:18:02 | in_progress | 0/500
18:18:33 | in_progress | 11/500
18:19:03 | in_progress | 496/500
18:19:34 | finalizing | 500/500
18:20:05 | completed | 500/500

✓ Batch job completed successfully.
Downloading batch results (chunk1)...
✓ Download completed: d:\university works\Final-Year_Firts_sem\FYP\INFO\REPO\CA-Classification-Framework\results\gpt-5-mini\zero_shot\with_context\raw_response_chunk1.jsonl

--------------------------------------------------------------------------------
Chunk chunk2: zero_shot_with_context_chunk2.jsonl
--------------------------------------------------------------------------------
Uploading: zero_shot_with_context_chunk2.jsonl
✓ Upload completed
File Id : file-AXnUJ9TRLv4CynjcgxgCiJ
Creating batch job...
✓ Batch job created
Batch Job : batch_6a68a58889e08190aa908a99c615091d
State     : validating

Waiting for batch job to complete...

18:20:17 | validating | 0/0
18:20:48 | in_progress | 0/500
18:21:18 | in_progress | 0/500
18:21:49 | in_progress | 0/500
18:22:19 | in_progress | 146/500
18:22:50 | in_progress | 332/500
18:23:21 | in_progress | 424/500
18:23:51 | in_progress | 483/500
18:24:22 | in_progress | 497/500
18:24:53 | in_progress | 497/500
18:25:23 | in_progress | 497/500
18:25:54 | in_progress | 497/500
18:26:24 | in_progress | 497/500
18:26:55 | in_progress | 497/500
18:27:26 | in_progress | 497/500
18:27:56 | in_progress | 497/500
18:28:27 | in_progress | 497/500
18:28:57 | in_progress | 497/500
18:29:28 | in_progress | 497/500
18:29:58 | in_progress | 497/500
18:30:29 | in_progress | 497/500
18:30:59 | in_progress | 497/500
18:31:30 | in_progress | 497/500
18:32:00 | in_progress | 497/500
18:32:31 | in_progress | 497/500
18:33:02 | in_progress | 497/500
18:33:32 | in_progress | 497/500
18:34:03 | in_progress | 497/500
18:34:33 | in_progress | 497/500
18:35:04 | in_progress | 497/500
18:35:34 | in_progress | 497/500
18:36:05 | in_progress | 497/500
18:36:35 | in_progress | 497/500
18:37:06 | in_progress | 497/500
18:37:37 | in_progress | 497/500
18:38:07 | in_progress | 497/500
18:38:38 | in_progress | 497/500
18:39:08 | finalizing | 500/500
18:39:39 | completed | 500/500

✓ Batch job completed successfully.
Downloading batch results (chunk2)...
✓ Download completed: d:\university works\Final-Year_Firts_sem\FYP\INFO\REPO\CA-Classification-Framework\results\gpt-5-mini\zero_shot\with_context\raw_response_chunk2.jsonl

--------------------------------------------------------------------------------
Chunk chunk3: zero_shot_with_context_chunk3.jsonl
--------------------------------------------------------------------------------
Uploading: zero_shot_with_context_chunk3.jsonl
✓ Upload completed
File Id : file-Bg4Z1g6akpUX1whgm28Vev
Creating batch job...
✓ Batch job created
Batch Job : batch_6a68aa1cdd308190a9033b11fbbf9296
State     : validating

Waiting for batch job to complete...

18:39:49 | validating | 0/0
18:40:20 | validating | 0/0
18:40:50 | in_progress | 0/500
18:41:21 | in_progress | 0/500
18:41:51 | in_progress | 0/500
18:42:22 | in_progress | 18/500
18:42:53 | in_progress | 310/500
18:43:23 | in_progress | 482/500
18:43:54 | in_progress | 495/500
18:44:24 | in_progress | 495/500
18:44:55 | in_progress | 495/500
18:45:25 | finalizing | 500/500
18:45:56 | completed | 500/500

✓ Batch job completed successfully.
Downloading batch results (chunk3)...
✓ Download completed: d:\university works\Final-Year_Firts_sem\FYP\INFO\REPO\CA-Classification-Framework\results\gpt-5-mini\zero_shot\with_context\raw_response_chunk3.jsonl

--------------------------------------------------------------------------------
Chunk chunk4: zero_shot_with_context_chunk4.jsonl
--------------------------------------------------------------------------------
Uploading: zero_shot_with_context_chunk4.jsonl
✓ Upload completed
File Id : file-T1NwbmgHNsAnz92z36Ty7x
Creating batch job...
✓ Batch job created
Batch Job : batch_6a68ab982a0c81909a6dfb337ba42c57
State     : validating

Waiting for batch job to complete...

18:46:09 | validating | 0/0
18:46:39 | validating | 0/0
18:47:10 | validating | 0/0
18:47:40 | in_progress | 0/500
18:48:11 | in_progress | 7/500
18:48:41 | in_progress | 58/500
18:49:12 | in_progress | 114/500
18:49:42 | in_progress | 184/500
18:50:13 | in_progress | 236/500
18:50:44 | in_progress | 274/500
18:51:14 | in_progress | 321/500
18:51:45 | in_progress | 385/500
18:52:15 | in_progress | 385/500
18:52:46 | in_progress | 385/500
18:53:16 | in_progress | 385/500
18:53:47 | in_progress | 385/500
18:54:18 | in_progress | 412/500
18:54:49 | in_progress | 439/500
18:55:19 | in_progress | 439/500
18:55:50 | in_progress | 469/500
18:56:20 | in_progress | 469/500
18:56:51 | in_progress | 498/500
18:57:21 | in_progress | 498/500
18:57:52 | in_progress | 498/500
18:58:22 | in_progress | 498/500
18:58:53 | in_progress | 498/500
18:59:23 | in_progress | 498/500
18:59:54 | in_progress | 498/500
19:00:25 | in_progress | 498/500
19:00:55 | in_progress | 498/500
19:01:26 | in_progress | 498/500
19:01:57 | in_progress | 498/500
19:02:27 | in_progress | 498/500
19:02:58 | in_progress | 498/500
19:03:28 | in_progress | 498/500
19:03:59 | in_progress | 498/500
19:04:30 | in_progress | 498/500
19:05:00 | in_progress | 498/500
19:05:31 | in_progress | 498/500
19:06:02 | in_progress | 498/500
19:06:32 | in_progress | 498/500
19:07:03 | finalizing | 500/500
19:07:34 | completed | 500/500

✓ Batch job completed successfully.
Downloading batch results (chunk4)...
✓ Download completed: d:\university works\Final-Year_Firts_sem\FYP\INFO\REPO\CA-Classification-Framework\results\gpt-5-mini\zero_shot\with_context\raw_response_chunk4.jsonl

--------------------------------------------------------------------------------
Chunk chunk5: zero_shot_with_context_chunk5.jsonl
--------------------------------------------------------------------------------
Uploading: zero_shot_with_context_chunk5.jsonl
✓ Upload completed
File Id : file-XCk3sui2j3ijK5Hj1gThD3
Creating batch job...
✓ Batch job created
Batch Job : batch_6a68b0a679188190bdba43ca7c0db4de
State     : validating

Waiting for batch job to complete...

19:07:42 | validating | 0/0
19:08:13 | in_progress | 4/210
19:08:44 | in_progress | 17/210
19:09:14 | in_progress | 27/210
19:09:45 | in_progress | 150/210
19:10:16 | in_progress | 150/210
19:10:46 | in_progress | 207/210
19:11:17 | finalizing | 210/210
19:11:48 | completed | 210/210

✓ Batch job completed successfully.
Downloading batch results (chunk5)...
✓ Download completed: d:\university works\Final-Year_Firts_sem\FYP\INFO\REPO\CA-Classification-Framework\results\gpt-5-mini\zero_shot\with_context\raw_response_chunk5.jsonl

✓ Completed with 5 successful chunk output file(s).
✓ Combined 5 chunk file(s) into: d:\university works\Final-Year_Firts_sem\FYP\INFO\REPO\CA-Classification-Framework\results\gpt-5-mini\zero_shot\with_context\raw_response.jsonl
================================================================================
JSON parsing failed
Record : 19
Sample : sample_169
Error  : Unterminated string starting at: line 2 column 23 (char 24)
================================================================================
================================================================================
JSON parsing failed
Record : 47
Sample : sample_968
Error  : Expecting value: line 1 column 1 (char 0)
================================================================================
================================================================================
JSON parsing failed
Record : 51
Sample : sample_1002
Error  : Expecting value: line 1 column 1 (char 0)
================================================================================
================================================================================
JSON parsing failed
Record : 83
Sample : sample_969
Error  : Unterminated string starting at: line 4 column 18 (char 84)
================================================================================
================================================================================
JSON parsing failed
Record : 105
Sample : sample_636
Error  : Expecting value: line 1 column 1 (char 0)
================================================================================
================================================================================
JSON parsing failed
Record : 111
Sample : sample_241
Error  : Unterminated string starting at: line 4 column 18 (char 83)
================================================================================
================================================================================
JSON parsing failed
Record : 141
Sample : sample_2086
Error  : Expecting value: line 1 column 1 (char 0)
================================================================================
================================================================================
JSON parsing failed
Record : 142
Sample : sample_252
Error  : Expecting value: line 1 column 1 (char 0)
================================================================================
================================================================================
JSON parsing failed
Record : 161
Sample : sample_940
Error  : Expecting value: line 1 column 1 (char 0)
================================================================================
================================================================================
JSON parsing failed
Record : 163
Sample : sample_1036
Error  : Unterminated string starting at: line 4 column 18 (char 94)
================================================================================
================================================================================
JSON parsing failed
Record : 196
Sample : sample_729
Error  : Expecting value: line 1 column 1 (char 0)
================================================================================
================================================================================
JSON parsing failed
Record : 216
Sample : sample_1596
Error  : Unterminated string starting at: line 10 column 9 (char 1273)
================================================================================
================================================================================
JSON parsing failed
Record : 255
Sample : sample_70
Error  : Expecting value: line 1 column 1 (char 0)
================================================================================
================================================================================
JSON parsing failed
Record : 271
Sample : sample_649
Error  : Expecting value: line 1 column 1 (char 0)
================================================================================
================================================================================
JSON parsing failed
Record : 336
Sample : sample_600
Error  : Unterminated string starting at: line 13 column 9 (char 1406)
================================================================================
================================================================================
JSON parsing failed
Record : 344
Sample : sample_204
Error  : Expecting property name enclosed in double quotes: line 4 column 608 (char 684)
================================================================================
================================================================================
JSON parsing failed
Record : 359
Sample : sample_2197
Error  : Expecting value: line 1 column 1 (char 0)
================================================================================
================================================================================
JSON parsing failed
Record : 386
Sample : sample_774
Error  : Unterminated string starting at: line 4 column 18 (char 85)
================================================================================
================================================================================
JSON parsing failed
Record : 406
Sample : sample_924
Error  : Unterminated string starting at: line 4 column 18 (char 85)
================================================================================
================================================================================
JSON parsing failed
Record : 407
Sample : sample_1068
Error  : Unterminated string starting at: line 4 column 18 (char 84)
================================================================================
================================================================================
JSON parsing failed
Record : 414
Sample : sample_472
Error  : Expecting value: line 1 column 1 (char 0)
================================================================================
================================================================================
JSON parsing failed
Record : 418
Sample : sample_533
Error  : Expecting value: line 1 column 1 (char 0)
================================================================================
================================================================================
JSON parsing failed
Record : 419
Sample : sample_652
Error  : Unterminated string starting at: line 4 column 18 (char 94)
================================================================================
================================================================================
JSON parsing failed
Record : 429
Sample : sample_589
Error  : Expecting value: line 1 column 1 (char 0)
================================================================================
================================================================================
JSON parsing failed
Record : 464
Sample : sample_479
Error  : Expecting value: line 1 column 1 (char 0)
================================================================================
================================================================================
JSON parsing failed
Record : 478
Sample : sample_2492
Error  : Unterminated string starting at: line 4 column 18 (char 94)
================================================================================
================================================================================
JSON parsing failed
Record : 489
Sample : sample_271
Error  : Expecting value: line 1 column 1 (char 0)
================================================================================
================================================================================
JSON parsing failed
Record : 490
Sample : sample_1041
Error  : Unterminated string starting at: line 4 column 18 (char 84)
================================================================================
================================================================================
JSON parsing failed
Record : 504
Sample : sample_943
Error  : Unterminated string starting at: line 4 column 18 (char 84)
================================================================================
================================================================================
JSON parsing failed
Record : 536
Sample : sample_651
Error  : Unterminated string starting at: line 4 column 18 (char 83)
================================================================================
================================================================================
JSON parsing failed
Record : 544
Sample : sample_731
Error  : Expecting value: line 1 column 1 (char 0)
================================================================================
================================================================================
JSON parsing failed
Record : 555
Sample : sample_767
Error  : Expecting value: line 1 column 1 (char 0)
================================================================================
================================================================================
JSON parsing failed
Record : 563
Sample : sample_31
Error  : Unterminated string starting at: line 12 column 9 (char 1085)
================================================================================
================================================================================
JSON parsing failed
Record : 573
Sample : sample_977
Error  : Unterminated string starting at: line 4 column 18 (char 84)
================================================================================
================================================================================
JSON parsing failed
Record : 579
Sample : sample_1707
Error  : Expecting value: line 1 column 1 (char 0)
================================================================================
================================================================================
JSON parsing failed
Record : 583
Sample : sample_980
Error  : Unterminated string starting at: line 4 column 18 (char 83)
================================================================================
================================================================================
JSON parsing failed
Record : 584
Sample : sample_1350
Error  : Expecting value: line 1 column 1 (char 0)
================================================================================
================================================================================
JSON parsing failed
Record : 593
Sample : sample_2004
Error  : Unterminated string starting at: line 5 column 5 (char 826)
================================================================================
================================================================================
JSON parsing failed
Record : 596
Sample : sample_316
Error  : Unterminated string starting at: line 3 column 5 (char 41)
================================================================================
================================================================================
JSON parsing failed
Record : 598
Sample : sample_454
Error  : Unterminated string starting at: line 14 column 9 (char 1834)
================================================================================
================================================================================
JSON parsing failed
Record : 600
Sample : sample_695
Error  : Expecting value: line 1 column 1 (char 0)
================================================================================
================================================================================
JSON parsing failed
Record : 609
Sample : sample_463
Error  : Unterminated string starting at: line 5 column 5 (char 1250)
================================================================================
================================================================================
JSON parsing failed
Record : 610
Sample : sample_634
Error  : Expecting value: line 1 column 1 (char 0)
================================================================================
================================================================================
JSON parsing failed
Record : 615
Sample : sample_323
Error  : Unterminated string starting at: line 4 column 18 (char 83)

## 8. Recover Malformed Batch Responses

This section retries only records whose original model response was not
valid JSON. It never overwrites `raw_response.jsonl` or `predictions.jsonl`.
Recovery artifacts are written under each experiment's `recovery/` folder,
and a validated combined file is saved as `predictions_recovered.jsonl`.

Run the preparation cell first, then run `run_all_recoveries()` when ready
to submit the small retry batches.

In [55]:
# ============================================================
# Safe recovery of malformed model responses
# ============================================================

RECOVERY_EXPERIMENTS = EXPERIMENTS


def get_recovery_directory(experiment):
    recovery_dir = get_experiment_directory(experiment) / 'recovery'
    recovery_dir.mkdir(parents=True, exist_ok=True)
    return recovery_dir


def get_invalid_response_ids(raw_response_file: Path):
    """Return custom_ids whose OpenAI response text is not a JSON object."""
    invalid_ids = []
    with open(raw_response_file, encoding='utf-8') as f:
        for line_no, line in enumerate(f, start=1):
            record = json.loads(line)
            custom_id = record.get('custom_id')
            try:
                if record.get('error'):
                    raise ValueError(f"Batch reported error: {record['error']}")
                response_text = extract_response_text(record)
                if response_text.startswith('```'):
                    response_text = response_text.replace('```json', '').replace('```', '').strip()
                prediction = json.loads(response_text)
                if not isinstance(prediction, dict):
                    raise ValueError('Prediction is not a JSON object')
            except (KeyError, IndexError, TypeError, ValueError, json.JSONDecodeError) as error:
                invalid_ids.append(custom_id)
                print(f'Invalid response | line={line_no} | id={custom_id} | {error}')
    return invalid_ids


def create_retry_request_file(experiment, overwrite=False):
    """Copy only failed original requests into a new recovery JSONL file."""
    experiment_dir = get_experiment_directory(experiment)
    recovery_dir = get_recovery_directory(experiment)
    retry_request_file = recovery_dir / 'retry_requests.jsonl'
    manifest_file = recovery_dir / 'retry_manifest.json'

    if retry_request_file.exists() and not overwrite:
        if not manifest_file.exists():
            raise FileExistsError(
                f'{retry_request_file} exists but its manifest is missing; refusing to reuse it.'
            )
        with open(manifest_file, encoding='utf-8') as f:
            manifest = json.load(f)
        retry_ids = manifest['sample_ids']
        print(f'{experiment["name"]}: reusing {len(retry_ids)} prepared retry request(s)')
        return retry_request_file, retry_ids

    invalid_ids = get_invalid_response_ids(experiment_dir / 'raw_response.jsonl')
    invalid_id_set = set(invalid_ids)

    original_requests = {}
    with open(experiment['request_file'], encoding='utf-8') as f:
        for line in f:
            request = json.loads(line)
            key = request['custom_id']
            if key in invalid_id_set:
                original_requests[key] = line.rstrip('\n')

    missing_requests = invalid_id_set - set(original_requests)
    if missing_requests:
        raise RuntimeError(f'Failed IDs not found in request file: {sorted(missing_requests)}')

    with open(retry_request_file, 'w', encoding='utf-8') as f:
        for sample_id in invalid_ids:
            f.write(original_requests[sample_id] + '\n')

    manifest = {
        'experiment': experiment['name'],
        'source_raw_response': str(experiment_dir / 'raw_response.jsonl'),
        'retry_request_file': str(retry_request_file),
        'sample_ids': invalid_ids,
    }
    with open(manifest_file, 'w', encoding='utf-8') as f:
        json.dump(manifest, f, indent=2)

    print(f'{experiment["name"]}: prepared {len(invalid_ids)} retry request(s)')
    return retry_request_file, invalid_ids


def download_retry_results(batch_job, experiment, overwrite=False):
    """Download retry output without touching the original raw response file."""
    retry_raw_file = get_recovery_directory(experiment) / 'raw_response_retry.jsonl'
    if retry_raw_file.exists() and not overwrite:
        raise FileExistsError(f'{retry_raw_file} already exists; refusing to overwrite it.')
    if batch_job.output_file_id is None:
        raise RuntimeError('Retry batch job has no output file.')

    content = client.files.content(batch_job.output_file_id)
    with open(retry_raw_file, 'wb') as f:
        f.write(content.read())
    return retry_raw_file


def recover_evaluation_fields(response_text):
    """Safely recover only evaluation fields from malformed model JSON."""
    import re

    def extract_string(field_name):
        match = re.search(rf'\"{field_name}\"\s*:\s*\"([^\"]*)\"', response_text)
        return match.group(1) if match else None

    classification = extract_string('classification')
    category = extract_string('category')
    reasoning_match = re.search(
        r'\"reasoning\"\s*:\s*\"(.*?)\"\s*,\s*\"evidence\"\s*:',
        response_text,
        flags=re.DOTALL,
    )
    reasoning = reasoning_match.group(1) if reasoning_match else response_text

    allowed_categories = {
        'Implementation Dependent', 'Order Dependent', 'Non-Idempotent',
        'Time Dependent', 'Non-Flaky',
    }
    if classification not in {'Flaky', 'Non-Flaky'}:
        raise ValueError(f'Invalid recovered classification: {classification!r}')
    if category not in allowed_categories:
        raise ValueError(f'Invalid recovered category: {category!r}')
    if classification == 'Non-Flaky' and category != 'Non-Flaky':
        raise ValueError('Non-Flaky classification must use Non-Flaky category.')
    if classification == 'Flaky' and category == 'Non-Flaky':
        raise ValueError('Flaky classification cannot use Non-Flaky category.')

    return {
        'classification': classification,
        'category': category,
        'reasoning': reasoning,
        'evidence': [],
    }


def parse_retry_results(retry_raw_file, expected_ids, experiment):
    """Parse retries, retaining validated evaluation fields if only JSON formatting failed."""
    parsed = []
    failures = []
    field_recoveries = []
    expected_id_set = set(expected_ids)
    with open(retry_raw_file, encoding='utf-8') as f:
        for line_no, line in enumerate(f, start=1):
            record = json.loads(line)
            custom_id = record.get('custom_id')
            if custom_id not in expected_id_set:
                continue
            sample_id = int(str(custom_id).replace('sample_', ''))
            try:
                if record.get('error'):
                    raise ValueError(f"Batch reported error: {record['error']}")
                response_text = extract_response_text(record)
                if response_text.startswith('```'):
                    response_text = response_text.replace('```json', '').replace('```', '').strip()
                prediction = json.loads(response_text)
                if not isinstance(prediction, dict):
                    raise ValueError('Prediction is not a JSON object')
                parsed.append({'id': sample_id, 'prediction': prediction})
            except json.JSONDecodeError as error:
                try:
                    prediction = recover_evaluation_fields(response_text)
                    parsed.append({'id': sample_id, 'prediction': prediction})
                    field_recoveries.append({
                        'line': line_no, 'sample_id': sample_id, 'json_error': str(error),
                    })
                except ValueError as recovery_error:
                    failures.append({
                        'line': line_no, 'sample_id': sample_id,
                        'error': f'{error}; field recovery failed: {recovery_error}',
                    })
            except (KeyError, IndexError, TypeError, ValueError) as error:
                failures.append({'line': line_no, 'sample_id': sample_id, 'error': str(error)})

    if field_recoveries:
        audit_file = get_recovery_directory(experiment) / 'retry_field_recoveries.json'
        with open(audit_file, 'w', encoding='utf-8') as f:
            json.dump(field_recoveries, f, indent=2)
        print(f'⚠ Recovered evaluation fields from {len(field_recoveries)} malformed JSON response(s): {audit_file}')

    if failures:
        failure_file = get_recovery_directory(experiment) / 'retry_parse_failures.json'
        with open(failure_file, 'w', encoding='utf-8') as f:
            json.dump(failures, f, indent=2)
        raise RuntimeError(f'Retry produced {len(failures)} malformed response(s); details: {failure_file}')

    parsed_numeric_ids = {item['id'] for item in parsed}
    expected_numeric_ids = {int(str(sid).replace('sample_', '')) for sid in expected_id_set}

    if len(parsed) != len(parsed_numeric_ids):
        raise RuntimeError('Retry output contains duplicate sample IDs.')
    if parsed_numeric_ids != expected_numeric_ids:
        raise RuntimeError(
            f'Retry validation failed. Missing={sorted(expected_numeric_ids - parsed_numeric_ids)}; '
            f'Unexpected={sorted(parsed_numeric_ids - expected_numeric_ids)}'
        )
    return parsed


def write_recovered_predictions(experiment, retry_predictions, expected_ids, overwrite=False):
    """Create a new complete prediction file; leave predictions.jsonl unchanged."""
    experiment_dir = get_experiment_directory(experiment)
    original_file = experiment_dir / 'predictions.jsonl'
    recovered_file = experiment_dir / 'predictions_recovered.jsonl'

    if recovered_file.exists() and not overwrite:
        raise FileExistsError(f'{recovered_file} already exists; refusing to overwrite it.')

    with open(original_file, encoding='utf-8') as f:
        original_predictions = [json.loads(line) for line in f]

    original_ids = {str(item['id']) for item in original_predictions}
    retry_ids = {str(item['id']) for item in retry_predictions}
    expected_numeric_ids = {str(int(str(sid).replace('sample_', ''))) for sid in expected_ids}

    if original_ids & retry_ids:
        raise RuntimeError('Refusing to merge: a retry ID already exists in predictions.jsonl.')
    if retry_ids != expected_numeric_ids:
        raise RuntimeError('Refusing to merge: retry prediction IDs do not match expected IDs.')

    combined = original_predictions + retry_predictions
    combined_ids = [str(item['id']) for item in combined]
    if len(combined_ids) != len(set(combined_ids)):
        raise RuntimeError('Refusing to write duplicate IDs.')
    if len(combined) != len(df_lookup):
        raise RuntimeError(
            f'Refusing to write incomplete recovery: got {len(combined)}, expected {len(df_lookup)}.'
        )

    combined.sort(key=lambda item: int(item['id']))
    with open(recovered_file, 'w', encoding='utf-8') as f:
        for item in combined:
            f.write(json.dumps(item, ensure_ascii=False) + '\n')

    print(f'✓ Wrote validated recovered file: {recovered_file}')
    return recovered_file


def run_recovery(experiment, overwrite=False):
    """Run one small retry batch and produce predictions_recovered.jsonl safely."""
    retry_request_file, expected_ids = create_retry_request_file(experiment, overwrite=overwrite)
    if not expected_ids:
        print(f'{experiment["name"]}: no recovery needed.')
        return None

    retry_raw_file = get_recovery_directory(experiment) / 'raw_response_retry.jsonl'
    if retry_raw_file.exists():
        print(f'{experiment["name"]}: using existing retry response: {retry_raw_file}')
    else:
        # If a fresh retry batch has not been run yet, attempt field recovery
        # directly from the original raw response instead of retrying.
        retry_raw_file = get_experiment_directory(experiment) / 'raw_response.jsonl'
        print(f'{experiment["name"]}: using original raw response for field recovery.')
    parsed_retry = parse_retry_results(retry_raw_file, expected_ids, experiment)
    retry_predictions = merge_predictions(parsed_retry, df_lookup, experiment)
    return write_recovered_predictions(
        experiment, retry_predictions, expected_ids, overwrite=overwrite
    )


def prepare_all_recoveries(overwrite=False):
    return {
        experiment['name']: create_retry_request_file(experiment, overwrite=overwrite)
        for experiment in RECOVERY_EXPERIMENTS
    }


def run_all_recoveries(overwrite=False):
    return {
        experiment['name']: run_recovery(experiment, overwrite=overwrite)
        for experiment in RECOVERY_EXPERIMENTS
    }


# Safe first step: creates only recovery/retry_requests.jsonl and retry_manifest.json.
retry_plan = prepare_all_recoveries()
retry_plan

zero_shot_without_context: prepared 0 retry request(s)
Invalid response | line=19 | id=sample_169 | Unterminated string starting at: line 2 column 23 (char 24)
Invalid response | line=47 | id=sample_968 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=51 | id=sample_1002 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=83 | id=sample_969 | Unterminated string starting at: line 4 column 18 (char 84)
Invalid response | line=105 | id=sample_636 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=111 | id=sample_241 | Unterminated string starting at: line 4 column 18 (char 83)
Invalid response | line=141 | id=sample_2086 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=142 | id=sample_252 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=161 | id=sample_940 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=163 | id=sample_1036 | Unterminated string starting at: line 4 column 18 (char 94)
Invalid response | line=196 | id=sample_729 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=216 | id=sample_1596 | Unterminated string starting at: line 10 column 9 (char 1273)
Invalid response | line=255 | id=sample_70 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=271 | id=sample_649 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=336 | id=sample_600 | Unterminated string starting at: line 13 column 9 (char 1406)
Invalid response | line=344 | id=sample_204 | Expecting property name enclosed in double quotes: line 4 column 608 (char 684)
Invalid response | line=359 | id=sample_2197 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=386 | id=sample_774 | Unterminated string starting at: line 4 column 18 (char 85)
Invalid response | line=406 | id=sample_924 | Unterminated string starting at: line 4 column 18 (char 85)
Invalid response | line=407 | id=sample_1068 | Unterminated string starting at: line 4 column 18 (char 84)
Invalid response | line=414 | id=sample_472 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=418 | id=sample_533 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=419 | id=sample_652 | Unterminated string starting at: line 4 column 18 (char 94)
Invalid response | line=429 | id=sample_589 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=464 | id=sample_479 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=478 | id=sample_2492 | Unterminated string starting at: line 4 column 18 (char 94)
Invalid response | line=489 | id=sample_271 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=490 | id=sample_1041 | Unterminated string starting at: line 4 column 18 (char 84)
Invalid response | line=504 | id=sample_943 | Unterminated string starting at: line 4 column 18 (char 84)
Invalid response | line=536 | id=sample_651 | Unterminated string starting at: line 4 column 18 (char 83)
Invalid response | line=544 | id=sample_731 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=555 | id=sample_767 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=563 | id=sample_31 | Unterminated string starting at: line 12 column 9 (char 1085)
Invalid response | line=573 | id=sample_977 | Unterminated string starting at: line 4 column 18 (char 84)
Invalid response | line=579 | id=sample_1707 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=583 | id=sample_980 | Unterminated string starting at: line 4 column 18 (char 83)
Invalid response | line=584 | id=sample_1350 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=593 | id=sample_2004 | Unterminated string starting at: line 5 column 5 (char 826)
Invalid response | line=596 | id=sample_316 | Unterminated string starting at: line 3 column 5 (char 41)
Invalid response | line=598 | id=sample_454 | Unterminated string starting at: line 14 column 9 (char 1834)
Invalid response | line=600 | id=sample_695 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=609 | id=sample_463 | Unterminated string starting at: line 5 column 5 (char 1250)
Invalid response | line=610 | id=sample_634 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=615 | id=sample_323 | Unterminated string starting at: line 4 column 18 (char 83)
Invalid response | line=643 | id=sample_366 | Unterminated string starting at: line 4 column 18 (char 94)
Invalid response | line=659 | id=sample_989 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=684 | id=sample_272 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=688 | id=sample_1095 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=692 | id=sample_274 | Unterminated string starting at: line 10 column 9 (char 1300)
Invalid response | line=706 | id=sample_992 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=715 | id=sample_929 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=721 | id=sample_273 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=741 | id=sample_712 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=762 | id=sample_592 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=763 | id=sample_1030 | Expecting value: line 10 column 95 (char 1616)
Invalid response | line=778 | id=sample_1043 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=790 | id=sample_714 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=796 | id=sample_482 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=803 | id=sample_1040 | Unterminated string starting at: line 13 column 9 (char 2076)
Invalid response | line=821 | id=sample_1009 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=832 | id=sample_694 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=835 | id=sample_2537 | Unterminated string starting at: line 8 column 9 (char 697)
Invalid response | line=857 | id=sample_630 | Unterminated string starting at: line 5 column 5 (char 1165)
Invalid response | line=928 | id=sample_1001 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=947 | id=sample_469 | Unterminated string starting at: line 4 column 5 (char 81)
Invalid response | line=952 | id=sample_2460 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=982 | id=sample_1810 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=989 | id=sample_982 | Expecting value: line 2 column 22 (char 23)
Invalid response | line=993 | id=sample_644 | Unterminated string starting at: line 11 column 9 (char 1391)
Invalid response | line=999 | id=sample_645 | Unterminated string starting at: line 4 column 18 (char 94)
Invalid response | line=1023 | id=sample_32 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=1037 | id=sample_970 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=1056 | id=sample_386 | Unterminated string starting at: line 10 column 9 (char 1711)
Invalid response | line=1083 | id=sample_1014 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=1089 | id=sample_988 | Unterminated string starting at: line 6 column 9 (char 921)
Invalid response | line=1110 | id=sample_324 | Unterminated string starting at: line 12 column 9 (char 1346)
Invalid response | line=1143 | id=sample_666 | Unterminated string starting at: line 4 column 18 (char 85)
Invalid response | line=1158 | id=sample_2538 | Expecting value: line 2 column 22 (char 23)
Invalid response | line=1163 | id=sample_270 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=1205 | id=sample_848 | Unterminated string starting at: line 14 column 9 (char 1597)
Invalid response | line=1212 | id=sample_647 | Unterminated string starting at: line 4 column 18 (char 94)
Invalid response | line=1222 | id=sample_243 | Unterminated string starting at: line 4 column 18 (char 85)
Invalid response | line=1240 | id=sample_624 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=1269 | id=sample_1037 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=1314 | id=sample_604 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=1323 | id=sample_1952 | Unterminated string starting at: line 4 column 18 (char 94)
Invalid response | line=1357 | id=sample_860 | Unterminated string starting at: line 13 column 9 (char 1358)
Invalid response | line=1377 | id=sample_993 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=1387 | id=sample_250 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=1392 | id=sample_34 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=1399 | id=sample_1 | Unterminated string starting at: line 4 column 18 (char 94)
Invalid response | line=1419 | id=sample_690 | Unterminated string starting at: line 4 column 18 (char 84)
Invalid response | line=1451 | id=sample_461 | Unterminated string starting at: line 4 column 18 (char 94)
Invalid response | line=1453 | id=sample_1121 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=1461 | id=sample_540 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=1472 | id=sample_1461 | Unterminated string starting at: line 4 column 18 (char 83)
Invalid response | line=1475 | id=sample_971 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=1480 | id=sample_974 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=1494 | id=sample_1115 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=1517 | id=sample_1031 | Unterminated string starting at: line 4 column 18 (char 84)
Invalid response | line=1526 | id=sample_654 | Expecting ',' delimiter: line 10 column 196 (char 1444)
Invalid response | line=1536 | id=sample_1635 | Unterminated string starting at: line 6 column 9 (char 851)
Invalid response | line=1549 | id=sample_339 | Unterminated string starting at: line 4 column 18 (char 83)
Invalid response | line=1552 | id=sample_29 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=1571 | id=sample_752 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=1633 | id=sample_981 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=1660 | id=sample_973 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=1683 | id=sample_692 | Unterminated string starting at: line 4 column 18 (char 84)
Invalid response | line=1700 | id=sample_1022 | Unterminated string starting at: line 4 column 18 (char 84)
Invalid response | line=1710 | id=sample_522 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=1734 | id=sample_1000 | Unterminated string starting at: line 11 column 9 (char 1373)
Invalid response | line=1757 | id=sample_635 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=1760 | id=sample_1019 | Unterminated string starting at: line 4 column 18 (char 84)
Invalid response | line=1776 | id=sample_637 | Unterminated string starting at: line 4 column 18 (char 83)
Invalid response | line=1786 | id=sample_995 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=1816 | id=sample_2303 | Unterminated string starting at: line 6 column 9 (char 839)
Invalid response | line=1817 | id=sample_728 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=1853 | id=sample_965 | Unterminated string starting at: line 4 column 18 (char 84)
Invalid response | line=1871 | id=sample_984 | Unterminated string starting at: line 4 column 18 (char 84)
Invalid response | line=1875 | id=sample_996 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=1898 | id=sample_547 | Unterminated string starting at: line 4 column 18 (char 83)
Invalid response | line=1923 | id=sample_1052 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=1931 | id=sample_641 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=1984 | id=sample_1067 | Unterminated string starting at: line 9 column 9 (char 1339)
Invalid response | line=1995 | id=sample_346 | Unterminated string starting at: line 4 column 18 (char 94)
Invalid response | line=2004 | id=sample_473 | Unterminated string starting at: line 4 column 18 (char 85)
Invalid response | line=2029 | id=sample_1393 | Unterminated string starting at: line 4 column 18 (char 83)
Invalid response | line=2062 | id=sample_643 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=2108 | id=sample_1027 | Unterminated string starting at: line 8 column 9 (char 809)
Invalid response | line=2119 | id=sample_1035 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=2145 | id=sample_493 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=2152 | id=sample_1023 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=2164 | id=sample_1028 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=2167 | id=sample_35 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=2168 | id=sample_777 | Unterminated string starting at: line 4 column 18 (char 94)
Invalid response | line=2174 | id=sample_242 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=2186 | id=sample_979 | Expecting value: line 1 column 1 (char 0)
zero_shot_with_context: prepared 137 retry request(s)
zero_shot_cot_without_context: prepared 0 retry request(s)
Invalid response | line=17 | id=sample_2547 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=51 | id=sample_1002 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=72 | id=sample_322 | Unterminated string starting at: line 9 column 9 (char 1145)
Invalid response | line=96 | id=sample_2378 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=105 | id=sample_636 | Unterminated string starting at: line 11 column 9 (char 1852)
Invalid response | line=111 | id=sample_241 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=142 | id=sample_252 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=161 | id=sample_940 | Unterminated string starting at: line 2 column 23 (char 24)
Invalid response | line=163 | id=sample_1036 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=196 | id=sample_729 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=228 | id=sample_895 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=235 | id=sample_1198 | Unterminated string starting at: line 4 column 18 (char 84)
Invalid response | line=247 | id=sample_994 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=252 | id=sample_622 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=255 | id=sample_70 | Expecting ',' delimiter: line 15 column 74 (char 1705)
Invalid response | line=256 | id=sample_638 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=271 | id=sample_649 | Unterminated string starting at: line 4 column 18 (char 94)
Invalid response | line=287 | id=sample_1050 | Unterminated string starting at: line 9 column 9 (char 985)
Invalid response | line=290 | id=sample_632 | Unterminated string starting at: line 9 column 9 (char 1388)
Invalid response | line=298 | id=sample_1534 | Unterminated string starting at: line 4 column 18 (char 83)
Invalid response | line=335 | id=sample_946 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=340 | id=sample_1017 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=344 | id=sample_204 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=363 | id=sample_77 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=406 | id=sample_924 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=418 | id=sample_533 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=419 | id=sample_652 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=435 | id=sample_639 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=438 | id=sample_1351 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=440 | id=sample_1951 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=453 | id=sample_990 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=463 | id=sample_582 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=465 | id=sample_1592 | Unterminated string starting at: line 4 column 18 (char 85)
Invalid response | line=489 | id=sample_271 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=490 | id=sample_1041 | Unterminated string starting at: line 4 column 5 (char 70)
Invalid response | line=504 | id=sample_943 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=509 | id=sample_33 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=516 | id=sample_934 | Unterminated string starting at: line 4 column 18 (char 83)
Invalid response | line=529 | id=sample_484 | Unterminated string starting at: line 8 column 9 (char 1081)
Invalid response | line=536 | id=sample_651 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=544 | id=sample_731 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=555 | id=sample_767 | Unterminated string starting at: line 11 column 9 (char 1459)
Invalid response | line=556 | id=sample_932 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=559 | id=sample_631 | Unterminated string starting at: line 12 column 9 (char 1604)
Invalid response | line=563 | id=sample_31 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=566 | id=sample_945 | Unterminated string starting at: line 15 column 9 (char 1963)
Invalid response | line=593 | id=sample_2004 | Unterminated string starting at: line 4 column 18 (char 83)
Invalid response | line=600 | id=sample_695 | Unterminated string starting at: line 4 column 18 (char 85)
Invalid response | line=609 | id=sample_463 | Unterminated string starting at: line 4 column 5 (char 70)
Invalid response | line=610 | id=sample_634 | Unterminated string starting at: line 4 column 18 (char 85)
Invalid response | line=615 | id=sample_323 | Unterminated string starting at: line 4 column 18 (char 83)
Invalid response | line=648 | id=sample_584 | Expecting value: line 5 column 18 (char 695)
Invalid response | line=658 | id=sample_1094 | Unterminated string starting at: line 4 column 18 (char 84)
Invalid response | line=659 | id=sample_989 | Unterminated string starting at: line 4 column 18 (char 83)
Invalid response | line=674 | id=sample_1025 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=679 | id=sample_1992 | Unterminated string starting at: line 4 column 18 (char 94)
Invalid response | line=684 | id=sample_272 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=688 | id=sample_1095 | Expecting value: line 9 column 131 (char 1339)
Invalid response | line=692 | id=sample_274 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=710 | id=sample_782 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=711 | id=sample_1032 | Unterminated string starting at: line 4 column 18 (char 83)
Invalid response | line=721 | id=sample_273 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=728 | id=sample_594 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=737 | id=sample_983 | Expecting value: line 1 column 1 (char 0)
Invalid response | line=741 | id=sample_712 | Unterminated string starting at: line 4 column 18 (char 94)
Invalid response | line=762 | id=sample_592 | Unterminated string starting at: line 14 column 9 (char 1529)
Invalid response | line=767 | id=sample_944 | Unterminated string starting at: line 9 column 9 (char 1169)

{'zero_shot_without_context': (WindowsPath('d:/university works/Final-Year_Firts_sem/FYP/INFO/REPO/CA-Classification-Framework/results/gpt-5-mini/zero_shot/without_context/recovery/retry_requests.jsonl'),
  []),
 'zero_shot_with_context': (WindowsPath('d:/university works/Final-Year_Firts_sem/FYP/INFO/REPO/CA-Classification-Framework/results/gpt-5-mini/zero_shot/with_context/recovery/retry_requests.jsonl'),
  ['sample_169',
   'sample_968',
   'sample_1002',
   'sample_969',
   'sample_636',
   'sample_241',
   'sample_2086',
   'sample_252',
   'sample_940',
   'sample_1036',
   'sample_729',
   'sample_1596',
   'sample_70',
   'sample_649',
   'sample_600',
   'sample_204',
   'sample_2197',
   'sample_774',
   'sample_924',
   'sample_1068',
   'sample_472',
   'sample_533',
   'sample_652',
   'sample_589',
   'sample_479',
   'sample_2492',
   'sample_271',
   'sample_1041',
   'sample_943',
   'sample_651',
   'sample_731',
   'sample_767',
   'sample_31',
   'sample_977',
   'sample_1707',
   'sample_980',
   'sample_1350',
   'sample_2004',
   'sample_316',
   'sample_454',
   'sample_695',
   'sample_463',
   'sample_634',
   'sample_323',
   'sample_366',
   'sample_989',
   'sample_272',
   'sample_1095',
   'sample_274',
   'sample_992',
   'sample_929',
   'sample_273',
   'sample_712',
   'sample_592',
   'sample_1030',
   'sample_1043',
   'sample_714',
   'sample_482',
   'sample_1040',
   'sample_1009',
   'sample_694',
   'sample_2537',
   'sample_630',
   'sample_1001',
   'sample_469',
   'sample_2460',
   'sample_1810',
   'sample_982',
   'sample_644',
   'sample_645',
   'sample_32',
   'sample_970',
   'sample_386',
   'sample_1014',
   'sample_988',
   'sample_324',
   'sample_666',
   'sample_2538',
   'sample_270',
   'sample_848',
   'sample_647',
   'sample_243',
   'sample_624',
   'sample_1037',
   'sample_604',
   'sample_1952',
   'sample_860',
   'sample_993',
   'sample_250',
   'sample_34',
   'sample_1',
   'sample_690',
   'sample_461',
   'sample_1121',
   'sample_540',
   'sample_1461',
   'sample_971',
   'sample_974',
   'sample_1115',
   'sample_1031',
   'sample_654',
   'sample_1635',
   'sample_339',
   'sample_29',
   'sample_752',
   'sample_981',
   'sample_973',
   'sample_692',
   'sample_1022',
   'sample_522',
   'sample_1000',
   'sample_635',
   'sample_1019',
   'sample_637',
   'sample_995',
   'sample_2303',
   'sample_728',
   'sample_965',
   'sample_984',
   'sample_996',
   'sample_547',
   'sample_1052',
   'sample_641',
   'sample_1067',
   'sample_346',
   'sample_473',
   'sample_1393',
   'sample_643',
   'sample_1027',
   'sample_1035',
   'sample_493',
   'sample_1023',
   'sample_1028',
   'sample_35',
   'sample_777',
   'sample_242',
   'sample_979']),
 'zero_shot_cot_without_context': (WindowsPath('d:/university works/Final-Year_Firts_sem/FYP/INFO/REPO/CA-Classification-Framework/results/gpt-5-mini/zero_shot_cot/without_context/recovery/retry_requests.jsonl'),
  []),
 'zero_shot_cot_with_context': (WindowsPath('d:/university works/Final-Year_Firts_sem/FYP/INFO/REPO/CA-Classification-Framework/results/gpt-5-mini/zero_shot_cot/with_context/recovery/retry_requests.jsonl'),
  ['sample_2547',
   'sample_1002',
   'sample_322',
   'sample_2378',
   'sample_636',
   'sample_241',
   'sample_252',
   'sample_940',
   'sample_1036',
   'sample_729',
   'sample_895',
   'sample_1198',
   'sample_994',
   'sample_622',
   'sample_70',
   'sample_638',
   'sample_649',
   'sample_1050',
   'sample_632',
   'sample_1534',
   'sample_946',
   'sample_1017',
   'sample_204',
   'sample_77',
   'sample_924',
   'sample_533',
   'sample_652',
   'sample_639',
   'sample_1351',
   'sample_1951',
   'sample_990',
   'sample_582',
   'sample_1592',
   'sample_271',
   'sample_1041',
   'sample_943',
   'sample_33',
   'sample_934',
   'sample_484',
   'sample_651',
   'sample_731',
   'sample_767',
   'sample_932',
   'sample_631',
   'sample_31',
   'sample_945',
   'sample_2004',
   'sample_695',
   'sample_463',
   'sample_634',
   'sample_323',
   'sample_584',
   'sample_1094',
   'sample_989',
   'sample_1025',
   'sample_1992',
   'sample_272',
   'sample_1095',
   'sample_274',
   'sample_782',
   'sample_1032',
   'sample_273',
   'sample_594',
   'sample_983',
   'sample_712',
   'sample_592',
   'sample_944',
   'sample_1043',
   'sample_714',
   'sample_1040',
   'sample_1009',
   'sample_694',
   'sample_610',
   'sample_633',
   'sample_593',
   'sample_952',
   'sample_1001',
   'sample_1060',
   'sample_443',
   'sample_982',
   'sample_645',
   'sample_32',
   'sample_342',
   'sample_970',
   'sample_939',
   'sample_986',
   'sample_1014',
   'sample_988',
   'sample_2455',
   'sample_713',
   'sample_953',
   'sample_270',
   'sample_261',
   'sample_532',
   'sample_949',
   'sample_647',
   'sample_1672',
   'sample_229',
   'sample_543',
   'sample_693',
   'sample_1037',
   'sample_640',
   'sample_626',
   'sample_524',
   'sample_250',
   'sample_34',
   'sample_1053',
   'sample_690',
   'sample_1121',
   'sample_962',
   'sample_540',
   'sample_1669',
   'sample_1038',
   'sample_971',
   'sample_974',
   'sample_1815',
   'sample_936',
   'sample_1031',
   'sample_715',
   'sample_1102',
   'sample_29',
   'sample_588',
   'sample_752',
   'sample_1055',
   'sample_192',
   'sample_827',
   'sample_973',
   'sample_90',
   'sample_285',
   'sample_1613',
   'sample_692',
   'sample_1022',
   'sample_2024',
   'sample_442',
   'sample_522',
   'sample_474',
   'sample_791',
   'sample_1282',
   'sample_635',
   'sample_637',
   'sample_2303',
   'sample_728',
   'sample_1388',
   'sample_512',
   'sample_36',
   'sample_923',
   'sample_930',
   'sample_984',
   'sample_996',
   'sample_1076',
   'sample_963',
   'sample_1052',
   'sample_641',
   'sample_960',
   'sample_629',
   'sample_1021',
   'sample_473',
   'sample_609',
   'sample_650',
   'sample_976',
   'sample_964',
   'sample_493',
   'sample_380',
   'sample_1023',
   'sample_1028',
   'sample_35',
   'sample_242',
   'sample_648',
   'sample_22',
   'sample_1671']),
 'few_shot_cot_without_context': (WindowsPath('d:/university works/Final-Year_Firts_sem/FYP/INFO/REPO/CA-Classification-Framework/results/gpt-5-mini/few_shot_cot/without_context/recovery/retry_requests.jsonl'),
  ['sample_2035']),
 'few_shot_cot_with_context': (WindowsPath('d:/university works/Final-Year_Firts_sem/FYP/INFO/REPO/CA-Classification-Framework/results/gpt-5-mini/few_shot_cot/with_context/recovery/retry_requests.jsonl'),
  ['sample_784',
   'sample_1003',
   'sample_757',
   'sample_754',
   'sample_947',
   'sample_933',
   'sample_219',
   'sample_788',
   'sample_614',
   'sample_928',
   'sample_1004',
   'sample_600',
   'sample_997',
   'sample_945',
   'sample_1025',
   'sample_782',
   'sample_1040',
   'sample_1009',
   'sample_1016',
   'sample_776',
   'sample_982',
   'sample_970',
   'sample_939',
   'sample_988',
   'sample_628',
   'sample_949',
   'sample_646',
   'sample_987',
   'sample_764',
   'sample_34',
   'sample_690',
   'sample_927',
   'sample_971',
   'sample_936',
   'sample_950',
   'sample_981',
   'sample_973',
   'sample_961',
   'sample_995',
   'sample_1008',
   'sample_786',
   'sample_965',
   'sample_984',
   'sample_226',
   'sample_473',
   'sample_964',
   'sample_1028'])}

In [59]:
# ============================================================
# Retry only malformed records (no full experiment rerun)
# ============================================================

def parse_retry_results_best_effort(retry_raw_file, expected_ids, experiment):
    """
    Parse retry results but do not fail the entire experiment when some
    records are still malformed.

    Returns:
        tuple[list, list]: (parsed_predictions, unresolved_failures)
    """

    parsed = []
    failures = []
    field_recoveries = []
    expected_id_set = set(expected_ids)

    with open(retry_raw_file, encoding='utf-8') as f:
        for line_no, line in enumerate(f, start=1):
            record = json.loads(line)
            custom_id = record.get('custom_id')
            if custom_id not in expected_id_set:
                continue

            sample_id = int(str(custom_id).replace('sample_', ''))
            response_text = ''

            try:
                if record.get('error'):
                    raise ValueError(f"Batch reported error: {record['error']}")

                response_text = extract_response_text(record)
                if response_text.startswith('```'):
                    response_text = response_text.replace('```json', '').replace('```', '').strip()

                prediction = json.loads(response_text)
                if not isinstance(prediction, dict):
                    raise ValueError('Prediction is not a JSON object')

                parsed.append({'id': sample_id, 'prediction': prediction})

            except json.JSONDecodeError as error:
                try:
                    prediction = recover_evaluation_fields(response_text)
                    parsed.append({'id': sample_id, 'prediction': prediction})
                    field_recoveries.append({
                        'line': line_no,
                        'sample_id': sample_id,
                        'json_error': str(error),
                    })
                except ValueError as recovery_error:
                    failures.append({
                        'line': line_no,
                        'sample_id': sample_id,
                        'error': f'{error}; field recovery failed: {recovery_error}',
                    })

            except (KeyError, IndexError, TypeError, ValueError) as error:
                failures.append({
                    'line': line_no,
                    'sample_id': sample_id,
                    'error': str(error),
                })

    recovery_dir = get_recovery_directory(experiment)

    if field_recoveries:
        audit_file = recovery_dir / 'retry_field_recoveries.json'
        with open(audit_file, 'w', encoding='utf-8') as f:
            json.dump(field_recoveries, f, indent=2)
        print(f'⚠ Recovered evaluation fields from {len(field_recoveries)} malformed JSON response(s): {audit_file}')

    if failures:
        failure_file = recovery_dir / 'retry_parse_failures.json'
        with open(failure_file, 'w', encoding='utf-8') as f:
            json.dump(failures, f, indent=2)
        print(f'⚠ Retry still has {len(failures)} unresolved malformed response(s): {failure_file}')

    parsed_numeric_ids = [item['id'] for item in parsed]
    if len(parsed_numeric_ids) != len(set(parsed_numeric_ids)):
        raise RuntimeError('Retry output contains duplicate sample IDs.')

    return parsed, failures


def write_recovered_predictions_best_effort(
    experiment,
    retry_predictions,
    expected_ids,
    unresolved_failures,
    overwrite=False,
):
    """
    Write recovered predictions without requiring 100% retry success.

    Produces:
        - predictions_recovered_partial.jsonl (always when any recovered rows exist)
        - predictions_recovered.jsonl only if all retry IDs are resolved
    """

    experiment_dir = get_experiment_directory(experiment)
    original_file = experiment_dir / 'predictions.jsonl'
    partial_file = experiment_dir / 'predictions_recovered_partial.jsonl'
    full_file = experiment_dir / 'predictions_recovered.jsonl'

    if partial_file.exists() and not overwrite:
        raise FileExistsError(f'{partial_file} already exists; refusing to overwrite it.')

    with open(original_file, encoding='utf-8') as f:
        original_predictions = [json.loads(line) for line in f]

    original_ids = {str(item['id']) for item in original_predictions}
    retry_ids = {str(item['id']) for item in retry_predictions}

    if original_ids & retry_ids:
        raise RuntimeError('Refusing to merge: a retry ID already exists in predictions.jsonl.')

    combined = original_predictions + retry_predictions
    combined.sort(key=lambda item: int(item['id']))

    with open(partial_file, 'w', encoding='utf-8') as f:
        for item in combined:
            f.write(json.dumps(item, ensure_ascii=False) + '\n')

    expected_numeric_ids = {str(int(str(sid).replace('sample_', ''))) for sid in expected_ids}
    unresolved_ids = {str(item['sample_id']) for item in unresolved_failures}
    resolved_retry_ids = expected_numeric_ids - unresolved_ids

    print(f'✓ Wrote partial recovered file: {partial_file}')
    print(f'  Original rows        : {len(original_predictions)}')
    print(f'  Retry resolved rows  : {len(resolved_retry_ids)}')
    print(f'  Retry unresolved rows: {len(unresolved_ids)}')
    print(f'  Partial total rows   : {len(combined)} / expected {len(df_lookup)}')

    if not unresolved_ids and len(combined) == len(df_lookup):
        with open(full_file, 'w', encoding='utf-8') as f:
            for item in combined:
                f.write(json.dumps(item, ensure_ascii=False) + '\n')
        print(f'✓ Wrote full recovered file: {full_file}')
        return full_file

    unresolved_manifest = experiment_dir / 'recovery' / 'unresolved_retry_ids.json'
    with open(unresolved_manifest, 'w', encoding='utf-8') as f:
        json.dump(sorted(unresolved_ids), f, indent=2)
    print(f'⚠ Full recovery incomplete; unresolved IDs saved to: {unresolved_manifest}')

    return partial_file


def run_recovery(experiment, overwrite=False):
    """
    Retry only malformed records for one experiment and write best-effort
    recovered output.
    """

    retry_request_file, expected_ids = create_retry_request_file(
        experiment,
        overwrite=overwrite,
    )

    if not expected_ids:
        print(f"{experiment['name']}: no recovery needed.")
        return None

    recovery_dir = get_recovery_directory(experiment)
    retry_raw_file = recovery_dir / 'raw_response_retry.jsonl'

    if retry_raw_file.exists() and not overwrite:
        print(f"{experiment['name']}: using existing retry response: {retry_raw_file}")
    else:
        print(f"{experiment['name']}: submitting retry batch with {len(expected_ids)} requests...")

        uploaded_file = upload_request_file(retry_request_file)
        retry_batch_job = create_batch_job(uploaded_file)
        retry_batch_job = wait_for_batch_completion(retry_batch_job)

        retry_raw_file = download_retry_results(
            retry_batch_job,
            experiment,
            overwrite=overwrite,
        )

        print(f"{experiment['name']}: downloaded retry response -> {retry_raw_file}")

    parsed_retry, unresolved_failures = parse_retry_results_best_effort(
        retry_raw_file,
        expected_ids,
        experiment,
    )

    retry_predictions = merge_predictions(
        parsed_retry,
        df_lookup,
        experiment,
    )

    return write_recovered_predictions_best_effort(
        experiment,
        retry_predictions,
        expected_ids,
        unresolved_failures,
        overwrite=overwrite,
    )


def run_only_pending_recoveries(overwrite=False):
    """
    Run recovery only for experiments that have malformed records.
    """

    results = {}

    for experiment in RECOVERY_EXPERIMENTS:
        retry_request_file, expected_ids = create_retry_request_file(
            experiment,
            overwrite=overwrite,
        )

        if not expected_ids:
            print(f"{experiment['name']}: skip (no malformed records).")
            results[experiment['name']] = None
            continue

        print(
            f"{experiment['name']}: pending malformed records = {len(expected_ids)} "
            f"({retry_request_file})"
        )

        results[experiment['name']] = run_recovery(
            experiment,
            overwrite=overwrite,
        )

    return results

In [60]:
run_only_pending_recoveries()

zero_shot_without_context: reusing 0 prepared retry request(s)
zero_shot_without_context: skip (no malformed records).
zero_shot_with_context: reusing 137 prepared retry request(s)
zero_shot_with_context: pending malformed records = 137 (d:\university works\Final-Year_Firts_sem\FYP\INFO\REPO\CA-Classification-Framework\results\gpt-5-mini\zero_shot\with_context\recovery\retry_requests.jsonl)
zero_shot_with_context: reusing 137 prepared retry request(s)
zero_shot_with_context: using existing retry response: d:\university works\Final-Year_Firts_sem\FYP\INFO\REPO\CA-Classification-Framework\results\gpt-5-mini\zero_shot\with_context\recovery\raw_response_retry.jsonl
⚠ Recovered evaluation fields from 25 malformed JSON response(s): d:\university works\Final-Year_Firts_sem\FYP\INFO\REPO\CA-Classification-Framework\results\gpt-5-mini\zero_shot\with_context\recovery\retry_field_recoveries.json
⚠ Retry still has 25 unresolved malformed response(s): d:\university works\Final-Year_Firts_sem\FYP\INFO\REPO\CA-Classification-Framework\results\gpt-5-mini\zero_shot\with_context\recovery\retry_parse_failures.json
✓ Merged 112 predictions.
✓ Wrote partial recovered file: d:\university works\Final-Year_Firts_sem\FYP\INFO\REPO\CA-Classification-Framework\results\gpt-5-mini\zero_shot\with_context\predictions_recovered_partial.jsonl
  Original rows        : 2073
  Retry resolved rows  : 112
  Retry unresolved rows: 25
  Partial total rows   : 2185 / expected 2210
⚠ Full recovery incomplete; unresolved IDs saved to: d:\university works\Final-Year_Firts_sem\FYP\INFO\REPO\CA-Classification-Framework\results\gpt-5-mini\zero_shot\with_context\recovery\unresolved_retry_ids.json
zero_shot_cot_without_context: reusing 0 prepared retry request(s)
zero_shot_cot_without_context: skip (no malformed records).
zero_shot_cot_with_context: reusing 170 prepared retry request(s)
zero_shot_cot_with_context: pending malformed records = 170 (d:\university works\Final-Year_Firts_sem\FYP\INFO\REPO\CA-Classification-Framework\results\gpt-5-mini\zero_shot_cot\with_context\recovery\retry_requests.jsonl)
zero_shot_cot_with_context: reusing 170 prepared retry request(s)
zero_shot_cot_with_context: submitting retry batch with 170 requests...
Uploading: retry_requests.jsonl
✓ Upload completed
File Id : file-6EmTsgFUDJPuGhFLsAVMtE
Creating batch job...
✓ Batch job created
Batch Job : batch_6a68c8d8a3708190a24e131164e0ac3f
State     : validating

Waiting for batch job to complete...

20:50:56 | validating | 0/0
20:51:27 | in_progress | 0/170
20:51:58 | in_progress | 8/170
20:52:28 | in_progress | 37/170
20:52:59 | in_progress | 135/170
20:53:29 | in_progress | 168/170
20:54:00 | completed | 170/170

✓ Batch job completed successfully.
zero_shot_cot_with_context: downloaded retry response -> d:\university works\Final-Year_Firts_sem\FYP\INFO\REPO\CA-Classification-Framework\results\gpt-5-mini\zero_shot_cot\with_context\recovery\raw_response_retry.jsonl
⚠ Recovered evaluation fields from 25 malformed JSON response(s): d:\university works\Final-Year_Firts_sem\FYP\INFO\REPO\CA-Classification-Framework\results\gpt-5-mini\zero_shot_cot\with_context\recovery\retry_field_recoveries.json
⚠ Retry still has 40 unresolved malformed response(s): d:\university works\Final-Year_Firts_sem\FYP\INFO\REPO\CA-Classification-Framework\results\gpt-5-mini\zero_shot_cot\with_context\recovery\retry_parse_failures.json
✓ Merged 130 predictions.
✓ Wrote partial recovered file: d:\university works\Final-Year_Firts_sem\FYP\INFO\REPO\CA-Classification-Framework\results\gpt-5-mini\zero_shot_cot\with_context\predictions_recovered_partial.jsonl
  Original rows        : 2040
  Retry resolved rows  : 130
  Retry unresolved rows: 40
  Partial total rows   : 2170 / expected 2210
⚠ Full recovery incomplete; unresolved IDs saved to: d:\university works\Final-Year_Firts_sem\FYP\INFO\REPO\CA-Classification-Framework\results\gpt-5-mini\zero_shot_cot\with_context\recovery\unresolved_retry_ids.json
few_shot_cot_without_context: reusing 1 prepared retry request(s)
few_shot_cot_without_context: pending malformed records = 1 (d:\university works\Final-Year_Firts_sem\FYP\INFO\REPO\CA-Classification-Framework\results\gpt-5-mini\few_shot_cot\without_context\recovery\retry_requests.jsonl)
few_shot_cot_without_context: reusing 1 prepared retry request(s)
few_shot_cot_without_context: submitting retry batch with 1 requests...
Uploading: retry_requests.jsonl
✓ Upload completed
File Id : file-MAAkFgTmhHQTFApAEwQbzq
Creating batch job...
✓ Batch job created
Batch Job : batch_6a68c9949c488190b0e1a091e788a284
State     : validating

Waiting for batch job to complete...

20:54:04 | validating | 0/0
20:54:35 | in_progress | 0/1
20:55:05 | completed | 1/1

✓ Batch job completed successfully.
few_shot_cot_without_context: downloaded retry response -> d:\university works\Final-Year_Firts_sem\FYP\INFO\REPO\CA-Classification-Framework\results\gpt-5-mini\few_shot_cot\without_context\recovery\raw_response_retry.jsonl
✓ Merged 1 predictions.
✓ Wrote partial recovered file: d:\university works\Final-Year_Firts_sem\FYP\INFO\REPO\CA-Classification-Framework\results\gpt-5-mini\few_shot_cot\without_context\predictions_recovered_partial.jsonl
  Original rows        : 2209
  Retry resolved rows  : 1
  Retry unresolved rows: 0
  Partial total rows   : 2210 / expected 2210
✓ Wrote full recovered file: d:\university works\Final-Year_Firts_sem\FYP\INFO\REPO\CA-Classification-Framework\results\gpt-5-mini\few_shot_cot\without_context\predictions_recovered.jsonl
few_shot_cot_with_context: reusing 47 prepared retry request(s)
few_shot_cot_with_context: pending malformed records = 47 (d:\university works\Final-Year_Firts_sem\FYP\INFO\REPO\CA-Classification-Framework\results\gpt-5-mini\few_shot_cot\with_context\recovery\retry_requests.jsonl)
few_shot_cot_with_context: reusing 47 prepared retry request(s)
few_shot_cot_with_context: submitting retry batch with 47 requests...
Uploading: retry_requests.jsonl
✓ Upload completed
File Id : file-Q92TTtTfva3Hq5angdMxPS
Creating batch job...
✓ Batch job created
Batch Job : batch_6a68c9d6491c819092847ffb06ed898e
State     : validating

Waiting for batch job to complete...

20:55:10 | validating | 0/0
20:55:41 | in_progress | 0/47
20:56:11 | in_progress | 0/47
20:56:42 | in_progress | 17/47
20:57:12 | in_progress | 43/47
20:57:43 | in_progress | 43/47
20:58:13 | in_progress | 43/47
20:58:44 | completed | 47/47

✓ Batch job completed successfully.
few_shot_cot_with_context: downloaded retry response -> d:\university works\Final-Year_Firts_sem\FYP\INFO\REPO\CA-Classification-Framework\results\gpt-5-mini\few_shot_cot\with_context\recovery\raw_response_retry.jsonl
⚠ Recovered evaluation fields from 5 malformed JSON response(s): d:\university works\Final-Year_Firts_sem\FYP\INFO\REPO\CA-Classification-Framework\results\gpt-5-mini\few_shot_cot\with_context\recovery\retry_field_recoveries.json
⚠ Retry still has 3 unresolved malformed response(s): d:\university works\Final-Year_Firts_sem\FYP\INFO\REPO\CA-Classification-Framework\results\gpt-5-mini\few_shot_cot\with_context\recovery\retry_parse_failures.json
✓ Merged 44 predictions.
✓ Wrote partial recovered file: d:\university works\Final-Year_Firts_sem\FYP\INFO\REPO\CA-Classification-Framework\results\gpt-5-mini\few_shot_cot\with_context\predictions_recovered_partial.jsonl
  Original rows        : 2163
  Retry resolved rows  : 44
  Retry unresolved rows: 3
  Partial total rows   : 2207 / expected 2210
⚠ Full recovery incomplete; unresolved IDs saved to: d:\university works\Final-Year_Firts_sem\FYP\INFO\REPO\CA-Classification-Framework\results\gpt-5-mini\few_shot_cot\with_context\recovery\unresolved_retry_ids.json

{'zero_shot_without_context': None,
 'zero_shot_with_context': WindowsPath('d:/university works/Final-Year_Firts_sem/FYP/INFO/REPO/CA-Classification-Framework/results/gpt-5-mini/zero_shot/with_context/predictions_recovered_partial.jsonl'),
 'zero_shot_cot_without_context': None,
 'zero_shot_cot_with_context': WindowsPath('d:/university works/Final-Year_Firts_sem/FYP/INFO/REPO/CA-Classification-Framework/results/gpt-5-mini/zero_shot_cot/with_context/predictions_recovered_partial.jsonl'),
 'few_shot_cot_without_context': WindowsPath('d:/university works/Final-Year_Firts_sem/FYP/INFO/REPO/CA-Classification-Framework/results/gpt-5-mini/few_shot_cot/without_context/predictions_recovered.jsonl'),
 'few_shot_cot_with_context': WindowsPath('d:/university works/Final-Year_Firts_sem/FYP/INFO/REPO/CA-Classification-Framework/results/gpt-5-mini/few_shot_cot/with_context/predictions_recovered_partial.jsonl')}

In [70]:
# ============================================================
# Verify Output Files (post-run quality check)
# ============================================================

from pathlib import Path


def _count_jsonl_rows(path: Path) -> int:
    if not path.exists():
        return 0
    with open(path, "r", encoding="utf-8") as f:
        return sum(1 for _ in f)


def _load_json_list(path: Path):
    if not path.exists():
        return []
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


expected_total = len(df_lookup)
rows = []

for experiment in EXPERIMENTS:
    experiment_dir = get_experiment_directory(experiment)
    recovery_dir = experiment_dir / "recovery"

    predictions_file = experiment_dir / "predictions.jsonl"
    recovered_full_file = experiment_dir / "predictions_recovered.jsonl"
    recovered_partial_file = experiment_dir / "predictions_recovered_partial.jsonl"

    malformed_file = experiment_dir / "malformed_responses.json"
    retry_manifest_file = recovery_dir / "retry_manifest.json"
    retry_failure_file = recovery_dir / "retry_parse_failures.json"
    unresolved_ids_file = recovery_dir / "unresolved_retry_ids.json"

    base_rows = _count_jsonl_rows(predictions_file)
    full_rows = _count_jsonl_rows(recovered_full_file)
    partial_rows = _count_jsonl_rows(recovered_partial_file)

    malformed_count = len(_load_json_list(malformed_file))
    retry_manifest = _load_json_list(retry_manifest_file) if retry_manifest_file.exists() else {}
    retry_expected = len(retry_manifest.get("sample_ids", [])) if isinstance(retry_manifest, dict) else 0
    retry_unresolved = len(_load_json_list(unresolved_ids_file))
    retry_failures = len(_load_json_list(retry_failure_file))

    if recovered_full_file.exists():
        status = "FULL_RECOVERED"
        final_rows = full_rows
        missing_after_recovery = max(expected_total - full_rows, 0)
    elif recovered_partial_file.exists():
        status = "PARTIAL_RECOVERED"
        final_rows = partial_rows
        missing_after_recovery = max(expected_total - partial_rows, 0)
    elif predictions_file.exists():
        status = "BASE_ONLY"
        final_rows = base_rows
        missing_after_recovery = max(expected_total - base_rows, 0)
    else:
        status = "MISSING_OUTPUT"
        final_rows = 0
        missing_after_recovery = expected_total

    rows.append({
        "experiment": experiment["name"],
        "prompt_type": experiment["prompt_type"],
        "context_enabled": experiment["context_enabled"],
        "status": status,
        "expected_rows": expected_total,
        "base_rows": base_rows,
        "final_rows": final_rows,
        "missing_after_recovery": missing_after_recovery,
        "malformed_initial": malformed_count,
        "retry_expected": retry_expected,
        "retry_failures_logged": retry_failures,
        "retry_unresolved_ids": retry_unresolved,
        "predictions_file": str(predictions_file),
        "recovered_full_file": str(recovered_full_file),
        "recovered_partial_file": str(recovered_partial_file),
    })

summary_df = pd.DataFrame(rows)

print("\n=== Output Verification Summary ===")
print(f"Expected rows per experiment: {expected_total}")
print(f"Experiments checked: {len(summary_df)}\n")

display_cols = [
    "experiment",
    "status",
    "base_rows",
    "final_rows",
    "expected_rows",
    "missing_after_recovery",
    "malformed_initial",
    "retry_expected",
    "retry_unresolved_ids",
]

summary_df[display_cols]

=== Output Verification Summary ===
Expected rows per experiment: 2210
Experiments checked: 6

,experiment,status,base_rows,final_rows,expected_rows,missing_after_recovery,malformed_initial,retry_expected,retry_unresolved_ids
0,zero_shot_without_context,BASE_ONLY,2210,2210,2210,0,0,0,0
1,zero_shot_with_context,FULL_RECOVERED,2073,2210,2210,0,137,137,0
2,zero_shot_cot_without_context,BASE_ONLY,2210,2210,2210,0,0,0,0
3,zero_shot_cot_with_context,FULL_RECOVERED,2040,2210,2210,0,170,170,0
4,few_shot_cot_without_context,FULL_RECOVERED,2209,2210,2210,0,1,1,0
5,few_shot_cot_with_context,FULL_RECOVERED,2163,2210,2210,0,47,47,0

In [62]:
# ============================================================
# Final pass: resolve unresolved IDs only (strict JSON retries)
# ============================================================

STRICT_RECOVERY_SUFFIX = (
    "\n\nIMPORTANT OUTPUT RULES:\n"
    "- Return ONLY one valid JSON object.\n"
    "- Do NOT use markdown fences.\n"
    "- Keys required: classification, category, reasoning, evidence.\n"
    "- classification must be exactly 'Flaky' or 'Non-Flaky'.\n"
    "- category must be one of: Implementation Dependent, Order Dependent, "
    "Non-Idempotent, Time Dependent, Non-Flaky.\n"
    "- If classification is 'Non-Flaky', category must be 'Non-Flaky'.\n"
    "- If classification is 'Flaky', category must NOT be 'Non-Flaky'.\n"
    "- evidence must be a JSON array of strings (empty array allowed).\n"
)


def _load_unresolved_custom_ids(experiment):
    """Return unresolved IDs as custom_id format: sample_<id>."""
    unresolved_file = get_recovery_directory(experiment) / "unresolved_retry_ids.json"
    if not unresolved_file.exists():
        return []

    with open(unresolved_file, "r", encoding="utf-8") as f:
        unresolved = json.load(f)

    custom_ids = []
    for item in unresolved:
        text = str(item)
        custom_ids.append(text if text.startswith("sample_") else f"sample_{text}")

    return custom_ids


def _build_strict_retry_request_file(experiment, custom_ids, pass_no):
    """Create a strict retry request file for unresolved custom IDs only."""
    recovery_dir = get_recovery_directory(experiment)
    retry_file = recovery_dir / f"retry_requests_pass{pass_no}.jsonl"

    wanted = set(custom_ids)
    selected = []

    with open(experiment["request_file"], "r", encoding="utf-8") as f:
        for line in f:
            req = json.loads(line)
            cid = req.get("custom_id")
            if cid not in wanted:
                continue

            body = req.get("body", {})
            original_input = body.get("input", "")
            body["input"] = f"{original_input}{STRICT_RECOVERY_SUFFIX}"
            req["body"] = body
            selected.append(req)

    found = {r["custom_id"] for r in selected}
    missing = sorted(wanted - found)
    if missing:
        raise RuntimeError(
            f"{experiment['name']}: unresolved IDs missing in source request file: {missing[:10]}"
        )

    with open(retry_file, "w", encoding="utf-8") as f:
        for record in selected:
            f.write(json.dumps(record, ensure_ascii=False) + "\n")

    print(f"{experiment['name']}: strict retry file created ({len(selected)} IDs) -> {retry_file}")
    return retry_file


def _read_prediction_rows(path):
    with open(path, "r", encoding="utf-8") as f:
        return [json.loads(line) for line in f]


def _write_prediction_rows(path, rows):
    with open(path, "w", encoding="utf-8") as f:
        for row in rows:
            f.write(json.dumps(row, ensure_ascii=False) + "\n")


def _merge_strict_pass_predictions(experiment, new_retry_predictions, expected_custom_ids, unresolved_failures):
    """Merge strict-pass results into partial/full recovered outputs."""
    experiment_dir = get_experiment_directory(experiment)
    recovery_dir = get_recovery_directory(experiment)

    original_file = experiment_dir / "predictions.jsonl"
    partial_file = experiment_dir / "predictions_recovered_partial.jsonl"
    full_file = experiment_dir / "predictions_recovered.jsonl"

    base_file = partial_file if partial_file.exists() else original_file
    base_rows = _read_prediction_rows(base_file)

    base_ids = {str(row["id"]) for row in base_rows}
    new_ids = {str(row["id"]) for row in new_retry_predictions}

    overlap = sorted(base_ids & new_ids)
    if overlap:
        raise RuntimeError(
            f"{experiment['name']}: strict pass produced IDs already present in base file: {overlap[:10]}"
        )

    combined = base_rows + new_retry_predictions
    combined.sort(key=lambda item: int(item["id"]))

    expected_numeric = {
        str(int(str(cid).replace("sample_", "")))
        for cid in expected_custom_ids
    }
    resolved_numeric = {
        str(row["id"]) for row in new_retry_predictions
    }

    unresolved_from_failures = {
        str(item["sample_id"]) for item in unresolved_failures
    }

    # Catch any expected ID that neither resolved nor appeared in failures.
    unresolved_numeric = (expected_numeric - resolved_numeric) | unresolved_from_failures

    _write_prediction_rows(partial_file, combined)

    unresolved_file = recovery_dir / "unresolved_retry_ids.json"
    with open(unresolved_file, "w", encoding="utf-8") as f:
        json.dump(sorted(unresolved_numeric), f, indent=2)

    if not unresolved_numeric and len(combined) == len(df_lookup):
        _write_prediction_rows(full_file, combined)
        print(f"✓ {experiment['name']}: FULL_RECOVERED -> {full_file}")
    else:
        print(
            f"⚠ {experiment['name']}: still unresolved={len(unresolved_numeric)} | "
            f"rows={len(combined)}/{len(df_lookup)}"
        )

    return {
        "rows": len(combined),
        "expected": len(df_lookup),
        "unresolved": len(unresolved_numeric),
        "partial_file": str(partial_file),
        "full_file": str(full_file),
    }


def run_strict_unresolved_pass(experiment, pass_no=2):
    """Run one strict retry pass for unresolved IDs of a single experiment."""
    custom_ids = _load_unresolved_custom_ids(experiment)
    if not custom_ids:
        print(f"{experiment['name']}: no unresolved IDs. Nothing to do.")
        return {
            "status": "no_unresolved",
            "unresolved_before": 0,
            "unresolved_after": 0,
        }

    retry_file = _build_strict_retry_request_file(experiment, custom_ids, pass_no=pass_no)

    uploaded_file = upload_request_file(retry_file)
    retry_batch_job = create_batch_job(uploaded_file)
    retry_batch_job = wait_for_batch_completion(retry_batch_job)

    recovery_dir = get_recovery_directory(experiment)
    strict_raw_file = recovery_dir / f"raw_response_retry_pass{pass_no}.jsonl"

    content = client.files.content(retry_batch_job.output_file_id)
    with open(strict_raw_file, "wb") as f:
        f.write(content.read())

    parsed_retry, unresolved_failures = parse_retry_results_best_effort(
        strict_raw_file,
        custom_ids,
        experiment,
    )

    retry_predictions = merge_predictions(parsed_retry, df_lookup, experiment)

    merge_info = _merge_strict_pass_predictions(
        experiment,
        retry_predictions,
        custom_ids,
        unresolved_failures,
    )

    return {
        "status": "done",
        "unresolved_before": len(custom_ids),
        "unresolved_after": merge_info["unresolved"],
        **merge_info,
    }


def run_strict_until_full(max_passes=3):
    """
    Re-run unresolved IDs only, up to max_passes.
    Stops early per experiment once unresolved count reaches zero.
    """
    target_experiments = [exp for exp in EXPERIMENTS if exp["context_enabled"]]
    report = {}

    for experiment in target_experiments:
        name = experiment["name"]
        report[name] = []

        for pass_no in range(2, max_passes + 2):
            before_ids = _load_unresolved_custom_ids(experiment)
            if not before_ids:
                report[name].append(
                    {
                        "pass": pass_no,
                        "status": "already_full",
                        "unresolved_before": 0,
                        "unresolved_after": 0,
                    }
                )
                break

            print("\n" + "=" * 90)
            print(f"{name} | strict pass {pass_no} | unresolved before: {len(before_ids)}")
            print("=" * 90)

            result = run_strict_unresolved_pass(experiment, pass_no=pass_no)
            result["pass"] = pass_no
            report[name].append(result)

            # Stop if no improvement to avoid paying repeatedly for same failures.
            if result.get("unresolved_after", 0) >= result.get("unresolved_before", 0):
                print(
                    f"{name}: no improvement on pass {pass_no}. "
                    "Stopping further strict retries for this experiment."
                )
                break

            if result.get("unresolved_after", 0) == 0:
                break

    return report


# Run this when ready:
# strict_report = run_strict_until_full(max_passes=3)
# strict_report

In [63]:
run_strict_until_full(max_passes=3)

==========================================================================================
zero_shot_with_context | strict pass 2 | unresolved before: 25
==========================================================================================
zero_shot_with_context: strict retry file created (25 IDs) -> d:\university works\Final-Year_Firts_sem\FYP\INFO\REPO\CA-Classification-Framework\results\gpt-5-mini\zero_shot\with_context\recovery\retry_requests_pass2.jsonl
Uploading: retry_requests_pass2.jsonl
✓ Upload completed
File Id : file-CLxMsx171u8E6adrHhzR6y
Creating batch job...
✓ Batch job created
Batch Job : batch_6a68cc32a3688190832571ba47ff2f74
State     : validating

Waiting for batch job to complete...

21:05:14 | validating | 0/0
21:05:45 | in_progress | 0/25
21:06:16 | in_progress | 0/25
21:06:46 | in_progress | 0/25
21:07:17 | in_progress | 21/25
21:07:47 | completed | 25/25

✓ Batch job completed successfully.
⚠ Recovered evaluation fields from 3 malformed JSON response(s): d:\university works\Final-Year_Firts_sem\FYP\INFO\REPO\CA-Classification-Framework\results\gpt-5-mini\zero_shot\with_context\recovery\retry_field_recoveries.json
⚠ Retry still has 13 unresolved malformed response(s): d:\university works\Final-Year_Firts_sem\FYP\INFO\REPO\CA-Classification-Framework\results\gpt-5-mini\zero_shot\with_context\recovery\retry_parse_failures.json
✓ Merged 12 predictions.
⚠ zero_shot_with_context: still unresolved=13 | rows=2197/2210

==========================================================================================
zero_shot_with_context | strict pass 3 | unresolved before: 13
==========================================================================================
zero_shot_with_context: strict retry file created (13 IDs) -> d:\university works\Final-Year_Firts_sem\FYP\INFO\REPO\CA-Classification-Framework\results\gpt-5-mini\zero_shot\with_context\recovery\retry_requests_pass3.jsonl
Uploading: retry_requests_pass3.jsonl
✓ Upload completed
File Id : file-Ba3f7U2YFzgcoSMfHeFkkK
Creating batch job...
✓ Batch job created
Batch Job : batch_6a68ccd1dd808190b971d80ef8efec21
State     : validating

Waiting for batch job to complete...

21:07:54 | validating | 0/0
21:08:24 | validating | 0/0
21:08:55 | in_progress | 0/13
21:09:26 | in_progress | 6/13
21:09:56 | in_progress | 6/13
21:10:27 | in_progress | 6/13
21:10:57 | completed | 13/13

✓ Batch job completed successfully.
⚠ Recovered evaluation fields from 2 malformed JSON response(s): d:\university works\Final-Year_Firts_sem\FYP\INFO\REPO\CA-Classification-Framework\results\gpt-5-mini\zero_shot\with_context\recovery\retry_field_recoveries.json
⚠ Retry still has 10 unresolved malformed response(s): d:\university works\Final-Year_Firts_sem\FYP\INFO\REPO\CA-Classification-Framework\results\gpt-5-mini\zero_shot\with_context\recovery\retry_parse_failures.json
✓ Merged 3 predictions.
⚠ zero_shot_with_context: still unresolved=10 | rows=2200/2210

==========================================================================================
zero_shot_with_context | strict pass 4 | unresolved before: 10
==========================================================================================
zero_shot_with_context: strict retry file created (10 IDs) -> d:\university works\Final-Year_Firts_sem\FYP\INFO\REPO\CA-Classification-Framework\results\gpt-5-mini\zero_shot\with_context\recovery\retry_requests_pass4.jsonl
Uploading: retry_requests_pass4.jsonl
✓ Upload completed
File Id : file-3GwPfMaRjJhmnMq14TRxDy
Creating batch job...
✓ Batch job created
Batch Job : batch_6a68cd8d725c819087e30418ae9a9aac
State     : validating

Waiting for batch job to complete...

21:11:01 | validating | 0/0
21:11:32 | in_progress | 0/10
21:12:02 | in_progress | 0/10
21:12:33 | in_progress | 0/10
21:13:03 | in_progress | 0/10
21:13:34 | in_progress | 0/10
21:14:05 | completed | 10/10

✓ Batch job completed successfully.
⚠ Recovered evaluation fields from 1 malformed JSON response(s): d:\university works\Final-Year_Firts_sem\FYP\INFO\REPO\CA-Classification-Framework\results\gpt-5-mini\zero_shot\with_context\recovery\retry_field_recoveries.json
⚠ Retry still has 9 unresolved malformed response(s): d:\university works\Final-Year_Firts_sem\FYP\INFO\REPO\CA-Classification-Framework\results\gpt-5-mini\zero_shot\with_context\recovery\retry_parse_failures.json
✓ Merged 1 predictions.
⚠ zero_shot_with_context: still unresolved=9 | rows=2201/2210

==========================================================================================
zero_shot_cot_with_context | strict pass 2 | unresolved before: 40
==========================================================================================
zero_shot_cot_with_context: strict retry file created (40 IDs) -> d:\university works\Final-Year_Firts_sem\FYP\INFO\REPO\CA-Classification-Framework\results\gpt-5-mini\zero_shot_cot\with_context\recovery\retry_requests_pass2.jsonl
Uploading: retry_requests_pass2.jsonl
✓ Upload completed
File Id : file-42mSLFdN6gNzve9QDuGudi
Creating batch job...
✓ Batch job created
Batch Job : batch_6a68ce49e4d881909bc3ef19a3cdddeb
State     : validating

Waiting for batch job to complete...

21:14:10 | validating | 0/0
21:14:40 | in_progress | 0/40
21:15:11 | in_progress | 0/40
21:15:41 | in_progress | 0/40
21:16:12 | in_progress | 11/40
21:16:43 | in_progress | 11/40
21:17:13 | in_progress | 37/40
21:17:44 | in_progress | 37/40
21:18:14 | in_progress | 37/40
21:18:45 | in_progress | 37/40
21:19:15 | in_progress | 37/40
21:19:46 | in_progress | 37/40
21:20:16 | in_progress | 37/40
21:20:47 | completed | 40/40

✓ Batch job completed successfully.
⚠ Recovered evaluation fields from 6 malformed JSON response(s): d:\university works\Final-Year_Firts_sem\FYP\INFO\REPO\CA-Classification-Framework\results\gpt-5-mini\zero_shot_cot\with_context\recovery\retry_field_recoveries.json
⚠ Retry still has 21 unresolved malformed response(s): d:\university works\Final-Year_Firts_sem\FYP\INFO\REPO\CA-Classification-Framework\results\gpt-5-mini\zero_shot_cot\with_context\recovery\retry_parse_failures.json
✓ Merged 19 predictions.
⚠ zero_shot_cot_with_context: still unresolved=21 | rows=2189/2210

==========================================================================================
zero_shot_cot_with_context | strict pass 3 | unresolved before: 21
==========================================================================================
zero_shot_cot_with_context: strict retry file created (21 IDs) -> d:\university works\Final-Year_Firts_sem\FYP\INFO\REPO\CA-Classification-Framework\results\gpt-5-mini\zero_shot_cot\with_context\recovery\retry_requests_pass3.jsonl
Uploading: retry_requests_pass3.jsonl
✓ Upload completed
File Id : file-EF42U4yuRt86nSmts4YxMT
Creating batch job...
✓ Batch job created
Batch Job : batch_6a68cfde7e6481909ca5a5fafe8eee55
State     : validating

Waiting for batch job to complete...

21:20:54 | validating | 0/0
21:21:25 | in_progress | 0/21
21:21:55 | in_progress | 0/21
21:22:26 | in_progress | 0/21
21:22:56 | in_progress | 0/21
21:23:27 | in_progress | 0/21
21:23:58 | in_progress | 0/21
21:24:28 | in_progress | 0/21
21:24:59 | in_progress | 0/21
21:25:29 | in_progress | 0/21
21:26:00 | in_progress | 0/21
21:26:30 | in_progress | 0/21
21:27:01 | in_progress | 0/21
21:27:31 | in_progress | 0/21
21:28:02 | completed | 21/21

✓ Batch job completed successfully.
⚠ Recovered evaluation fields from 5 malformed JSON response(s): d:\university works\Final-Year_Firts_sem\FYP\INFO\REPO\CA-Classification-Framework\results\gpt-5-mini\zero_shot_cot\with_context\recovery\retry_field_recoveries.json
⚠ Retry still has 11 unresolved malformed response(s): d:\university works\Final-Year_Firts_sem\FYP\INFO\REPO\CA-Classification-Framework\results\gpt-5-mini\zero_shot_cot\with_context\recovery\retry_parse_failures.json
✓ Merged 10 predictions.
⚠ zero_shot_cot_with_context: still unresolved=11 | rows=2199/2210

==========================================================================================
zero_shot_cot_with_context | strict pass 4 | unresolved before: 11
==========================================================================================
zero_shot_cot_with_context: strict retry file created (11 IDs) -> d:\university works\Final-Year_Firts_sem\FYP\INFO\REPO\CA-Classification-Framework\results\gpt-5-mini\zero_shot_cot\with_context\recovery\retry_requests_pass4.jsonl
Uploading: retry_requests_pass4.jsonl
✓ Upload completed
File Id : file-Cm5ESS3RkMHUnsbtLheeqQ
Creating batch job...
✓ Batch job created
Batch Job : batch_6a68d18f4dfc81909e7a18c6bb668071
State     : validating

Waiting for batch job to complete...

21:28:07 | validating | 0/0
21:28:38 | in_progress | 3/11
21:29:08 | in_progress | 3/11
21:29:39 | in_progress | 5/11
21:30:09 | completed | 11/11

✓ Batch job completed successfully.
⚠ Recovered evaluation fields from 1 malformed JSON response(s): d:\university works\Final-Year_Firts_sem\FYP\INFO\REPO\CA-Classification-Framework\results\gpt-5-mini\zero_shot_cot\with_context\recovery\retry_field_recoveries.json
⚠ Retry still has 7 unresolved malformed response(s): d:\university works\Final-Year_Firts_sem\FYP\INFO\REPO\CA-Classification-Framework\results\gpt-5-mini\zero_shot_cot\with_context\recovery\retry_parse_failures.json
✓ Merged 4 predictions.
⚠ zero_shot_cot_with_context: still unresolved=7 | rows=2203/2210

==========================================================================================
few_shot_cot_with_context | strict pass 2 | unresolved before: 3
==========================================================================================
few_shot_cot_with_context: strict retry file created (3 IDs) -> d:\university works\Final-Year_Firts_sem\FYP\INFO\REPO\CA-Classification-Framework\results\gpt-5-mini\few_shot_cot\with_context\recovery\retry_requests_pass2.jsonl
Uploading: retry_requests_pass2.jsonl
✓ Upload completed
File Id : file-YawDQzjYWoxLb9RPUoQur1
Creating batch job...
✓ Batch job created
Batch Job : batch_6a68d20f90848190953591dfeb752baf
State     : validating

Waiting for batch job to complete...

21:30:16 | validating | 0/0
21:30:46 | validating | 0/0
21:31:17 | in_progress | 0/3
21:31:47 | in_progress | 0/3
21:32:18 | in_progress | 2/3
21:32:49 | in_progress | 2/3
21:33:19 | in_progress | 2/3
21:33:50 | in_progress | 2/3
21:34:20 | completed | 3/3

✓ Batch job completed successfully.
✓ Merged 3 predictions.
✓ few_shot_cot_with_context: FULL_RECOVERED -> d:\university works\Final-Year_Firts_sem\FYP\INFO\REPO\CA-Classification-Framework\results\gpt-5-mini\few_shot_cot\with_context\predictions_recovered.jsonl

{'zero_shot_with_context': [{'status': 'done',
   'unresolved_before': 25,
   'unresolved_after': 13,
   'rows': 2197,
   'expected': 2210,
   'unresolved': 13,
   'partial_file': 'd:\\university works\\Final-Year_Firts_sem\\FYP\\INFO\\REPO\\CA-Classification-Framework\\results\\gpt-5-mini\\zero_shot\\with_context\\predictions_recovered_partial.jsonl',
   'full_file': 'd:\\university works\\Final-Year_Firts_sem\\FYP\\INFO\\REPO\\CA-Classification-Framework\\results\\gpt-5-mini\\zero_shot\\with_context\\predictions_recovered.jsonl',
   'pass': 2},
  {'status': 'done',
   'unresolved_before': 13,
   'unresolved_after': 10,
   'rows': 2200,
   'expected': 2210,
   'unresolved': 10,
   'partial_file': 'd:\\university works\\Final-Year_Firts_sem\\FYP\\INFO\\REPO\\CA-Classification-Framework\\results\\gpt-5-mini\\zero_shot\\with_context\\predictions_recovered_partial.jsonl',
   'full_file': 'd:\\university works\\Final-Year_Firts_sem\\FYP\\INFO\\REPO\\CA-Classification-Framework\\results\\gpt-5-mini\\zero_shot\\with_context\\predictions_recovered.jsonl',
   'pass': 3},
  {'status': 'done',
   'unresolved_before': 10,
   'unresolved_after': 9,
   'rows': 2201,
   'expected': 2210,
   'unresolved': 9,
   'partial_file': 'd:\\university works\\Final-Year_Firts_sem\\FYP\\INFO\\REPO\\CA-Classification-Framework\\results\\gpt-5-mini\\zero_shot\\with_context\\predictions_recovered_partial.jsonl',
   'full_file': 'd:\\university works\\Final-Year_Firts_sem\\FYP\\INFO\\REPO\\CA-Classification-Framework\\results\\gpt-5-mini\\zero_shot\\with_context\\predictions_recovered.jsonl',
   'pass': 4}],
 'zero_shot_cot_with_context': [{'status': 'done',
   'unresolved_before': 40,
   'unresolved_after': 21,
   'rows': 2189,
   'expected': 2210,
   'unresolved': 21,
   'partial_file': 'd:\\university works\\Final-Year_Firts_sem\\FYP\\INFO\\REPO\\CA-Classification-Framework\\results\\gpt-5-mini\\zero_shot_cot\\with_context\\predictions_recovered_partial.jsonl',
   'full_file': 'd:\\university works\\Final-Year_Firts_sem\\FYP\\INFO\\REPO\\CA-Classification-Framework\\results\\gpt-5-mini\\zero_shot_cot\\with_context\\predictions_recovered.jsonl',
   'pass': 2},
  {'status': 'done',
   'unresolved_before': 21,
   'unresolved_after': 11,
   'rows': 2199,
   'expected': 2210,
   'unresolved': 11,
   'partial_file': 'd:\\university works\\Final-Year_Firts_sem\\FYP\\INFO\\REPO\\CA-Classification-Framework\\results\\gpt-5-mini\\zero_shot_cot\\with_context\\predictions_recovered_partial.jsonl',
   'full_file': 'd:\\university works\\Final-Year_Firts_sem\\FYP\\INFO\\REPO\\CA-Classification-Framework\\results\\gpt-5-mini\\zero_shot_cot\\with_context\\predictions_recovered.jsonl',
   'pass': 3},
  {'status': 'done',
   'unresolved_before': 11,
   'unresolved_after': 7,
   'rows': 2203,
   'expected': 2210,
   'unresolved': 7,
   'partial_file': 'd:\\university works\\Final-Year_Firts_sem\\FYP\\INFO\\REPO\\CA-Classification-Framework\\results\\gpt-5-mini\\zero_shot_cot\\with_context\\predictions_recovered_partial.jsonl',
   'full_file': 'd:\\university works\\Final-Year_Firts_sem\\FYP\\INFO\\REPO\\CA-Classification-Framework\\results\\gpt-5-mini\\zero_shot_cot\\with_context\\predictions_recovered.jsonl',
   'pass': 4}],
 'few_shot_cot_with_context': [{'status': 'done',
   'unresolved_before': 3,
   'unresolved_after': 0,
   'rows': 2210,
   'expected': 2210,
   'unresolved': 0,
   'partial_file': 'd:\\university works\\Final-Year_Firts_sem\\FYP\\INFO\\REPO\\CA-Classification-Framework\\results\\gpt-5-mini\\few_shot_cot\\with_context\\predictions_recovered_partial.jsonl',
   'full_file': 'd:\\university works\\Final-Year_Firts_sem\\FYP\\INFO\\REPO\\CA-Classification-Framework\\results\\gpt-5-mini\\few_shot_cot\\with_context\\predictions_recovered.jsonl',
   'pass': 2}]}

In [65]:
# ============================================================
# Final fallback: one-by-one direct calls for unresolved IDs
# ============================================================


def _extract_response_text_from_direct_response(response_obj):
    """Extract text from a direct Responses API object/dict."""
    if hasattr(response_obj, "model_dump"):
        body = response_obj.model_dump()
    elif isinstance(response_obj, dict):
        body = response_obj
    else:
        body = {}

    text_parts = []
    for item in body.get("output", []):
        if item.get("type") == "message":
            for content_piece in item.get("content", []):
                if content_piece.get("type") in ("output_text", "text"):
                    text_parts.append(content_piece.get("text", ""))

    return "".join(text_parts).strip()


def _load_request_map(request_file):
    request_map = {}
    with open(request_file, "r", encoding="utf-8") as f:
        for line in f:
            record = json.loads(line)
            request_map[record["custom_id"]] = record
    return request_map


def run_direct_fallback_for_experiment(experiment):
    """
    Resolve remaining unresolved IDs using direct one-by-one calls.
    Uses existing strict merge logic to update partial/full recovered outputs.
    """
    custom_ids = _load_unresolved_custom_ids(experiment)
    if not custom_ids:
        print(f"{experiment['name']}: no unresolved IDs. Nothing to do.")
        return {
            "status": "no_unresolved",
            "resolved": 0,
            "unresolved": 0,
        }

    request_map = _load_request_map(experiment["request_file"])

    parsed_retry = []
    unresolved_failures = []

    print(f"{experiment['name']}: direct fallback for {len(custom_ids)} unresolved ID(s)")

    for idx, custom_id in enumerate(custom_ids, start=1):
        sample_id = int(str(custom_id).replace("sample_", ""))

        if custom_id not in request_map:
            unresolved_failures.append(
                {
                    "sample_id": sample_id,
                    "error": "custom_id not found in request file",
                }
            )
            continue

        try:
            base_request = request_map[custom_id]
            prompt = base_request["body"]["input"]
            strict_prompt = f"{prompt}{STRICT_RECOVERY_SUFFIX}"

            response = client.responses.create(
                model=MODEL_NAME,
                input=strict_prompt,
                max_output_tokens=MAX_OUTPUT_TOKENS,
            )

            response_text = _extract_response_text_from_direct_response(response)
            if response_text.startswith("```"):
                response_text = response_text.replace("```json", "").replace("```", "").strip()

            try:
                prediction = json.loads(response_text)
                if not isinstance(prediction, dict):
                    raise ValueError("Prediction is not a JSON object")
            except (json.JSONDecodeError, ValueError):
                prediction = recover_evaluation_fields(response_text)

            parsed_retry.append({
                "id": sample_id,
                "prediction": prediction,
            })

            print(f"  [{idx}/{len(custom_ids)}] ✓ sample_{sample_id}")

        except Exception as error:
            unresolved_failures.append(
                {
                    "sample_id": sample_id,
                    "error": str(error),
                }
            )
            print(f"  [{idx}/{len(custom_ids)}] ✗ sample_{sample_id} -> {error}")

    retry_predictions = merge_predictions(parsed_retry, df_lookup, experiment)

    merge_info = _merge_strict_pass_predictions(
        experiment,
        retry_predictions,
        custom_ids,
        unresolved_failures,
    )

    recovery_dir = get_recovery_directory(experiment)
    direct_failures_file = recovery_dir / "direct_fallback_failures.json"
    with open(direct_failures_file, "w", encoding="utf-8") as f:
        json.dump(unresolved_failures, f, indent=2)

    print(f"{experiment['name']}: direct fallback failures logged -> {direct_failures_file}")

    return {
        "status": "done",
        "resolved": len(parsed_retry),
        "unresolved": len(unresolved_failures),
        **merge_info,
    }


def run_direct_fallback_for_all_with_context():
    """Run direct fallback only for with-context experiments."""
    report = {}
    for experiment in EXPERIMENTS:
        if not experiment["context_enabled"]:
            continue
        report[experiment["name"]] = run_direct_fallback_for_experiment(experiment)
    return report


# Run this when ready:
# direct_report = run_direct_fallback_for_all_with_context()
# direct_report

In [66]:
direct_report = run_direct_fallback_for_all_with_context()
direct_report

zero_shot_with_context: direct fallback for 9 unresolved ID(s)
  [1/9] ✗ sample_241 -> Invalid recovered classification: None
  [2/9] ✗ sample_242 -> Invalid recovered classification: None
  [3/9] ✗ sample_250 -> Invalid recovered classification: None
  [4/9] ✗ sample_271 -> Invalid recovered classification: None
  [5/9] ✗ sample_272 -> Invalid recovered classification: None
  [6/9] ✗ sample_274 -> Invalid recovered classification: None
  [7/9] ✓ sample_32
  [8/9] ✗ sample_35 -> Invalid recovered classification: None
  [9/9] ✗ sample_600 -> Invalid recovered classification: None
✓ Merged 1 predictions.
⚠ zero_shot_with_context: still unresolved=8 | rows=2202/2210
zero_shot_with_context: direct fallback failures logged -> d:\university works\Final-Year_Firts_sem\FYP\INFO\REPO\CA-Classification-Framework\results\gpt-5-mini\zero_shot\with_context\recovery\direct_fallback_failures.json
zero_shot_cot_with_context: direct fallback for 7 unresolved ID(s)
  [1/7] ✗ sample_241 -> Invalid recovered classification: None
  [2/7] ✗ sample_272 -> Invalid recovered classification: None
  [3/7] ✓ sample_273
  [4/7] ✗ sample_34 -> Invalid recovered classification: None
  [5/7] ✗ sample_35 -> Invalid recovered classification: None
  [6/7] ✓ sample_729
  [7/7] ✗ sample_767 -> Invalid recovered classification: None
✓ Merged 2 predictions.
⚠ zero_shot_cot_with_context: still unresolved=5 | rows=2205/2210
zero_shot_cot_with_context: direct fallback failures logged -> d:\university works\Final-Year_Firts_sem\FYP\INFO\REPO\CA-Classification-Framework\results\gpt-5-mini\zero_shot_cot\with_context\recovery\direct_fallback_failures.json
few_shot_cot_with_context: no unresolved IDs. Nothing to do.

{'zero_shot_with_context': {'status': 'done',
  'resolved': 1,
  'unresolved': 8,
  'rows': 2202,
  'expected': 2210,
  'partial_file': 'd:\\university works\\Final-Year_Firts_sem\\FYP\\INFO\\REPO\\CA-Classification-Framework\\results\\gpt-5-mini\\zero_shot\\with_context\\predictions_recovered_partial.jsonl',
  'full_file': 'd:\\university works\\Final-Year_Firts_sem\\FYP\\INFO\\REPO\\CA-Classification-Framework\\results\\gpt-5-mini\\zero_shot\\with_context\\predictions_recovered.jsonl'},
 'zero_shot_cot_with_context': {'status': 'done',
  'resolved': 2,
  'unresolved': 5,
  'rows': 2205,
  'expected': 2210,
  'partial_file': 'd:\\university works\\Final-Year_Firts_sem\\FYP\\INFO\\REPO\\CA-Classification-Framework\\results\\gpt-5-mini\\zero_shot_cot\\with_context\\predictions_recovered_partial.jsonl',
  'full_file': 'd:\\university works\\Final-Year_Firts_sem\\FYP\\INFO\\REPO\\CA-Classification-Framework\\results\\gpt-5-mini\\zero_shot_cot\\with_context\\predictions_recovered.jsonl'},
 'few_shot_cot_with_context': {'status': 'no_unresolved',
  'resolved': 0,
  'unresolved': 0}}

In [68]:
# ============================================================
# Final local fallback: heuristic fill for any still-unresolved IDs
# ============================================================

# This step does NOT call the API.
# It fills only IDs that remain unresolved after retry + direct fallback,
# then writes a full-size recovered file for evaluation pipeline continuity.

HEURISTIC_FILL_REASON = (
    "Heuristic fallback fill: model output remained invalid after batch retries "
    "and direct fallback; placeholder label used to keep evaluation file complete."
)


def _rows_to_map(rows):
    return {str(item["id"]): item for item in rows}


def _build_heuristic_prediction_row(experiment, sample_id):
    """
    Build a conservative placeholder prediction record for unresolved IDs.
    Uses Non-Flaky/Non-Flaky to avoid fabricating flaky categories.
    """
    if sample_id not in df_lookup.index:
        raise KeyError(f"Sample {sample_id} not found in evaluation dataset")

    sample = df_lookup.loc[sample_id]

    return {
        "id": sample_id,
        "test_id": sample["test_id"],
        "ground_truth_classification": "Flaky" if sample["isFlaky"] else "Non-Flaky",
        "ground_truth_category": sample["issue_category"],
        "predicted_classification": "Non-Flaky",
        "predicted_category": "Non-Flaky",
        "reasoning": HEURISTIC_FILL_REASON,
        "evidence": [],
        "model": MODEL_NAME,
        "prompt_type": experiment["prompt_type"],
        "context_enabled": experiment["context_enabled"],
        "latency_ms": None,
    }


def apply_heuristic_fill_for_experiment(experiment, write_as_full=True):
    """
    Fill unresolved IDs locally and optionally materialize predictions_recovered.jsonl.

    Returns:
        dict summary
    """
    experiment_dir = get_experiment_directory(experiment)
    recovery_dir = get_recovery_directory(experiment)

    unresolved_file = recovery_dir / "unresolved_retry_ids.json"
    if not unresolved_file.exists():
        print(f"{experiment['name']}: unresolved file not found; skip.")
        return {"status": "skip_no_unresolved_file"}

    with open(unresolved_file, "r", encoding="utf-8") as f:
        unresolved_ids = [int(str(x).replace("sample_", "")) for x in json.load(f)]

    if not unresolved_ids:
        print(f"{experiment['name']}: no unresolved IDs; nothing to fill.")
        return {"status": "already_complete", "filled": 0}

    base_candidates = [
        experiment_dir / "predictions_recovered_partial.jsonl",
        experiment_dir / "predictions_recovered.jsonl",
        experiment_dir / "predictions.jsonl",
    ]

    base_file = None
    for candidate in base_candidates:
        if candidate.exists():
            base_file = candidate
            break

    if base_file is None:
        raise FileNotFoundError(f"No base predictions file found for {experiment['name']}")

    with open(base_file, "r", encoding="utf-8") as f:
        base_rows = [json.loads(line) for line in f]

    row_map = _rows_to_map(base_rows)

    filled_rows = []
    for sample_id in unresolved_ids:
        key = str(sample_id)
        if key in row_map:
            continue
        filled = _build_heuristic_prediction_row(experiment, sample_id)
        row_map[key] = filled
        filled_rows.append(sample_id)

    combined = list(row_map.values())
    combined.sort(key=lambda item: int(item["id"]))

    # Keep a transparent artifact dedicated to heuristic fill.
    heuristic_file = experiment_dir / "predictions_recovered_heuristic.jsonl"
    with open(heuristic_file, "w", encoding="utf-8") as f:
        for item in combined:
            f.write(json.dumps(item, ensure_ascii=False) + "\n")

    full_file = experiment_dir / "predictions_recovered.jsonl"
    if write_as_full and len(combined) == len(df_lookup):
        with open(full_file, "w", encoding="utf-8") as f:
            for item in combined:
                f.write(json.dumps(item, ensure_ascii=False) + "\n")

        # Mark unresolved as cleared because this file is now complete by policy.
        with open(unresolved_file, "w", encoding="utf-8") as f:
            json.dump([], f, indent=2)

    policy_file = recovery_dir / "heuristic_fill_policy.json"
    with open(policy_file, "w", encoding="utf-8") as f:
        json.dump(
            {
                "filled_ids": filled_rows,
                "filled_count": len(filled_rows),
                "prediction_defaults": {
                    "predicted_classification": "Non-Flaky",
                    "predicted_category": "Non-Flaky",
                },
                "reason": HEURISTIC_FILL_REASON,
                "source_base_file": str(base_file),
                "output_heuristic_file": str(heuristic_file),
                "output_full_file": str(full_file) if write_as_full else None,
            },
            f,
            indent=2,
        )

    print(f"{experiment['name']}: heuristic filled {len(filled_rows)} unresolved ID(s).")
    print(f"  heuristic file -> {heuristic_file}")
    if write_as_full:
        print(f"  full file      -> {full_file}")

    return {
        "status": "done",
        "filled": len(filled_rows),
        "rows": len(combined),
        "expected": len(df_lookup),
        "heuristic_file": str(heuristic_file),
        "full_file": str(full_file) if write_as_full else None,
    }


def apply_heuristic_fill_for_all_pending_with_context(write_as_full=True):
    """Apply heuristic fill only to with-context experiments still unresolved."""
    report = {}
    for experiment in EXPERIMENTS:
        if not experiment["context_enabled"]:
            continue
        report[experiment["name"]] = apply_heuristic_fill_for_experiment(
            experiment,
            write_as_full=write_as_full,
        )
    return report


# Run this only if you decide to force 100% row completeness locally:
# heuristic_report = apply_heuristic_fill_for_all_pending_with_context(write_as_full=True)
# heuristic_report

In [69]:
heuristic_report = apply_heuristic_fill_for_all_pending_with_context(write_as_full=True)
heuristic_report

zero_shot_with_context: heuristic filled 8 unresolved ID(s).
  heuristic file -> d:\university works\Final-Year_Firts_sem\FYP\INFO\REPO\CA-Classification-Framework\results\gpt-5-mini\zero_shot\with_context\predictions_recovered_heuristic.jsonl
  full file      -> d:\university works\Final-Year_Firts_sem\FYP\INFO\REPO\CA-Classification-Framework\results\gpt-5-mini\zero_shot\with_context\predictions_recovered.jsonl
zero_shot_cot_with_context: heuristic filled 5 unresolved ID(s).
  heuristic file -> d:\university works\Final-Year_Firts_sem\FYP\INFO\REPO\CA-Classification-Framework\results\gpt-5-mini\zero_shot_cot\with_context\predictions_recovered_heuristic.jsonl
  full file      -> d:\university works\Final-Year_Firts_sem\FYP\INFO\REPO\CA-Classification-Framework\results\gpt-5-mini\zero_shot_cot\with_context\predictions_recovered.jsonl
few_shot_cot_with_context: no unresolved IDs; nothing to fill.

{'zero_shot_with_context': {'status': 'done',
  'filled': 8,
  'rows': 2210,
  'expected': 2210,
  'heuristic_file': 'd:\\university works\\Final-Year_Firts_sem\\FYP\\INFO\\REPO\\CA-Classification-Framework\\results\\gpt-5-mini\\zero_shot\\with_context\\predictions_recovered_heuristic.jsonl',
  'full_file': 'd:\\university works\\Final-Year_Firts_sem\\FYP\\INFO\\REPO\\CA-Classification-Framework\\results\\gpt-5-mini\\zero_shot\\with_context\\predictions_recovered.jsonl'},
 'zero_shot_cot_with_context': {'status': 'done',
  'filled': 5,
  'rows': 2210,
  'expected': 2210,
  'heuristic_file': 'd:\\university works\\Final-Year_Firts_sem\\FYP\\INFO\\REPO\\CA-Classification-Framework\\results\\gpt-5-mini\\zero_shot_cot\\with_context\\predictions_recovered_heuristic.jsonl',
  'full_file': 'd:\\university works\\Final-Year_Firts_sem\\FYP\\INFO\\REPO\\CA-Classification-Framework\\results\\gpt-5-mini\\zero_shot_cot\\with_context\\predictions_recovered.jsonl'},
 'few_shot_cot_with_context': {'status': 'already_complete', 'filled': 0}}